"""Downloader profile declarations for the TDX provider package."""

from __future__ import annotations

from typing import Any


def _tdx_output_path_parts(interface_name: str) -> list[str]:
    return ["通达信", "股票数据", _tdx_interface_group_path(interface_name), interface_name]


def _core_table_output_path_parts(table_name: str) -> list[str]:
    return ["core", f"table={table_name}"]


def _tdx_interface_group_path(interface_name: str) -> str:
    if interface_name in {
        "stock_limit_ladder_tdx",
        "stock_theme_strength_rank_tdx",
    }:
        return "短线数据"
    if interface_name in {
        "stock_auction_process_tdx",
        "stock_auction_result_tdx",
        "stock_auction_result_history_tdx",
    }:
        return "竞价数据"
    if interface_name in {
        "stock_realtime_snapshot_tdx",
        "stock_realtime_rank_tdx",
        "stock_order_book_tdx",
        "stock_trade_detail_today_tdx",
    }:
        return "实时数据"
    if interface_name in {
        "stock_kline_daily_tdx",
        "stock_kline_weekly_tdx",
        "stock_kline_monthly_tdx",
        "stock_kline_5min_tdx",
        "stock_kline_15min_tdx",
        "stock_kline_30min_tdx",
        "stock_kline_60min_tdx",
    }:
        return "K线数据"
    if interface_name in {
        "stock_intraday_today_tdx",
        "stock_intraday_history_tdx",
    }:
        return "分时数据"
    return "基础数据"


def tdx_downloader_profiles(
    concurrency_profile_cls: type[Any],
    downloader_profile_cls: type[Any],
) -> dict[str, Any]:
    tdx_single_kline_concurrency = concurrency_profile_cls(
        mode="fixed",
        default_source_server_count=1,
        max_source_server_count=1,
        default_connections_per_server=1,
        max_connections_per_server=1,
        default_max_concurrent_tasks=1,
        max_max_concurrent_tasks=1,
        default_batch_size=1,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="默认只请求单只证券的小样本日 K 线；如需批量或全市场采集，必须显式传入 code 列表和执行预算。",
    )

    tdx_adj_factor_concurrency = concurrency_profile_cls(
        mode="fixed",
        default_source_server_count=1,
        max_source_server_count=1,
        default_connections_per_server=1,
        max_connections_per_server=1,
        default_max_concurrent_tasks=1,
        max_max_concurrent_tasks=1,
        default_batch_size=1,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="默认只请求单只证券的小样本复权因子；该接口会读取除权除息事件和未复权日 K，批量运行需显式传参。",
    )

    tdx_full_snapshot_concurrency = concurrency_profile_cls(
        mode="fixed",
        default_source_server_count=1,
        max_source_server_count=1,
        default_connections_per_server=1,
        max_connections_per_server=1,
        default_max_concurrent_tasks=1,
        max_max_concurrent_tasks=1,
        default_batch_size=1,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="这个接口一次就能拿完整列表；采集完成后会自动断开连接。",
    )

    tdx_stock_codes_concurrency = concurrency_profile_cls(
        mode="fixed",
        default_source_server_count=1,
        max_source_server_count=1,
        default_connections_per_server=3,
        max_connections_per_server=3,
        default_max_concurrent_tasks=3,
        max_max_concurrent_tasks=3,
        default_batch_size=1,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="这个接口会并行扫描沪、深、北三个市场；采集完成后会自动断开连接。",
    )

    tdx_stock_suspensions_concurrency = concurrency_profile_cls(
        mode="fixed",
        default_source_server_count=4,
        max_source_server_count=4,
        default_connections_per_server=2,
        max_connections_per_server=2,
        default_max_concurrent_tasks=8,
        max_max_concurrent_tasks=8,
        default_batch_size=80,
        batch_size_editable=False,
        max_batch_size=80,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="一开始创建 4 × 2 连接池；股票池阶段只扫描沪、深、北三路，天然用不满，停牌状态阶段会批量使用并发，批大小 80；采集完成后会自动断开连接。",
    )

    tdx_daily_share_concurrency = concurrency_profile_cls(
        mode="fixed",
        mode_editable=False,
        default_source_server_count=4,
        source_server_count_editable=False,
        max_source_server_count=4,
        default_connections_per_server=2,
        connections_per_server_editable=False,
        max_connections_per_server=2,
        default_max_concurrent_tasks=8,
        max_concurrent_tasks_editable=False,
        max_max_concurrent_tasks=8,
        default_batch_size=80,
        batch_size_editable=False,
        max_batch_size=80,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="这个接口会先扫描股票池，再把财务快照按每批最多 80 只拆开；默认使用当前最快的 4 个普通行情服务器，每个服务器 2 条长连接，采集完成后会自动断开连接。",
    )

    tdx_daily_price_limit_concurrency = concurrency_profile_cls(
        mode="fixed",
        mode_editable=False,
        default_source_server_count=4,
        source_server_count_editable=False,
        max_source_server_count=4,
        default_connections_per_server=2,
        connections_per_server_editable=False,
        max_connections_per_server=2,
        default_max_concurrent_tasks=8,
        max_concurrent_tasks_editable=False,
        max_max_concurrent_tasks=8,
        default_batch_size=80,
        batch_size_editable=False,
        max_batch_size=80,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="采集只保存最新涨跌停价格：先扫描股票池，再按每批最多 80 只请求实时快照昨收并计算；默认使用当前最快的 4 个普通行情服务器，每个服务器 2 条长连接，采集完成后会自动断开连接。",
    )

    tdx_capital_changes_concurrency = concurrency_profile_cls(
        mode="fixed",
        mode_editable=False,
        default_source_server_count=8,
        source_server_count_editable=False,
        max_source_server_count=8,
        default_connections_per_server=2,
        connections_per_server_editable=False,
        max_connections_per_server=2,
        default_max_concurrent_tasks=16,
        max_concurrent_tasks_editable=False,
        max_max_concurrent_tasks=16,
        default_batch_size=1,
        batch_size_editable=False,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="这个接口会先扫描股票池，再逐只请求股本变迁事件；实测默认使用当前最快的 8 个普通行情服务器，每个服务器 2 条长连接，采集完成后会自动断开连接。",
    )

    tdx_limit_ladder_concurrency = concurrency_profile_cls(
        mode="fixed",
        mode_editable=False,
        default_source_server_count=1,
        source_server_count_editable=False,
        max_source_server_count=1,
        default_connections_per_server=1,
        connections_per_server_editable=False,
        max_connections_per_server=1,
        default_max_concurrent_tasks=1,
        max_concurrent_tasks_editable=False,
        max_max_concurrent_tasks=1,
        default_batch_size=1,
        batch_size_editable=False,
        max_batch_size=1,
        default_request_interval_ms=0,
        min_request_interval_ms=0,
        max_request_interval_ms=0,
        default_retry_count=0,
        max_retry_count=0,
        default_timeout_ms=30000,
        min_timeout_ms=30000,
        max_timeout_ms=30000,
        description="主体天梯列表一次可取，普通行情保持单连接；题材补全会在接口内部先用 6 个 F10 题材查询 worker，若首轮有题材为空的股票，再用 6 个 worker 补漏 1 轮，采集完成后会自动断开连接。",
    )

    def full_snapshot_profile(
        interface_name: str,
        *,
        display_name: str,
        description: str,
        concurrency: Any = tdx_full_snapshot_concurrency,
    ) -> Any:
        return downloader_profile_cls(
            interface_name=interface_name,
            display_name=display_name,
            downloader_type="full_snapshot",
            default_params={"scope": "all"},
            default_fields=None,
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=concurrency,
            primary_key="instrument_id",
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts(interface_name),
            required_columns=["instrument_id"],
            date_field=None,
            description=description,
        )

    def daily_share_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_daily_share_tdx",
            display_name="每日股本（盘前）",
            downloader_type="full_snapshot",
            default_params={"scope": "all"},
            default_fields=[
                "trade_date",
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "total_share",
                "float_share",
                "free_float_share_z",
                "finance_updated_date",
                "share_source",
            ],
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_daily_share_concurrency,
            primary_key=("trade_date", "instrument_id"),
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_daily_share_tdx"),
            snapshot_date_meta_keys=["tdx_stats_date", "snapshot_date", "data_date", "trade_date", "date"],
            file_stem_template="{interface_name}_{snapshot_date}",
            required_columns=["trade_date", "instrument_id"],
            expected_columns=[
                "trade_date",
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "total_share",
                "float_share",
                "free_float_share_z",
                "finance_updated_date",
                "share_source",
            ],
            date_field="trade_date",
            numeric_positive_columns=["total_share", "float_share", "free_float_share_z"],
            params=[
                ["scope", "string/list", "否", "股票范围：all 全部、main 主板、star 科创板、chinext 创业板、bse 北交所、cdr CDR；默认 all"],
                ["code", "string/list", "否", "证券代码：可选；不填则按股票范围拉取全量"],
                ["refresh_stats", "boolean", "否", "是否强制刷新盘前统计缓存；默认 false"],
                ["stats_cache_root", "string", "否", "盘前统计资源缓存目录；不传时使用项目 cache/tdx/stats"],
            ],
            description="自动取股票池并批量生成每日股本盘前快照；不填 code 时按股票范围拉取全量。财务快照每批最多 80 只，可用多服务器多长连接并发。",
        )

    def daily_price_limit_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_daily_price_limit_tdx",
            display_name="涨跌停价格",
            downloader_type="full_snapshot",
            default_params={"scope": "all"},
            default_fields=[
                "trade_date",
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "name",
                "name_flag",
                "pre_close_trade_date",
                "pre_close",
                "pre_close_source",
                "limit_up_price",
                "limit_down_price",
                "limit_ratio_pct",
                "limit_rule",
                "limit_status",
            ],
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_daily_price_limit_concurrency,
            primary_key=("trade_date", "instrument_id"),
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_daily_price_limit_tdx"),
            file_stem_template="{interface_name}_{snapshot_date}",
            required_columns=["trade_date", "instrument_id"],
            expected_columns=[
                "trade_date",
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "name",
                "name_flag",
                "pre_close_trade_date",
                "pre_close",
                "pre_close_source",
                "limit_up_price",
                "limit_down_price",
                "limit_ratio_pct",
                "limit_rule",
                "limit_status",
            ],
            date_field="trade_date",
            numeric_positive_columns=["pre_close", "limit_up_price", "limit_down_price"],
            params=[
                ["scope", "string/list", "否", "股票范围：all 全部、main 主板、star 科创板、chinext 创业板、bse 北交所、cdr CDR；默认 all"],
                ["code", "string/list", "否", "证券代码：可选；不填则按股票范围拉取全量"],
            ],
            description="自动取股票池并生成最新涨跌停价格；不填 code 时按股票范围拉取全量。该兼容下载固定使用实时快照昨收快速计算最新全量，历史日期查询请走接口页或 SDK。",
        )

    def capital_changes_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_capital_changes_tdx",
            display_name="股本变迁",
            downloader_type="full_snapshot",
            default_params={"scope": "all"},
            default_fields=[
                "instrument_id",
                "ts_code",
                "symbol",
                "tdx_code",
                "exchange",
                "event_date",
                "category_raw",
                "category_name",
                "c1",
                "c2",
                "c3",
                "c4",
                "c1_raw_hex",
                "c2_raw_hex",
                "c3_raw_hex",
                "c4_raw_hex",
                "record_hex",
            ],
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_capital_changes_concurrency,
            primary_key=("instrument_id", "record_hex"),
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_capital_changes_tdx"),
            required_columns=["instrument_id", "record_hex"],
            expected_columns=[
                "instrument_id",
                "ts_code",
                "symbol",
                "tdx_code",
                "exchange",
                "event_date",
                "category_raw",
                "category_name",
                "c1",
                "c2",
                "c3",
                "c4",
                "c1_raw_hex",
                "c2_raw_hex",
                "c3_raw_hex",
                "c4_raw_hex",
                "record_hex",
            ],
            date_field="event_date",
            params=[
                ["scope", "string/list", "否", "股票范围：all 全部、main 主板、star 科创板、chinext 创业板、bse 北交所、cdr CDR；默认 all"],
                ["code", "string/list", "否", "证券代码：可选；不填则按股票范围拉取全量"],
                ["category", "integer/string/list", "否", "事件类别：可选；常用 1/xdxr 除权除息、5/equity 股本变化、15/restructure 重整调整"],
            ],
            description="自动取股票池并逐只拉取股本变迁事件；不填 code 时按股票范围拉取全量。category 可选，用来只保存除权除息等某一类事件。",
        )

    def daily_kline_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_kline_daily_tdx",
            display_name="日K线",
            downloader_type="history",
            default_params={
                "code": "000001.SZ",
                "count": 800,
                "adjust": "none",
            },
            default_fields=[
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "trade_time",
                "period",
                "open",
                "high",
                "low",
                "close",
                "volume",
                "amount",
            ],
            output_layer="core",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_single_kline_concurrency,
            primary_key=("instrument_id", "trade_time", "period"),
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_kline_daily_tdx"),
            snapshot_date_meta_keys=["trade_date", "data_date", "snapshot_date", "date"],
            file_stem_template="{interface_name}_{snapshot_date}",
            partition_by=["trade_date"],
            required_columns=["instrument_id", "trade_time", "period"],
            expected_columns=[
                "instrument_id",
                "symbol",
                "tdx_code",
                "exchange",
                "trade_time",
                "period",
                "open",
                "high",
                "low",
                "close",
                "volume",
                "amount",
            ],
            datetime_field="trade_time",
            numeric_positive_columns=["open", "high", "low", "close", "volume", "amount"],
            field_mappings={
                "instrument_id": "ts_code",
                "trade_time": "trade_date",
                "volume": "vol",
            },
            params=[
                ["code", "string/list", "是", "证券代码：默认 000001.SZ；批量可传列表或英文逗号分隔字符串"],
                ["count", "integer", "否", "返回最近 K 线数量；默认 800，最大 65535"],
                ["adjust", "string", "否", "复权参数：none 不复权、qfq 前复权、hfq 后复权、fixed_qfq 定点前复权；默认 none"],
                ["anchor_date", "string", "否", "定点前复权锚点日期，仅 adjust=fixed_qfq 时使用，格式 YYYYMMDD 或 YYYY-MM-DD"],
            ],
            description="保存单只或显式代码列表的通达信日 K 线。默认仅小样本，不做全市场隐式展开；写入层为 core daily 的源端样本口径，生产级全市场转换仍需独立任务。",
        )

    def adj_factor_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_adj_factor_tdx",
            display_name="复权因子",
            downloader_type="history",
            default_params={
                "code": "000001.SZ",
                "adjust": "qfq",
            },
            default_fields=[
                "instrument_id",
                "ts_code",
                "symbol",
                "tdx_code",
                "exchange",
                "trade_date",
                "adj_factor",
            ],
            output_layer="core",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_adj_factor_concurrency,
            primary_key=("ts_code", "trade_date"),
            resource_group="tdx.quote",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_core_table_output_path_parts("adj_factor"),
            snapshot_date_meta_keys=["trade_date", "data_date", "snapshot_date", "date"],
            file_stem_template="{interface_name}_{snapshot_date}",
            write_mode="upsert_by_key",
            partition_by=["trade_date"],
            required_columns=["ts_code", "trade_date", "adj_factor"],
            expected_columns=[
                "instrument_id",
                "ts_code",
                "symbol",
                "tdx_code",
                "exchange",
                "trade_date",
                "adj_factor",
            ],
            date_field="trade_date",
            numeric_positive_columns=["adj_factor"],
            params=[
                ["code", "string/list", "是", "证券代码：默认 000001.SZ；批量可传列表或英文逗号分隔字符串"],
                ["adjust", "string", "否", "复权方向：qfq 前复权因子，hfq 后复权因子；默认 qfq"],
                ["anchor_date", "string", "否", "可选的前复权锚点日期，格式 YYYYMMDD 或 YYYY-MM-DD；仅 adjust=qfq 时使用"],
            ],
            description="保存单只或显式代码列表的复权因子。该因子由 TDX 除权除息事件和未复权日 K 计算得到，默认小样本，不做全市场隐式展开。",
        )

    def limit_ladder_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_limit_ladder_tdx",
            display_name="连板天梯",
            downloader_type="full_snapshot",
            default_params={
                "count": "all",
                "scope": "main",
                "include_touched": False,
                "topic_type": "theme",
            },
            default_fields=[
                "trade_date",
                "ladder_level",
                "limit_board_text",
                "instrument_id",
                "name",
                "last_price",
                "change_pct",
                "limit_status",
                "amount",
                "seal_amount",
                "seal_to_amount_ratio",
                "free_float_market_value",
                "primary_theme",
                "secondary_themes",
                "year_limit_up_days",
                "symbol",
                "exchange",
                "pre_close",
                "limit_up_price",
            ],
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_limit_ladder_concurrency,
            primary_key=("trade_date", "ladder_level", "instrument_id"),
            resource_group="tdx.f10",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_limit_ladder_tdx"),
            required_columns=["trade_date", "ladder_level", "instrument_id"],
            date_field="trade_date",
            numeric_positive_columns=["last_price", "amount", "seal_amount", "free_float_market_value"],
            params=[
                ["count", "integer/string", "否", "返回数量；默认 all 保存完整天梯，也可传数字只保存前 N 条，最大 500"],
                ["scope", "string/list", "否", "股票范围；默认 main 主板；可传 all、star、chinext、bse、cdr"],
                ["include_touched", "boolean", "否", "是否包含盘中触及涨停但当前未封住的股票；默认 false"],
                ["topic_type", "string", "否", "题材类型：theme 主题题材，sector 板块题材；默认 theme"],
            ],
            description="保存当前连板天梯快照；默认主板完整天梯，只统计当前封住涨停且剔除 ST / *ST 的股票。适合盘中或盘后定时留痕，不做历史全量回填。",
        )

    def theme_strength_rank_profile() -> Any:
        return downloader_profile_cls(
            interface_name="stock_theme_strength_rank_tdx",
            display_name="题材强度排行",
            downloader_type="full_snapshot",
            default_params={
                "count": "all",
                "scope": "main",
                "topic_type": "theme",
            },
            default_fields=[
                "rank",
                "trade_date",
                "topic_type",
                "topic_name",
                "topic_id",
                "theme_strength_score",
                "limit_up_count",
                "highest_ladder_level",
                "lianban_stock_count",
                "first_board_count",
                "leader_instrument_id",
                "leader_name",
                "leader_ladder_level",
                "leader_limit_board_text",
                "leader_seal_amount",
                "seal_amount_sum",
                "amount_sum",
                "top_stock_summary",
            ],
            output_layer="snapshot",
            output_format="parquet",
            supported_formats=["parquet", "csv", "jsonl"],
            default_connection_mode="long_connection",
            concurrency=tdx_limit_ladder_concurrency,
            primary_key=("trade_date", "topic_type", "topic_name"),
            resource_group="tdx.f10",
            adapter_factory="tdx",
            runtime_source_server_max_factory="tdx",
            default_output_path_parts=_tdx_output_path_parts("stock_theme_strength_rank_tdx"),
            required_columns=["trade_date", "topic_type", "topic_name"],
            date_field="trade_date",
            numeric_positive_columns=[
                "theme_strength_score",
                "limit_up_count",
                "highest_ladder_level",
                "seal_amount_sum",
                "amount_sum",
            ],
            params=[
                ["count", "integer/string", "否", "返回数量；默认 all 保存完整题材强度排行，也可传数字只保存前 N 条，最大 500"],
                ["scope", "string/list", "否", "股票范围；默认 main 主板；可传 all、star、chinext、bse、cdr"],
                ["topic_type", "string", "否", "题材类型：theme 主题题材，sector 板块题材；默认 theme"],
            ],
            description="保存当前题材强度排行快照；默认主板完整排行，复用连板天梯涨停池口径，只统计当前封住涨停且剔除 ST / *ST 的股票。",
        )

    return {
        "stock_codes_tdx": full_snapshot_profile(
            "stock_codes_tdx",
            display_name="最新股票列表",
            description="一次性拉取通达信最新股票列表并保存为本地快照。",
            concurrency=tdx_stock_codes_concurrency,
        ),
        "stock_suspensions_tdx": full_snapshot_profile(
            "stock_suspensions_tdx",
            display_name="最新停牌列表",
            description="一次性拉取通达信最新停牌股票列表并保存为本地快照。",
            concurrency=tdx_stock_suspensions_concurrency,
        ),
        "stock_st_list_tdx": full_snapshot_profile(
            "stock_st_list_tdx",
            display_name="最新ST股票列表",
            description="一次性拉取通达信最新 ST / *ST 股票列表并保存为本地快照。",
            concurrency=tdx_stock_codes_concurrency,
        ),
        "stock_daily_share_tdx": daily_share_profile(),
        "stock_daily_price_limit_tdx": daily_price_limit_profile(),
        "stock_capital_changes_tdx": capital_changes_profile(),
        "stock_kline_daily_tdx": daily_kline_profile(),
        "stock_adj_factor_tdx": adj_factor_profile(),
        "stock_limit_ladder_tdx": limit_ladder_profile(),
        "stock_theme_strength_rank_tdx": theme_strength_rank_profile(),
    }
