"""TDX request interface declarations used by the adapter dispatch layer."""

from __future__ import annotations

from typing import Any

from .request_params import INDEX_KLINE_INTERFACE, KLINE_INTERFACE_SPECS
from .tdx_f10_names import F10_INTERFACE_NAMES


FINANCE_INTERFACE_FIELDS: dict[str, tuple[str, ...]] = {
    "stock_finance_summary_tdx": (
        "instrument_id",
        "symbol",
        "tdx_code",
        "exchange",
        "updated_date",
        "ipo_date",
        "total_share",
        "float_share",
        "eps",
        "bps",
        "total_assets",
        "net_assets",
        "revenue",
        "net_profit",
        "operating_cashflow",
        "shareholder_count",
    ),
    "stock_share_capital_tdx": (
        "instrument_id",
        "symbol",
        "tdx_code",
        "exchange",
        "updated_date",
        "total_share",
        "float_share",
        "state_share",
        "founder_legal_person_share",
        "legal_person_share",
        "b_share",
        "h_share",
        "shareholder_count",
    ),
    "stock_balance_summary_tdx": (
        "instrument_id",
        "symbol",
        "tdx_code",
        "exchange",
        "updated_date",
        "total_assets",
        "current_assets",
        "fixed_assets",
        "intangible_assets",
        "current_liabilities",
        "long_term_liabilities",
        "capital_reserve",
        "net_assets",
        "accounts_receivable",
        "inventory",
    ),
    "stock_profit_cashflow_summary_tdx": (
        "instrument_id",
        "symbol",
        "tdx_code",
        "exchange",
        "updated_date",
        "revenue",
        "main_business_profit",
        "operating_profit",
        "investment_income",
        "operating_cashflow",
        "total_cashflow",
        "total_profit",
        "after_tax_profit",
        "net_profit",
        "undistributed_profit",
        "eps",
        "bps",
    ),
    "stock_finance_profile_tdx": (
        "instrument_id",
        "symbol",
        "tdx_code",
        "exchange",
        "updated_date",
        "ipo_date",
        "province_raw",
        "province_name",
        "province_board_name",
        "province_board_code",
        "industry_raw",
        "tdx_industry_code",
        "tdx_industry_name",
        "tdx_industry_path",
        "tdx_research_industry_code",
        "tdx_research_industry_name",
        "tdx_research_industry_path",
    ),
}

DAILY_SHARE_FINANCE_BATCH_SIZE = 80

INTRADAY_SUBCHART_INTERFACE_SPECS: dict[str, dict[str, Any]] = {
    "stock_intraday_buy_sell_strength_tdx": {
        "selector": 0x00,
        "protocol": "0x051b",
        "fields": (
            "instrument_id",
            "symbol",
            "tdx_code",
            "exchange",
            "minute_time",
            "minute_index",
            "bid_order",
            "ask_order",
        ),
    },
    "stock_intraday_volume_comparison_tdx": {
        "selector": 0x0B,
        "protocol": "0x051b",
        "fields": (
            "instrument_id",
            "symbol",
            "tdx_code",
            "exchange",
            "minute_time",
            "minute_index",
            "today_volume",
            "yesterday_volume",
            "volume_change",
            "volume_change_pct",
        ),
    },
}

SUPPORTED_INTERFACES: set[str] = {
    "stock_codes_tdx",
    "index_codes_tdx",
    "index_realtime_snapshot_tdx",
    "index_realtime_rank_tdx",
    "index_quote_refresh_tdx",
    "index_intraday_today_tdx",
    "index_intraday_history_tdx",
    INDEX_KLINE_INTERFACE,
    "etf_codes_tdx",
    "etf_realtime_snapshot_tdx",
    "etf_realtime_rank_tdx",
    "etf_kline_tdx",
    "etf_intraday_today_tdx",
    "etf_intraday_history_tdx",
    "etf_trades_today_tdx",
    "etf_trades_history_tdx",
    "etf_auction_process_tdx",
    "etf_auction_result_tdx",
    "stock_st_list_tdx",
    "stock_suspensions_tdx",
    "stock_daily_share_tdx",
    "stock_daily_price_limit_tdx",
    "stock_capital_changes_tdx",
    "stock_adj_factor_tdx",
    "stock_limit_ladder_tdx",
    "stock_theme_strength_rank_tdx",
    "stock_realtime_rank_tdx",
    "stock_realtime_snapshot_tdx",
    "stock_order_book_tdx",
    "stock_auction_process_tdx",
    "stock_auction_result_tdx",
    "stock_auction_result_history_tdx",
    "stock_shortline_indicators_tdx",
    *INTRADAY_SUBCHART_INTERFACE_SPECS,
    "stock_intraday_today_tdx",
    "stock_intraday_history_tdx",
    "stock_intraday_recent_history_tdx",
    "stock_trades_today_tdx",
    "stock_trades_history_tdx",
    *FINANCE_INTERFACE_FIELDS,
    *F10_INTERFACE_NAMES,
    *KLINE_INTERFACE_SPECS,
}
