"""Lazy compatibility exports for legacy TDX request-module private names."""

from __future__ import annotations

from importlib import import_module
from typing import Any


def _tdx(module: str, name: str) -> tuple[str, str]:
    return (f"axdata_source_tdx.{module}", name)


_REQUEST_MODULE_COMPAT_EXPORTS: dict[str, tuple[str, str]] = {
    "timedelta": ("datetime", "timedelta"),
    "TdxRequestAdapter": _tdx("request_entrypoints", "TdxRequestAdapter"),
    "EXCHANGE_TO_MARKET": _tdx("codes", "EXCHANGE_TO_MARKET"),
    "MARKET_TO_EXCHANGE": _tdx("codes", "MARKET_TO_EXCHANGE"),
    "MARKET_TO_ID": _tdx("codes", "MARKET_TO_ID"),
    "SUFFIX_TO_MARKET": _tdx("codes", "SUFFIX_TO_MARKET"),
    "exchange_to_market": _tdx("codes", "exchange_to_market"),
    "instrument_id_to_tdx_code": _tdx("codes", "instrument_id_to_tdx_code"),
    "tdx_code_to_instrument_id": _tdx("codes", "tdx_code_to_instrument_id"),
    "DAILY_SHARE_FINANCE_BATCH_SIZE": _tdx("interface_sets", "DAILY_SHARE_FINANCE_BATCH_SIZE"),
    "FINANCE_INTERFACE_FIELDS": _tdx("interface_sets", "FINANCE_INTERFACE_FIELDS"),
    "INTRADAY_SUBCHART_INTERFACE_SPECS": _tdx(
        "interface_sets",
        "INTRADAY_SUBCHART_INTERFACE_SPECS",
    ),
    "SUPPORTED_INTERFACES": _tdx("interface_sets", "SUPPORTED_INTERFACES"),
    "DEFAULT_QUOTE_BATCH_SIZE": _tdx("request_limits", "DEFAULT_QUOTE_BATCH_SIZE"),
    "TDX_RANK_CATEGORY_ALIASES": _tdx("rank_params", "TDX_RANK_CATEGORY_ALIASES"),
    "TDX_RANK_SORT_ALIASES": _tdx("rank_params", "TDX_RANK_SORT_ALIASES"),
    "INDEX_KLINE_INTERFACE": _tdx("request_params", "INDEX_KLINE_INTERFACE"),
    "KLINE_INTERFACE_SPECS": _tdx("request_params", "KLINE_INTERFACE_SPECS"),
    "TDX_EXACT_REQUEST_METHODS": _tdx("request_dispatch", "TDX_EXACT_REQUEST_METHODS"),
    "F10_INTERFACE_NAMES": _tdx("tdx_f10_names", "F10_INTERFACE_NAMES"),
    "TDX_CODE_PAGE_SIZE": _tdx("request_limits", "TDX_CODE_PAGE_SIZE"),
    "TDX_KLINE_HOST_COUNT": _tdx("request_limits", "TDX_KLINE_HOST_COUNT"),
    "TDX_KLINE_POOL_SIZE": _tdx("request_limits", "TDX_KLINE_POOL_SIZE"),
    "TDX_KLINE_MAX_COUNT": _tdx("request_params", "TDX_KLINE_MAX_COUNT"),
    "TDX_LIMIT_LADDER_SCAN_PAGE_SIZE": _tdx("request_limits", "TDX_LIMIT_LADDER_SCAN_PAGE_SIZE"),
    "TDX_RANK_DEFAULT_COUNT": _tdx("request_limits", "TDX_RANK_DEFAULT_COUNT"),
    "TDX_RANK_MAX_COUNT": _tdx("request_limits", "TDX_RANK_MAX_COUNT"),
    "TDX_RANK_MAX_START": _tdx("request_limits", "TDX_RANK_MAX_START"),
    "TDX_SUSPENSION_HOST_COUNT": _tdx("request_limits", "TDX_SUSPENSION_HOST_COUNT"),
    "TDX_SUSPENSION_POOL_SIZE": _tdx("request_limits", "TDX_SUSPENSION_POOL_SIZE"),
    "TDX_TRADE_MAX_START": _tdx("request_limits", "TDX_TRADE_MAX_START"),
    "TDX_TRADE_PAGE_SIZE": _tdx("request_limits", "TDX_TRADE_PAGE_SIZE"),
    "normalize_security": _tdx("security_codes", "normalize_security"),
    "prepare_limit_ladder_source_rows": _tdx("limit_ladder_fetch", "prepare_limit_ladder_source_rows"),
    "request_f10_dispatch_result": _tdx("f10_executor", "request_f10_dispatch_result"),
    "request_f10_many_with_default_interface": _tdx("f10_executor", "request_f10_many_with_default_interface"),
    "request_topic_rows_lookup_result": _tdx("f10_executor", "request_topic_rows_lookup_result"),
    "build_adjustment_factors": _tdx("adjustment", "build_adjustment_factors"),
    "load_finance_local_maps_from_root": _tdx("finance_maps", "load_finance_local_maps_from_root"),
    "lookup_finance_profile_maps": _tdx("finance_maps", "lookup_finance_profile_maps"),
    "selected_factor_value": _tdx("adjustment", "selected_factor_value"),
    "create_tdx_client": _tdx("request_entrypoints", "create_tdx_client"),
    "_tdx_env_int": _tdx("request_entrypoints", "_tdx_env_int"),
    "request_realtime_refresh_rows": _tdx("request_entrypoints", "request_realtime_refresh_rows"),
    "SourceRequestError": ("axdata_core.source_errors", "SourceRequestError"),
    "SourceRequestValidationError": ("axdata_core.source_errors", "SourceRequestValidationError"),
    "SourceUnavailableError": ("axdata_core.source_errors", "SourceUnavailableError"),
    "_DEFAULT_PRICE_DECIMAL": _tdx("snapshot_normalize", "DEFAULT_PRICE_DECIMAL"),
    "_adj_factor_adjust_param": _tdx("request_params", "adj_factor_adjust_param"),
    "_adjust_param": _tdx("request_params", "adjust_param"),
    "_anchor_date_param": _tdx("request_params", "anchor_date_param"),
    "_attack_pct": _tdx("normalize_utils", "attack_pct"),
    "_attach_limit_ladder_themes": _tdx("limit_ladder_topics", "attach_limit_ladder_themes"),
    "_auction_open_volume_hand": _tdx("normalize_utils", "auction_open_volume_hand"),
    "_avg_price_from_raw": _tdx("time_series_normalize", "avg_price_from_raw"),
    "_average_price": _tdx("normalize_utils", "average_price"),
    "_balance_pct": _tdx("normalize_utils", "balance_pct"),
    "_bar_trade_date": _tdx("normalize_utils", "bar_trade_date"),
    "_before_daily_close_buffer": _tdx("derived_rows", "before_daily_close_buffer"),
    "_board_from_tdx_code": _tdx("security_codes", "board_from_tdx_code"),
    "_board_matches": _tdx("request_filters", "board_matches"),
    "_bool_param": _tdx("request_params", "bool_param"),
    "_bytes_hex": _tdx("normalize_utils", "bytes_hex"),
    "_capital_change_category_matches": _tdx("finance_normalize", "capital_change_category_matches"),
    "_capital_change_record_key": _tdx("finance_normalize", "capital_change_record_key"),
    "_capital_change_value": _tdx("finance_normalize", "capital_change_value"),
    "_chunked": _tdx("execution_utils", "chunked"),
    "_client_pool_size": _tdx("execution_utils", "client_pool_size"),
    "_code_matches": _tdx("request_filters", "code_matches"),
    "_daily_share_source": _tdx("derived_rows", "daily_share_source"),
    "_default_daily_price_limit_trade_date": _tdx("derived_rows", "default_daily_price_limit_trade_date"),
    "_drawdown_pct": _tdx("normalize_utils", "drawdown_pct"),
    "_elapsed_monotonic_ms": _tdx("execution_utils", "elapsed_monotonic_ms"),
    "_emit_batch_progress": _tdx("execution_utils", "emit_batch_progress"),
    "_emit_price_limit_progress": _tdx("execution_utils", "emit_price_limit_progress"),
    "_emit_source_progress": _tdx("execution_utils", "emit_source_progress"),
    "_etf_type_from_tdx_code": _tdx("security_codes", "etf_type_from_tdx_code"),
    "_finance_market_id": _tdx("finance_normalize", "finance_market_id"),
    "_finance_path_value": _tdx("finance_normalize", "finance_path_value"),
    "_finance_profile_maps_for_record": _tdx("finance_normalize", "finance_profile_maps_for_record"),
    "_finance_records": _tdx("finance_normalize", "finance_records"),
    "_format_datetime": _tdx("normalize_utils", "format_datetime"),
    "_format_time": _tdx("normalize_utils", "format_time"),
    "_format_time_seconds": _tdx("normalize_utils", "format_time_seconds"),
    "_get": _tdx("normalize_utils", "get_value"),
    "_index_kline_period": _tdx("request_params", "index_kline_period"),
    "_index_type_from_tdx_code": _tdx("security_codes", "index_type_from_tdx_code"),
    "_intraday_subchart_minute_time": _tdx("normalize_utils", "intraday_subchart_minute_time"),
    "_is_all_codes_value": _tdx("request_filters", "is_all_codes_value"),
    "_kline_page_size": _tdx("request_params", "kline_page_size"),
    "_kline_period": _tdx("request_params", "kline_period"),
    "_kline_bars": _tdx("time_series_normalize", "kline_bars"),
    "_kline_rows_and_meta": _tdx("kline_helpers", "kline_rows_and_meta"),
    "_kline_row_sort_key": _tdx("time_series_normalize", "kline_row_sort_key"),
    "_limit_board_text": _tdx("normalize_utils", "limit_board_text"),
    "_limit_ladder_candidate": _tdx("derived_rows", "limit_ladder_candidate"),
    "_limit_ladder_count_param": _tdx("derived_rows", "limit_ladder_count_param"),
    "_limit_ladder_level": _tdx("derived_rows", "limit_ladder_level"),
    "_limit_ladder_needs_name_lookup": _tdx("derived_rows", "limit_ladder_needs_name_lookup"),
    "_limit_ladder_public_row": _tdx("derived_rows", "limit_ladder_public_row"),
    "_limit_ladder_rank_page_below_threshold": _tdx("derived_rows", "limit_ladder_rank_page_below_threshold"),
    "_limit_ladder_status": _tdx("price_limits", "limit_ladder_status"),
    "_limit_ladder_stock_summary_text": _tdx("limit_ladder_topics", "limit_ladder_stock_summary_text"),
    "_limit_ladder_theme_is_noise": _tdx("limit_ladder_topics", "limit_ladder_theme_is_noise"),
    "_limit_ladder_theme_rank_rows": _tdx("limit_ladder_topics", "limit_ladder_theme_rank_rows"),
    "_limit_ladder_theme_stats": _tdx("limit_ladder_topics", "limit_ladder_theme_stats"),
    "_limit_ladder_theme_strength_score": _tdx("limit_ladder_topics", "limit_ladder_theme_strength_score"),
    "_limit_ladder_topic_type": _tdx("derived_rows", "limit_ladder_topic_type"),
    "_limit_ladder_trade_date": _tdx("derived_rows", "limit_ladder_trade_date"),
    "_limit_ladder_year_limit_up_days": _tdx("derived_rows", "limit_ladder_year_limit_up_days"),
    "_locked_amount": _tdx("normalize_utils", "locked_amount"),
    "_lookup_limit_ladder_topics": _tdx("limit_ladder_fetch", "lookup_limit_ladder_topics"),
    "_market_value": _tdx("normalize_utils", "market_value"),
    "_name_matches": _tdx("request_filters", "name_matches"),
    "_normalize_adj_factor_anchor_date": _tdx("request_params", "normalize_adj_factor_anchor_date"),
    "_normalize_adj_factor_row": _tdx("derived_rows", "normalize_adj_factor_row"),
    "_normalize_auction_indicator_row": _tdx("derived_rows", "normalize_auction_indicator_row"),
    "_normalize_capital_change_row": _tdx("finance_normalize", "normalize_capital_change_row"),
    "_normalize_daily_price_limit_from_pre_close": _tdx(
        "derived_rows",
        "normalize_daily_price_limit_from_pre_close",
    ),
    "_normalize_daily_price_limit_row": _tdx("derived_rows", "normalize_daily_price_limit_row"),
    "_normalize_daily_price_limit_snapshot_row": _tdx(
        "derived_rows",
        "normalize_daily_price_limit_snapshot_row",
    ),
    "_normalize_daily_share_row": _tdx("derived_rows", "normalize_daily_share_row"),
    "_normalize_index_code_row": _tdx("security_codes", "normalize_index_code_row"),
    "_normalize_index_kline_row": _tdx("time_series_normalize", "normalize_index_kline_row"),
    "_normalize_index_snapshot_row": _tdx("snapshot_normalize", "normalize_index_snapshot_row"),
    "_normalize_limit_ladder_row": _tdx("derived_rows", "normalize_limit_ladder_row"),
    "_normalize_optional_date_text": _tdx("request_params", "normalize_optional_date_text"),
    "_normalize_realtime_snapshot_row": _tdx("snapshot_normalize", "normalize_realtime_snapshot_row"),
    "_normalize_stock_kline_row": _tdx("time_series_normalize", "normalize_stock_kline_row"),
    "_numeric_at_or_above": _tdx("derived_rows", "numeric_at_or_above"),
    "_open_volume_ratio": _tdx("normalize_utils", "open_volume_ratio"),
    "_optional_int": _tdx("normalize_utils", "optional_int"),
    "_optional_int_diff": _tdx("normalize_utils", "optional_int_diff"),
    "_percent_change": _tdx("normalize_utils", "percent_change"),
    "_positive_number": _tdx("price_limits", "positive_number"),
    "_positive_option_int": _tdx("options", "positive_option_int"),
    "_price_at_or_above": _tdx("price_limits", "price_at_or_above"),
    "_price_close": _tdx("price_limits", "price_close"),
    "_price_from_raw": _tdx("time_series_normalize", "price_from_raw"),
    "_price_limit_name_flag": _tdx("price_limits", "price_limit_name_flag"),
    "_price_limit_ratio": _tdx("price_limits", "price_limit_ratio"),
    "_price_limit_ratio_from_rule": _tdx("price_limits", "price_limit_ratio_from_rule"),
    "_price_limit_rule": _tdx("price_limits", "price_limit_rule"),
    "_quote_level_at": _tdx("snapshot_normalize", "quote_level_at"),
    "_quote_security": _tdx("quote_identity", "quote_security"),
    "_quote_security_from_tdx_code": _tdx("quote_identity", "quote_security_from_tdx_code"),
    "_quote_tdx_code": _tdx("snapshot_normalize", "quote_tdx_code"),
    "_rank_sort_param": _tdx("rank_params", "rank_sort_param"),
    "_requested_capital_change_categories": _tdx("finance_normalize", "requested_capital_change_categories"),
    "_requested_codes": _tdx("request_filters", "requested_codes"),
    "_requested_boards": _tdx("request_filters", "requested_boards"),
    "_requested_exchanges": _tdx("request_filters", "requested_exchanges"),
    "_requested_f10_codes": _tdx("request_filters", "requested_f10_codes"),
    "_requested_kline_codes": _tdx("request_filters", "requested_kline_codes"),
    "_requested_names": _tdx("request_filters", "requested_names"),
    "_rescale_price": _tdx("snapshot_normalize", "rescale_price"),
    "_round_optional_float": _tdx("normalize_utils", "round_optional_float"),
    "_round_price": _tdx("price_limits", "round_price"),
    "_rule_price_limits": _tdx("price_limits", "rule_price_limits"),
    "_safe_ratio": _tdx("normalize_utils", "safe_ratio"),
    "_safe_ratio_pct": _tdx("normalize_utils", "safe_ratio_pct"),
    "_scope_meta_value": _tdx("request_filters", "scope_meta_value"),
    "_special_limit_ratio": _tdx("price_limits", "special_limit_ratio"),
    "_stats_date_is_today": _tdx("derived_rows", "stats_date_is_today"),
    "_st_type_from_name": _tdx("price_limits", "st_type_from_name"),
    "_string_values": _tdx("request_filters", "string_values"),
    "_tdx_adjustment_factor_meta": _tdx("adjustment_fetch", "adjustment_factor_meta"),
    "_tdx_adjustment_factor_request_result": _tdx("adjustment_fetch", "adjustment_factor_request_result"),
    "_tdx_adjustment_factor_rows": _tdx("adjustment_fetch", "adjustment_factor_rows"),
    "_tdx_apply_asset_type_meta": _tdx("execution_utils", "apply_asset_type_meta"),
    "_as_list": _tdx("normalize_utils", "as_list"),
    "_tdx_auction_indicator_meta": _tdx("auction_fetch", "auction_indicator_meta"),
    "_tdx_auction_indicator_request_result": _tdx("auction_fetch", "auction_indicator_request_result"),
    "_tdx_auction_indicator_rows": _tdx("auction_fetch", "auction_indicator_rows"),
    "_tdx_capital_change_meta": _tdx("finance_fetch", "capital_change_meta"),
    "_tdx_capital_change_request_result": _tdx("finance_fetch", "capital_change_request_result"),
    "_tdx_capital_change_result": _tdx("finance_fetch", "capital_change_result"),
    "_tdx_capital_changes": _tdx("wire_requests", "tdx_capital_changes"),
    "_tdx_category_quotes": _tdx("wire_requests", "tdx_category_quotes"),
    "_tdx_client_meta": _tdx("execution_utils", "tdx_client_meta"),
    "_tdx_daily_price_limit_meta": _tdx("price_limit_fetch", "daily_price_limit_meta"),
    "_tdx_daily_price_limit_request_result": _tdx("price_limit_fetch", "daily_price_limit_request_result"),
    "_tdx_daily_price_limit_result": _tdx("price_limit_fetch", "daily_price_limit_result"),
    "_tdx_daily_share_meta": _tdx("finance_fetch", "daily_share_meta"),
    "_tdx_daily_share_request_result": _tdx("finance_fetch", "daily_share_request_result"),
    "_tdx_daily_share_rows": _tdx("finance_fetch", "daily_share_rows"),
    "_tdx_default_stock_f10_request_result": _tdx("f10_executor", "default_stock_f10_request_result"),
    "_tdx_explicit_quotes": _tdx("wire_requests", "tdx_explicit_quotes"),
    "_tdx_finance_info": _tdx("wire_requests", "tdx_finance_info"),
    "_tdx_finance_info_request_result": _tdx("finance_fetch", "finance_info_request_result"),
    "_tdx_finance_info_result": _tdx("finance_fetch", "finance_info_result"),
    "_tdx_finish_request_result": _tdx("execution_utils", "finish_request_result"),
    "_tdx_historical_trades": _tdx("wire_requests", "tdx_historical_trades"),
    "_tdx_kline": _tdx("wire_requests", "tdx_kline"),
    "_tdx_legacy_quotes": _tdx("wire_requests", "tdx_legacy_quotes"),
    "_tdx_limit_ladder_meta": _tdx("limit_ladder_fetch", "limit_ladder_meta"),
    "_tdx_limit_ladder_request_result": _tdx("limit_ladder_fetch", "limit_ladder_request_result"),
    "_tdx_refresh_quotes": _tdx("wire_requests", "tdx_refresh_quotes"),
    "_tdx_request_option_connections_per_server": _tdx("options", "tdx_request_option_connections_per_server"),
    "_tdx_request_option_f10_topic_refill_rounds": _tdx("options", "tdx_request_option_f10_topic_refill_rounds"),
    "_tdx_request_option_f10_topic_refill_workers": _tdx("options", "tdx_request_option_f10_topic_refill_workers"),
    "_tdx_request_option_f10_workers": _tdx("options", "tdx_request_option_f10_workers"),
    "_tdx_request_option_hosts": _tdx("options", "tdx_request_option_hosts"),
    "_tdx_request_option_pool_size": _tdx("options", "tdx_request_option_pool_size"),
    "_tdx_request_topic_worker_count": _tdx("options", "tdx_request_topic_worker_count"),
    "_tdx_request_client_should_parallelize_stock_code_request": _tdx(
        "request_client",
        "should_parallelize_stock_code_request",
    ),
    "_tdx_request_client_stock_code_request_pool_size": _tdx(
        "request_client",
        "stock_code_request_pool_size",
    ),
    "_tdx_should_parallelize_stock_code_request": _tdx("code_fetch", "should_parallelize_stock_code_request"),
    "_tdx_stats_resource_params": _tdx("options", "stats_resource_params"),
    "_tdx_stock_code_request_pool_size": _tdx("code_fetch", "stock_code_request_pool_size"),
    "_tdx_stock_code_pool_from_params": _tdx("code_fetch", "stock_code_pool_from_params"),
    "_tdx_theme_strength_meta": _tdx("limit_ladder_fetch", "theme_strength_meta"),
    "_tdx_theme_strength_request_result": _tdx("limit_ladder_fetch", "theme_strength_request_result"),
    "_tdx_today_trades": _tdx("wire_requests", "tdx_today_trades"),
    "_request_kline_code_history": _tdx("request_methods", "_request_kline_code_history"),
    "_request_kline_codes_on_host": _tdx("request_methods", "_request_kline_codes_on_host"),
    "_request_kline_codes_parallel": _tdx("request_methods", "_request_kline_codes_parallel"),
    "_request_kline_series_history": _tdx("request_methods", "_request_kline_series_history"),
    "_request_limit_ladder_rank_rows": _tdx("request_methods", "_request_limit_ladder_rank_rows"),
    "_request_recent_daily_bars": _tdx("request_methods", "_request_recent_daily_bars"),
    "_request_trade_series_history": _tdx("request_methods", "_request_trade_series_history"),
    "_should_parallelize_stock_code_request": _tdx(
        "request_adapter_runtime",
        "should_parallelize_tdx_stock_code_request",
    ),
    "_stock_code_request_pool_size": _tdx(
        "request_adapter_runtime",
        "tdx_stock_code_request_pool_size",
    ),
    "_kline_meta": _tdx("request_methods", "kline_meta"),
    "_latest_daily_price_limit_calendar_dates": _tdx(
        "request_methods",
        "_latest_daily_price_limit_calendar_dates",
    ),
    "_capital_change_rows_by_tdx_code": _tdx("request_methods", "_capital_change_rows_by_tdx_code"),
    "_explicit_snapshot_rows_by_tdx_code": _tdx("request_methods", "_explicit_snapshot_rows_by_tdx_code"),
    "_finance_rows_by_tdx_code": _tdx("request_methods", "_finance_rows_by_tdx_code"),
    "_normalize_finance_info_row": _tdx("request_methods", "_normalize_finance_info_row"),
    "_price_limit_base_from_daily_kline": _tdx(
        "request_methods",
        "_price_limit_base_from_daily_kline",
    ),
    "_price_limit_bases_by_tdx_code": _tdx("request_methods", "_price_limit_bases_by_tdx_code"),
    "_request_legacy_quote_batches": _tdx("request_methods", "_request_legacy_quote_batches"),
    "_request_legacy_quote_batches_concurrent": _tdx(
        "request_methods",
        "_request_legacy_quote_batches_concurrent",
    ),
    "_request_legacy_quotes_on_host": _tdx("request_methods", "_request_legacy_quotes_on_host"),
    "_request_legacy_quotes_parallel": _tdx("request_methods", "_request_legacy_quotes_parallel"),
    "_suspension_scan_hosts": _tdx("request_host_config", "_suspension_scan_hosts"),
    "_env_hosts": _tdx("request_host_config", "_env_hosts"),
    "_configured_tdx_hosts": _tdx("request_host_config", "_configured_tdx_hosts"),
    "_configured_tdx_hosts_from_options": _tdx("request_host_config", "_configured_tdx_hosts_from_options"),
    "effective_host_strings": _tdx("request_host_config", "effective_host_strings"),
    "_security_names_by_tdx_code": _tdx("request_methods", "_security_names_by_tdx_code"),
    "_tenk_shares_to_lots": _tdx("normalize_utils", "tenk_shares_to_lots"),
    "_tenk_to_unit": _tdx("normalize_utils", "tenk_to_unit"),
    "_tenk_yuan": _tdx("normalize_utils", "tenk_yuan"),
    "_tdx_codes": _tdx("snapshot_normalize", "tdx_codes"),
    "_tdx_codes_all": _tdx("snapshot_normalize", "tdx_codes_all"),
    "_today_limit_board_window": _tdx("derived_rows", "today_limit_board_window"),
    "_topic_missing_stock_count": _tdx("limit_ladder_topics", "topic_missing_stock_count"),
    "_trade_date_param": _tdx("request_params", "trade_date_param"),
    "_validate_kline_anchor_date": _tdx("request_params", "validate_kline_anchor_date"),
    "_volume_change": _tdx("normalize_utils", "volume_change"),
    "_volume_change_pct": _tdx("normalize_utils", "volume_change_pct"),
    "_volume_ratio_vs_previous_day": _tdx("normalize_utils", "volume_ratio_vs_previous_day"),
    "_KlineHostResult": _tdx("series_history", "KlineHostResult"),
    "_KlineParallelResult": _tdx("series_history", "KlineParallelResult"),
    "_KlineRequestResult": _tdx("series_history", "KlineRequestResult"),
    "_normalize_kline_row": _tdx("time_series_normalize", "normalize_kline_row"),
    "_normalize_trade_row": _tdx("time_series_normalize", "normalize_trade_row"),
    "_price_decimal": _tdx("snapshot_normalize", "price_decimal"),
    "_trade_records": _tdx("time_series_normalize", "trade_records"),
    "_exchanges_for_boards": _tdx("request_filters", "exchanges_for_boards"),
    "_has_tdx_connection_options": _tdx("options", "has_tdx_connection_options"),
    "_int_param": _tdx("request_params", "int_param"),
    "_normalize_tdx_request_options": _tdx("options", "normalize_tdx_request_options"),
}

_F10_REQUEST_COMPAT_EXPORTS: dict[str, str] = {
    "_attach_event_driver_details": "attach_event_driver_details",
    "_f10_business_composition_periods": "f10_business_composition_periods",
    "_tdx_f10_interface_specs": "f10_interface_specs",
    "_f10_private_placement_dates": "f10_private_placement_dates",
    "_latest_f10_guarantee_period": "latest_f10_guarantee_period",
    "_normalize_control_ranking_rows": "normalize_control_ranking_rows",
    "_normalize_institution_holding_rows": "normalize_institution_holding_rows",
    "_prepare_f10_params": "prepare_f10_params",
    "_request_analyst_rating_rows": "request_analyst_rating_rows",
    "_request_event_driver_detail": "request_event_driver_detail",
    "_request_f10_all_pages": "request_f10_all_pages",
    "_f10_interface_specs": "f10_interface_specs",
    "request_f10_interface": "request_f10_interface",
    "_request_f10_interface_once": "request_f10_interface_once",
    "_request_f10_tables": "request_f10_tables",
}

_F10_NORMALIZE_COMPAT_EXPORTS: dict[str, str] = {
    "_date_dash": "date_dash",
    "_f10_date_text": "f10_date_text",
    "_f10_field_value": "f10_field_value",
    "_f10_first_text": "f10_first_text",
    "_f10_first_value": "f10_first_value",
    "_f10_identifier_text": "f10_identifier_text",
    "_f10_market_from_market_code": "f10_market_from_market_code",
    "_f10_number": "f10_number",
    "_f10_page": "f10_page",
    "_f10_rating_code": "f10_rating_code",
    "_is_empty_f10_value": "is_empty_f10_value",
    "_normalize_f10_plain_text": "normalize_f10_plain_text",
    "_scale_f10_hundred": "scale_f10_hundred",
}

_F10_POSTPROCESS_COMPAT_EXPORTS: dict[str, str] = {
    "_convertible_bond_status": "convertible_bond_status",
    "_equity_financing_event_type": "equity_financing_event_type",
    "_equity_rights_issue_plan": "equity_rights_issue_plan",
    "_filter_date_range": "filter_date_range",
    "_filter_f10_rows": "filter_f10_rows",
    "_filter_shareholder_change_direction": "filter_shareholder_change_direction",
    "_normalize_dividend_metrics_row": "normalize_dividend_metrics_row",
    "_normalize_dividend_metrics_summary_rows": "normalize_dividend_metrics_summary_rows",
    "_normalize_equity_financing_row": "normalize_equity_financing_row",
    "_normalize_equity_financing_rows": "normalize_equity_financing_rows",
    "_normalize_f10_row": "normalize_f10_row",
    "_normalize_f10_row_for_summary": "normalize_f10_row_for_summary",
    "_normalize_northbound_holding_row": "normalize_northbound_holding_row",
    "_normalize_private_placement_allocation_row": "normalize_private_placement_allocation_row",
    "_northbound_record_channel_type": "northbound_record_channel_type",
    "_postprocess_concept_constituent_row": "postprocess_concept_constituent_row",
    "_postprocess_f10_rows": "postprocess_f10_rows",
    "_postprocess_market_ranking_row": "postprocess_market_ranking_row",
    "_topic_exposure_type": "topic_exposure_type",
    "_valuation_metric_name": "valuation_metric_name",
    "_year_in_range": "year_in_range",
}

_F10_RENDER_COMPAT_EXPORTS: dict[str, str] = {
    "_render_f10_body": "render_f10_body",
}

_F10_PARAMS_COMPAT_EXPORTS: dict[str, str] = {
    "_analyst_target_stats": "analyst_target_stats",
    "_control_ranking_item": "control_ranking_item",
    "_f10_business_period_candidates": "f10_business_period_candidates",
    "_f10_business_period_value": "f10_business_period_value",
    "_f10_context": "f10_context",
    "_f10_dividend_metrics_function": "f10_dividend_metrics_function",
    "_f10_function": "f10_function",
    "_f10_unfiltered_page_params": "f10_unfiltered_page_params",
}

_PRICE_LIMIT_COMPAT_EXPORTS: dict[str, tuple[str, str]] = {
    "_PriceLimitCalendarDates": (
        "axdata_source_tdx.price_limit_calendar",
        "PriceLimitCalendarDates",
    ),
    "_PriceLimitBase": (
        "axdata_source_tdx.price_limit_history",
        "PriceLimitBase",
    ),
    "_PriceLimitRequestResult": (
        "axdata_source_tdx.price_limit_history",
        "PriceLimitRequestResult",
    ),
}


def resolve_request_compat_export(name: str, module_globals: dict[str, Any], module_name: str) -> Any:
    request_module_export = _REQUEST_MODULE_COMPAT_EXPORTS.get(name)
    if request_module_export is not None:
        module = import_module(request_module_export[0])
        value = getattr(module, request_module_export[1])
        module_globals[name] = value
        return value

    target_name = _F10_REQUEST_COMPAT_EXPORTS.get(name)
    target_module = "axdata_source_tdx.f10_request"
    if target_name is None:
        target_name = _F10_NORMALIZE_COMPAT_EXPORTS.get(name)
        target_module = "axdata_source_tdx.f10_normalize"
    if target_name is None:
        target_name = _F10_POSTPROCESS_COMPAT_EXPORTS.get(name)
        target_module = "axdata_source_tdx.f10_postprocess"
    if target_name is None:
        target_name = _F10_RENDER_COMPAT_EXPORTS.get(name)
        target_module = "axdata_source_tdx.f10_render"
    if target_name is None:
        target_name = _F10_PARAMS_COMPAT_EXPORTS.get(name)
        target_module = "axdata_source_tdx.f10_params"
    if target_name is None:
        price_limit_export = _PRICE_LIMIT_COMPAT_EXPORTS.get(name)
        if price_limit_export is not None:
            module = import_module(price_limit_export[0])
            value = getattr(module, price_limit_export[1])
            module_globals[name] = value
            return value
        raise AttributeError(f"module {module_name!r} has no attribute {name!r}")
    module = import_module(target_module)
    value = getattr(module, target_name)
    module_globals[name] = value
    return value
