"""TDX request pagination, status bit, and default concurrency constants."""

DEFAULT_QUOTE_BATCH_SIZE = 80
TDX_CODE_PAGE_SIZE = 1600
TDX_SUSPENSION_HOST_COUNT = 4
TDX_SUSPENSION_POOL_SIZE = 2
TDX_SUSPENSION_STATUS_BIT = 0x20
TDX_KLINE_HOST_COUNT = 2
TDX_KLINE_POOL_SIZE = 4
TDX_TRADE_PAGE_SIZE = 1800
TDX_TRADE_MAX_START = 65535
TDX_RANK_DEFAULT_COUNT = 80
TDX_RANK_MAX_COUNT = 1000
TDX_RANK_MAX_START = 65535
TDX_LIMIT_LADDER_SCAN_PAGE_SIZE = 80
