"""Lightweight TDX F10 catalog projection.

This module intentionally contains only display-facing F10 metadata. The
protocol execution specs live in ``tdx_f10_specs`` and are imported only when a
real 7615 request is executed.
"""

from __future__ import annotations

from .tdx_f10_models import F10FieldSpec, F10InterfaceSpec, F10ParamSpec


def _field(name: str, dtype: str, description_zh: str, example: object = None) -> F10FieldSpec:
    return F10FieldSpec(name=name, dtype=dtype, description_zh=description_zh, example=example)


def _param(
    name: str,
    dtype: str,
    description_zh: str,
    *,
    required: bool = False,
    default: object = None,
) -> F10ParamSpec:
    return F10ParamSpec(
        name=name,
        dtype=dtype,
        required=required,
        description_zh=description_zh,
        default=default,
    )


F10_CATALOG_SPECS: dict[str, F10InterfaceSpec] = {
    'stock_ipo_listing_profile_tdx': F10InterfaceSpec(
        name='stock_ipo_listing_profile_tdx',
        display_name_zh='发行上市资料',
        category='F10数据',
        summary_zh='查询公司发行上市资料。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('stock_type', 'string', '股票类别。', 'A股'),
            _field('list_date', 'date/string', '上市日期。', '19940509'),
            _field('issue_method', 'string', '发行方式。', '申请表抽签限额认购'),
            _field('issue_system', 'string', '发行制度。', '核准制'),
            _field('par_value', 'number', '每股面值，单位：元。', 1.0),
            _field('issue_price', 'number', '发行价格，单位：元。', 5.2),
            _field('issue_volume', 'number', '发行数量。', 4680),
            _field('raised_amount', 'number', '实际募资总额。', 24336),
            _field('net_raised_amount', 'number', '实际募资净额。', 23390.2),
            _field('first_open', 'number', '首日开盘价，单位：元。', 7.2),
            _field('first_close', 'number', '首日收盘价，单位：元。', 6.76),
            _field('lead_underwriter', 'string', '主承销商。', '巨田证券有限责任公司'),
            _field('sponsor', 'string', '上市保荐人。', '巨田证券有限责任公司'),
        ),
    ),
    'stock_index_constituent_changes_tdx': F10InterfaceSpec(
        name='stock_index_constituent_changes_tdx',
        display_name_zh='指数调入调出',
        category='F10数据',
        summary_zh='查询股票被指数调入或调出的历史记录。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选；不传返回全部记录。'),
            _param('end_date', 'string', '结束日期，可选；不传返回全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('publish_date', 'date/string', '指数调整公布日期。', '20241129'),
            _field('change_direction', 'string', '指数调入/调出方向。', '调入'),
            _field('index_name', 'string', '指数名称。', '中证500'),
            _field('publish_date_change_pct', 'number', '公布日涨跌幅，单位：%。', 1.9496101),
            _field('effective_date', 'date/string', '指数调整日期。', '20241216'),
            _field('effective_date_change_pct', 'number', '调整日涨跌幅，单位：%。', -1.9343494),
        ),
    ),
    'stock_company_profile_tdx': F10InterfaceSpec(
        name='stock_company_profile_tdx',
        display_name_zh='公司概况',
        category='F10数据',
        summary_zh='查询公司发行上市资料和指数调入调出记录。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('type', 'string', '资料类型：listing 发行上市信息，index_change 指数调入调出；默认 listing。', default='listing'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('stock_type', 'string', '股票类别。', 'A股'),
            _field('list_date', 'date/string', '上市日期。', '19940509'),
            _field('issue_method', 'string', '发行方式。', '申请表抽签限额认购'),
            _field('issue_system', 'string', '发行制度。', '核准制'),
            _field('par_value', 'number', '每股面值，单位：元。', 1.0),
            _field('issue_price', 'number', '发行价格，单位：元。', 5.2),
            _field('issue_volume', 'number', '发行数量。', 4680),
            _field('raised_amount', 'number', '实际募资总额。', 24336),
            _field('net_raised_amount', 'number', '实际募资净额。', 23390.2),
            _field('first_open', 'number', '首日开盘价，单位：元。', 7.2),
            _field('first_close', 'number', '首日收盘价，单位：元。', 6.76),
            _field('lead_underwriter', 'string', '主承销商。', '巨田证券有限责任公司'),
            _field('sponsor', 'string', '上市保荐人。', '巨田证券有限责任公司'),
            _field('publish_date', 'date/string', '指数调整公布日期。'),
            _field('change_direction', 'string', '指数调入/调出方向。'),
            _field('index_name', 'string', '指数名称。'),
            _field('publish_date_change_pct', 'number', '公布日涨跌幅，单位：%。'),
            _field('effective_date', 'date/string', '指数调整日期。'),
            _field('effective_date_change_pct', 'number', '调整日涨跌幅，单位：%。'),
        ),
    ),
    'stock_business_composition_tdx': F10InterfaceSpec(
        name='stock_business_composition_tdx',
        display_name_zh='主营构成',
        category='F10数据',
        summary_zh='查询各报告期主营收入、成本、毛利和毛利率。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('period', 'string', '报告期，格式 YYYYMMDD；不传时返回全部可用报告期。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('report_period', 'date/string', '报告期。', '20251231'),
            _field('dimension', 'string', '分类方式。', '按产品'),
            _field('item_order', 'integer', '序号或层级。', 1),
            _field('item_name', 'string', '主营构成项目。', '数字化产品'),
            _field('revenue', 'number', '主营收入。', 123456.78),
            _field('revenue_ratio_pct', 'number', '收入占比，单位：%。', 62.3),
            _field('cost', 'number', '主营成本。', 80000.0),
            _field('cost_ratio_pct', 'number', '成本占比，单位：%。', 58.2),
            _field('gross_profit', 'number', '毛利。', 43456.78),
            _field('profit_ratio_pct', 'number', '利润占比，单位：%。', 66.1),
            _field('gross_margin_pct', 'number', '毛利率，单位：%。', 35.2),
        ),
    ),
    'stock_financial_statement_tdx': F10InterfaceSpec(
        name='stock_financial_statement_tdx',
        display_name_zh='资产负债表',
        category='F10数据',
        summary_zh='查询资产负债表。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('report_period', 'date/string', '报告期。', '20251231'),
            _field('cash', 'number', '货币资金。'),
            _field('trading_financial_assets', 'number', '交易性金融资产。'),
            _field('notes_receivable', 'number', '应收票据。'),
            _field('accounts_receivable', 'number', '应收账款。'),
            _field('current_assets', 'number', '流动资产合计。'),
            _field('total_assets', 'number', '资产总计。'),
            _field('short_term_borrowing', 'number', '短期借款。'),
            _field('notes_payable', 'number', '应付票据。'),
            _field('accounts_payable', 'number', '应付账款。'),
            _field('current_liabilities', 'number', '流动负债合计。'),
            _field('total_liabilities', 'number', '负债合计。'),
            _field('share_capital', 'number', '实收资本或股本。'),
            _field('capital_reserve', 'number', '资本公积金。'),
            _field('undistributed_profit', 'number', '未分配利润。'),
            _field('parent_equity', 'number', '归母权益合计。'),
            _field('total_equity', 'number', '所有者权益合计。'),
            _field('liabilities_and_equity', 'number', '负债和股东权益合计。'),
        ),
    ),
    'stock_financial_diagnosis_tdx': F10InterfaceSpec(
        name='stock_financial_diagnosis_tdx',
        display_name_zh='财务诊断',
        category='F10数据',
        summary_zh='查询源端财务能力、预警和评分。该接口为源端评价，不代表 AxData 自有判断。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('dimension', 'string', '诊断维度：operation 营运能力、profit 盈利能力、growth 成长能力、cashflow 现金流、asset_quality 资产质量、z_score Z值预警、score 综合评分；默认 score。', default='score'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('stock_name', 'string', '股票简称。'),
            _field('compare_group', 'string', '对比行业或板块。'),
            _field('report_period', 'date/string', '报告期。'),
            _field('rank', 'integer', '个股排名。'),
            _field('rank_change', 'number', '排名或评分变化。'),
            _field('rating_code', 'string', '评价等级码。'),
            _field('score', 'number', '源端综合评分。'),
            _field('percentile', 'number', '分位或打败比例。'),
            _field('warning_value', 'number', 'Z 值或预警值。'),
        ),
        evaluation=True,
    ),
    'stock_forecast_consensus_tdx': F10InterfaceSpec(
        name='stock_forecast_consensus_tdx',
        display_name_zh='盈利预测',
        category='F10数据',
        summary_zh='查询盈利预测统计，包括未来三年预测、历史实际值和预测机构数量。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('forecast_start_year', 'integer', '预测起始年份。'),
            _field('align_flag', 'string', '年份对齐标记。'),
            _field('eps_year1', 'number', '未来第一年预测每股收益。'),
            _field('eps_year2', 'number', '未来第二年预测每股收益。'),
            _field('eps_year3', 'number', '未来第三年预测每股收益。'),
            _field('net_profit_year1', 'number', '未来第一年预测归母净利润。'),
            _field('net_profit_year2', 'number', '未来第二年预测归母净利润。'),
            _field('net_profit_year3', 'number', '未来第三年预测归母净利润。'),
            _field('revenue_year1', 'number', '未来第一年预测营业收入。'),
            _field('revenue_year2', 'number', '未来第二年预测营业收入。'),
            _field('revenue_year3', 'number', '未来第三年预测营业收入。'),
            _field('forecast_institution_count', 'integer', '预测机构数量。'),
        ),
    ),
    'stock_dividend_history_tdx': F10InterfaceSpec(
        name='stock_dividend_history_tdx',
        display_name_zh='分红历史',
        category='F10数据',
        summary_zh='查询历史分红方案、登记日、除权日和方案进度。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_year', 'string', '起始年份，可选；不传返回全部记录。'),
            _param('end_year', 'string', '结束年份，可选；不传返回全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('report_period', 'date/string', '分红年度或报告期。'),
            _field('board_date', 'date/string', '董事会日期。'),
            _field('plan', 'string', '分红方案。'),
            _field('eps', 'number', '每股收益。'),
            _field('roe_weighted_pct', 'number', '加权净资产收益率，单位：%。'),
            _field('record_date', 'date/string', '股权登记日。'),
            _field('ex_dividend_date', 'date/string', '除权派息日。'),
            _field('progress', 'string', '方案进度。'),
            _field('progress_code', 'string', '方案进度码。'),
            _field('payout_ratio_pct', 'number', '股利支付率，单位：%。'),
            _field('target_holder', 'string', '派发对象。'),
        ),
    ),
    'stock_dividend_metrics_tdx': F10InterfaceSpec(
        name='stock_dividend_metrics_tdx',
        display_name_zh='分红指标',
        category='F10数据',
        summary_zh='查询股息率、股利支付率、派现融资等分红指标。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('metric', 'string', '指标：dividend_yield 股息率、payout_ratio 股利支付率、cash_financing 派现融资；默认 dividend_yield。', default='dividend_yield'),
            _param('view', 'string', '展示方式：trend 走势、ranking 排名、summary 总览；不传时 dividend_yield/payout_ratio 默认 trend，cash_financing 默认 summary。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '日期或期间。'),
            _field('metric_value', 'number', '指标值。'),
            _field('benchmark_value', 'number', '对照值。'),
            _field('rank', 'integer', '排名。'),
            _field('stock_name', 'string', '证券简称。'),
            _field('stock_code', 'string', '股票代码。'),
            _field('summary_total', 'number', '汇总总额。'),
            _field('cash_dividend_total', 'number', '累计现金分红。'),
        ),
    ),
    'stock_equity_financing_events_tdx': F10InterfaceSpec(
        name='stock_equity_financing_events_tdx',
        display_name_zh='融资事件',
        category='F10数据',
        summary_zh='查询增发、配股、股权激励、可转债等融资相关事件。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('event_type', 'string', '事件类型：placement 增发、rights_issue 配股、incentive 股权激励、convertible_bond 可转债；默认 placement。', default='placement'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('event_date', 'date/string', '事件日期。'),
            _field('event_type', 'string', '事件类型。'),
            _field('plan', 'string', '方案或关键条款。'),
            _field('amount', 'number', '融资金额。'),
            _field('price', 'number', '发行、配股、授予或转股价格。'),
            _field('volume', 'number', '发行、配股、授予或债券规模。'),
            _field('progress', 'string', '进度。'),
        ),
    ),
    'stock_private_placement_allocations_tdx': F10InterfaceSpec(
        name='stock_private_placement_allocations_tdx',
        display_name_zh='增发获配明细',
        category='F10数据',
        summary_zh='查询增发获配机构、获配数量和获配金额。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('event_date', 'string', '增发日期，格式 YYYYMMDD 或 YYYY-MM-DD；不传返回全部可用增发日期的获配明细。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('event_date', 'date/string', '增发日期。'),
            _field('allocator', 'string', '获配机构。'),
            _field('allocated_volume', 'number', '获配数量，单位：股。'),
            _field('subscribed_volume', 'number', '申购数量，单位：股。'),
            _field('allocated_amount', 'number', '获配金额，单位：元。'),
            _field('lock_months', 'number', '锁定期，单位：月。'),
            _field('institution_type', 'string', '机构类型。'),
            _field('unlock_date', 'date/string', '解禁日期。'),
            _field('shareholder_id', 'string', '股东 ID。'),
        ),
    ),
    'stock_shareholder_change_plans_tdx': F10InterfaceSpec(
        name='stock_shareholder_change_plans_tdx',
        display_name_zh='股东增减持',
        category='F10数据',
        summary_zh='查询股东增持或减持计划。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('direction', 'string', '方向筛选：increase 增持、decrease 减持；不传返回全部方向。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('announcement_date', 'date/string', '最新公告日。'),
            _field('direction', 'string', '变动方向。'),
            _field('shareholder_name', 'string', '股东名称。'),
            _field('shareholder_role', 'string', '股东身份或职务。'),
            _field('planned_volume_upper', 'number', '拟变动数量上限，单位：股。'),
            _field('planned_ratio_upper_pct', 'number', '拟变动上限占总股本比例，单位：%。'),
            _field('planned_amount_upper', 'number', '拟变动资金上限，单位：元；源端未按金额披露时为空。'),
            _field('start_date', 'date/string', '起始变动日期。'),
            _field('end_date', 'date/string', '截止变动日期。'),
            _field('progress', 'string', '进度。'),
            _field('detail_id', 'string', '详情记录 ID。'),
        ),
    ),
    'stock_northbound_holding_tdx': F10InterfaceSpec(
        name='stock_northbound_holding_tdx',
        display_name_zh='沪深股通持股',
        category='F10数据',
        summary_zh='查询沪深股通持股变化序列；不传日期默认返回全部可用记录。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选；不传返回全部记录。'),
            _param('end_date', 'string', '结束日期，可选；不传返回全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('channel_type', 'string', '当前持股记录对应的交易通道；有记录的深市标为深股通，沪市标为沪股通。'),
            _field('date', 'date/string', '指标日期。'),
            _field('holding_ratio_pct', 'number', '持股比例，单位：%。'),
            _field('holding_volume', 'number', '持股数量，单位：股。'),
            _field('change_volume', 'number', '变动股数，单位：股。'),
            _field('change_pct', 'number', '较上期变化，单位：%。'),
            _field('close', 'number', '收盘价，单位：元。'),
        ),
    ),
    'stock_margin_trading_tdx': F10InterfaceSpec(
        name='stock_margin_trading_tdx',
        display_name_zh='融资融券',
        category='F10数据',
        summary_zh='查询源端融资融券统计。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选。'),
            _param('end_date', 'string', '结束日期，可选。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '日期。'),
            _field('margin_net_buy', 'number', '融资净买入。'),
            _field('margin_balance', 'number', '融资余额。'),
            _field('short_balance', 'number', '融券相关统计。'),
        ),
    ),
    'stock_chip_distribution_tdx': F10InterfaceSpec(
        name='stock_chip_distribution_tdx',
        display_name_zh='筹码分布',
        category='F10数据',
        summary_zh='查询源端筹码分布统计。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '按统计日期过滤的起始日期；不传返回源端本次给出的全部记录。'),
            _param('end_date', 'string', '按统计日期过滤的结束日期；不传返回源端本次给出的全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '统计日期。'),
            _field('profit_ratio_pct', 'number', '获利比例，单位：%。'),
            _field('cost90_concentration', 'number', '90% 成本区间宽窄，数值越小表示筹码成本越集中。'),
            _field('cost90_range', 'string', '覆盖 90% 筹码的估算成本区间。'),
            _field('cost70_concentration', 'number', '70% 成本区间宽窄，数值越小表示核心筹码成本越集中。'),
            _field('cost70_range', 'string', '覆盖 70% 筹码的估算成本区间。'),
        ),
    ),
    'stock_research_reports_tdx': F10InterfaceSpec(
        name='stock_research_reports_tdx',
        display_name_zh='研报列表',
        category='F10数据',
        summary_zh='查询公司研究报告列表。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('rating', 'string', '评级筛选：all、buy、overweight、neutral、underweight、sell；默认 all。', default='all'),
            _param('keyword', 'string', '标题关键字，可选。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
            _param('cursor', 'string', '分页游标；不传从第一页开始。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('rating', 'string', '评级类别。'),
            _field('analyst', 'string', '研究员。'),
            _field('publish_date', 'date/string', '撰写日期。'),
            _field('detail_id', 'string', '研报详情 ID。'),
            _field('title', 'string', '研报标题。'),
            _field('attachment', 'string', '研报附件标识。'),
        ),
    ),
    'stock_analyst_rating_tdx': F10InterfaceSpec(
        name='stock_analyst_rating_tdx',
        display_name_zh='机构评级与目标价',
        category='F10数据',
        summary_zh='查询机构评级家数和目标价统计。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '按评级统计日期过滤的起始日期；不传返回源端本次给出的记录。'),
            _param('end_date', 'string', '按评级统计日期过滤的结束日期；不传返回源端本次给出的记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '评级统计日期。'),
            _field('buy_count', 'integer', '买入家数。'),
            _field('overweight_count', 'integer', '增持家数。'),
            _field('neutral_count', 'integer', '中性家数。'),
            _field('underweight_count', 'integer', '减持家数。'),
            _field('sell_count', 'integer', '卖出家数。'),
            _field('target_price', 'number', '平均目标价。'),
            _field('target_price_low', 'number', '目标价下限。'),
            _field('target_price_high', 'number', '目标价上限。'),
            _field('current_price', 'number', '当前价。'),
            _field('upside_pct', 'number', '上涨空间，单位：%。'),
        ),
    ),
    'stock_institution_holding_tdx': F10InterfaceSpec(
        name='stock_institution_holding_tdx',
        display_name_zh='机构持仓',
        category='F10数据',
        summary_zh='查询机构持仓比例多期趋势。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '按报告日期过滤的起始日期；不传返回源端本次给出的全部记录。'),
            _param('end_date', 'string', '按报告日期过滤的结束日期；不传返回源端本次给出的全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '报告日期。'),
            _field('report_period', 'string', '报告期名称，例如 2026一季报。'),
            _field('institution_holding_ratio_pct', 'number', '机构持仓比例，单位：%。'),
            _field('close', 'number', '当期收盘价，单位：元。'),
        ),
    ),
    'stock_governance_guarantees_tdx': F10InterfaceSpec(
        name='stock_governance_guarantees_tdx',
        display_name_zh='担保明细',
        category='F10数据',
        summary_zh='查询担保方、被担保方、担保金额和担保期限。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('period', 'string', '报告期；不传自动取最新可用报告期。'),
            _param('count', 'integer', '返回条数，默认 20；该接口单期可能有大量明细。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('report_period', 'date/string', '报告期。'),
            _field('guarantor', 'string', '担保方。'),
            _field('guaranteed_party', 'string', '被担保方。'),
            _field('amount', 'number', '担保金额。'),
            _field('currency', 'string', '币种。'),
            _field('guarantee_type', 'string', '担保类型。'),
            _field('is_completed', 'string', '是否履行完毕。'),
            _field('is_related_party', 'string', '是否关联交易。'),
            _field('actual_date', 'date/string', '实际发生日。'),
            _field('term', 'number/string', '担保期限，源端原值，可能为数字或空。'),
        ),
    ),
    'stock_violation_cases_tdx': F10InterfaceSpec(
        name='stock_violation_cases_tdx',
        display_name_zh='违规处理',
        category='F10数据',
        summary_zh='查询违规处理和处罚决定。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '按立案日期过滤的起始日期；不传返回源端本次给出的全部记录。'),
            _param('end_date', 'string', '按立案日期过滤的结束日期；不传返回源端本次给出的全部记录。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('case_date', 'date/string', '立案日期。'),
            _field('case_type', 'string', '立案类型。'),
            _field('publish_date', 'date/string', '处罚公布日期，源端可能为空。'),
            _field('progress', 'string', '案情进展。'),
            _field('detail_id', 'string', '违法事实详情 ID。'),
            _field('decision', 'string', '处罚决定，源端可能为空。'),
        ),
    ),
    'stock_regulatory_actions_tdx': F10InterfaceSpec(
        name='stock_regulatory_actions_tdx',
        display_name_zh='监管措施',
        category='F10数据',
        summary_zh='查询监管措施或处罚函件。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '按处罚公布日期过滤的起始日期；不传返回源端本次给出的全部记录。'),
            _param('end_date', 'string', '按处罚公布日期过滤的结束日期；不传返回源端本次给出的全部记录。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('publish_date', 'date/string', '处罚公布日期。'),
            _field('target', 'string', '处罚对象。'),
            _field('action', 'string', '监管措施。'),
            _field('content', 'string', '函件内容。'),
            _field('link', 'string', '链接，源端可能为空。'),
        ),
    ),
    'stock_score_summary_tdx': F10InterfaceSpec(
        name='stock_score_summary_tdx',
        display_name_zh='综合评分',
        category='F10数据',
        summary_zh='查询源端综合评分、维度评分和排名。该接口为源端评价，不代表 AxData 自有判断。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('score', 'number', '源端综合评分。'),
            _field('industry_rank', 'integer', '行业排名名次。'),
            _field('industry_rank_total', 'integer', '行业排名总数。'),
            _field('market_rank', 'integer', 'A 股市场排名名次。'),
            _field('market_rank_total', 'integer', 'A 股市场排名总数。'),
            _field('market_win_pct', 'number', '打败 A 股百分比。'),
            _field('date', 'date/string', '日期。'),
            _field('capital_score', 'number', '资金面评分。'),
            _field('fundamental_score', 'number', '基本面评分。'),
            _field('news_score', 'number', '消息面评分。'),
            _field('theme_score', 'number', '主题面评分。'),
            _field('industry_name', 'string', '行业名。'),
            _field('stock_name', 'string', '股票名。'),
        ),
        evaluation=True,
    ),
    'stock_disclosure_feed_tdx': F10InterfaceSpec(
        name='stock_disclosure_feed_tdx',
        display_name_zh='新闻公告路演',
        category='F10数据',
        summary_zh='查询个股新闻、公告或路演列表。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('category', 'string', '类型：news 新闻、announcement 公告、roadshow 路演；默认 announcement。', default='announcement'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('category', 'string', '资讯类型。'),
            _field('issue_date', 'datetime/string', '发布时间或公告日期；路演通常为空。'),
            _field('title', 'string', '标题。'),
            _field('source', 'string', '来源；路演通常为空。'),
            _field('detail_table', 'string', '详情来源表。'),
            _field('detail_id', 'string', '记录 ID；路演通常为空。'),
            _field('type_code', 'string', '公告类型码；非公告通常为空。'),
            _field('type_name', 'string', '公告类型名；非公告通常为空。'),
            _field('url', 'string', 'PDF、新闻或活动链接；源端无链接时为空。'),
            _field('summary', 'string', '摘要；源端无摘要时为空。'),
            _field('start_date', 'date/string', '路演开始日期；非路演为空。'),
            _field('start_time', 'time/string', '路演开始时间；非路演为空。'),
            _field('end_time', 'time/string', '路演结束时间；非路演为空。'),
        ),
    ),
    'stock_event_drivers_tdx': F10InterfaceSpec(
        name='stock_event_drivers_tdx',
        display_name_zh='历史事件关联',
        category='F10数据',
        summary_zh='查询个股历史事件关联记录；不是涨停原因库，可选补充详情正文。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选；按事件创建日期过滤。'),
            _param('end_date', 'string', '结束日期，可选；按事件创建日期过滤。'),
            _param('include_detail', 'boolean', '是否补充详情正文，默认 false。', default=False),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('event_date', 'date/string', '事件创建日期。'),
            _field('event_name', 'string', '事件名称，不等同于涨停原因。'),
            _field('detail_id', 'string', '事件详情 ID。'),
            _field('event_nature', 'string', '事件性质。'),
            _field('creation_change_pct', 'number', '创建日涨跌幅，单位：%。'),
            _field('has_detail', 'boolean', '是否有详情正文。'),
            _field('detail_title', 'string', '详情标题；include_detail=true 时补充。'),
            _field('detail_text', 'string', '详情正文；include_detail=true 时补充。'),
        ),
    ),
    'stock_topic_exposure_tdx': F10InterfaceSpec(
        name='stock_topic_exposure_tdx',
        display_name_zh='个股题材',
        category='短线数据',
        summary_zh='查询个股所属题材、关联度和入选原因。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('topic_type', 'string', '题材类型：sector 板块题材、theme 主题题材；默认 theme。', default='theme'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('topic_type', 'string', '题材类型：sector 板块题材、theme 主题题材。'),
            _field('created_date', 'date/string', '创建日期。'),
            _field('topic_name', 'string', '题材名称。'),
            _field('relevance', 'number', '关联度，源端评价分值。'),
            _field('selected_date', 'date/string', '入选或更新日期；源端可能为空。'),
            _field('reason', 'string', '入选原因或栏目内容。'),
            _field('topic_id', 'string', '题材 ID。'),
            _field('group_code', 'string', '源端分组类别码；主题题材可能为空。'),
        ),
    ),
    'concept_related_boards_tdx': F10InterfaceSpec(
        name='concept_related_boards_tdx',
        display_name_zh='相关板块',
        category='短线数据',
        summary_zh='查询个股当前关联板块列表。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('board_market', 'string', '板块市场。'),
            _field('board_code', 'string', '板块代码。'),
            _field('board_name', 'string', '板块名称。'),
            _field('change_pct', 'number', '涨幅，单位：%。'),
            _field('limit_up_count', 'integer', '涨停数。'),
        ),
    ),
    'concept_constituents_tdx': F10InterfaceSpec(
        name='concept_constituents_tdx',
        display_name_zh='板块成分股',
        category='短线数据',
        summary_zh='按板块代码查询当前成分股。',
        entry="",
        body_kind="",
        params=(
            _param('concept_code', 'string', '板块代码；先用相关板块接口按股票代码查询，取返回的 board_code 填入。', required=True),
            _param('count', 'integer', '返回前多少只，默认 20，最大 500。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。', '000001.SZ'),
            _field('symbol', 'string', '交易所原始六位代码。', '000001'),
            _field('exchange', 'string', 'AxData 交易所代码：SSE、SZSE 或 BSE。', 'SZSE'),
            _field('market_code', 'string', '市场代码。', '0'),
            _field('name', 'string', '股票名称。', '平安银行'),
            _field('change_pct', 'number', '涨幅，单位：%。', -0.45),
            _field('last_price', 'number', '现价，单位：元。', 11.01),
        ),
    ),
    'concept_capital_flow_tdx': F10InterfaceSpec(
        name='concept_capital_flow_tdx',
        display_name_zh='题材资金走势',
        category='短线数据',
        summary_zh='查询题材或行业主力资金走势。',
        entry="",
        body_kind="",
        params=(
            _param('concept_code', 'string', '题材或行业 ID；可先从个股题材接口返回的 topic_id 中选择，部分 ID 可能没有资金走势。', required=True),
            _param('start_date', 'string', '起始日期，可选；按 date 过滤。'),
            _param('end_date', 'string', '结束日期，可选；按 date 过滤。'),
            _param('count', 'integer', '返回条数，默认 20，最大 500。', default=20),
        ),
        fields=(
            _field('board_name', 'string', '题材或行业名。', '化学制药'),
            _field('date', 'date/string', '日期。', '20260506'),
            _field('main_amount', 'number', '主力资金。', -2188328.25),
            _field('main_buy_amount', 'number', '主买资金。', -10129654.0),
            _field('avg_main_amount', 'number', '平均主力资金。', -4462953.86),
            _field('avg_main_buy_amount', 'number', '平均主买资金。', -6449633.2),
        ),
    ),
    'concept_control_series_tdx': F10InterfaceSpec(
        name='concept_control_series_tdx',
        display_name_zh='主力控盘序列',
        category='F10数据',
        summary_zh='查询每日主力控盘比例序列。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选；按 date 过滤。'),
            _param('end_date', 'string', '结束日期，可选；按 date 过滤。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('date', 'date/string', '日期。', '20260601'),
            _field('control_ratio_pct', 'number', '主力控盘比例，单位：%。', 41.58),
            _field('board_code', 'string', '所属板块代码。', '881386'),
            _field('board_name', 'string', '所属板块名称。', '全国性银行'),
            _field('rank', 'integer', '排名。', 6),
        ),
    ),
    'concept_control_ranking_tdx': F10InterfaceSpec(
        name='concept_control_ranking_tdx',
        display_name_zh='控盘榜单',
        category='F10数据',
        summary_zh='查询行业或题材按日期返回的控盘榜单；每个日期内通常是前十名。',
        entry="",
        body_kind="",
        params=(
            _param('concept_code', 'string', '题材或行业 ID；可先从个股题材接口返回的 topic_id 中选择，部分 ID 可能没有控盘榜单。', required=True),
            _param('count', 'integer', '返回前多少条榜单记录，默认 20，最大 500；记录按日期榜单拍平后计数。', default=20),
        ),
        fields=(
            _field('date', 'date/string', '日期。', '20260506'),
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。', '002102.SZ'),
            _field('exchange', 'string', 'AxData 交易所代码：SSE、SZSE 或 BSE。', 'SZSE'),
            _field('rank', 'integer', '排名。', 1),
            _field('market_code', 'integer', '市场代码。', 0),
            _field('symbol', 'string', '股票代码。', '002102'),
            _field('name', 'string', '股票名称。', 'ST能特'),
            _field('control_ratio_pct', 'number', '控盘比例，单位：%。', 57.8),
        ),
    ),
    'concept_constituent_comparison_tdx': F10InterfaceSpec(
        name='concept_constituent_comparison_tdx',
        display_name_zh='题材内对比',
        category='F10数据',
        summary_zh='查询题材内股票涨幅、财务或市值对比。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('concept_code', 'string', '题材 ID。', required=True),
            _param('compare_type', 'string', '对比类型：return 涨幅，financial 财务；默认 return。', default='return'),
            _param('sort_by', 'string', '源端排序字段，默认 zdf；实测不同字段可能仍按源端默认排序。', default='zdf'),
        ),
        fields=(
            _field('rank', 'integer', '排名。', 1),
            _field('market_code', 'integer', '市场代码。', 0),
            _field('symbol', 'string', '股票代码。', '301171'),
            _field('name', 'string', '股票简称。', '易点天下'),
            _field('report_period', 'date/string', '财务数据报告期；compare_type=financial 时返回。', '20260331'),
            _field('change_pct', 'number', '涨幅，单位：%。', 8.23),
            _field('change_pct_3d', 'number', '3 日涨幅，单位：%。', 0.42),
            _field('change_pct_5d', 'number', '5 日涨幅，单位：%。', -5.71),
            _field('change_pct_20d', 'number', '20 日涨幅，单位：%。', -17.31),
            _field('change_pct_60d', 'number', '60 日涨幅，单位：%。', 4.11),
            _field('total_market_cap', 'number', '总市值。', 12235300000.0),
            _field('float_market_cap', 'number', '流通市值。', 8932100000.0),
            _field('revenue', 'number', '营业收入。'),
            _field('net_profit', 'number', '归母净利润。'),
            _field('revenue_yoy_pct', 'number', '营收同比，单位：%。'),
            _field('net_profit_yoy_pct', 'number', '归母净利润同比，单位：%。'),
        ),
    ),
    'stock_valuation_metrics_tdx': F10InterfaceSpec(
        name='stock_valuation_metrics_tdx',
        display_name_zh='估值表',
        category='F10数据',
        summary_zh='查询估值、市值和估值百分位。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('start_date', 'string', '起始日期，可选；按 date 过滤。'),
            _param('end_date', 'string', '结束日期，可选；按 date 过滤。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。', '000001.SZ'),
            _field('symbol', 'string', '交易所原始六位代码。', '000001'),
            _field('date', 'date/string', '日期。', '20260615'),
            _field('pe_ttm', 'number', 'PE(TTM)。', 4.98),
            _field('pe_percentile', 'number', 'PE 百分位。', 41.21),
            _field('pb_mrq', 'number', 'PB(MRQ)。', 0.46),
            _field('pb_percentile', 'number', 'PB 百分位。', 5.7),
            _field('pcf_ttm', 'number', '市现率(TTM)。', 1.13),
            _field('pcf_percentile', 'number', '市现率百分位。', 42.69),
            _field('ps_ttm', 'number', '市销率(TTM)。', 1.61),
            _field('ps_percentile', 'number', '市销率百分位。', 64.66),
            _field('peg', 'number', 'PEG。', 0.1),
            _field('float_market_cap', 'number', '流通市值。', 214625959936.0),
            _field('total_market_cap', 'number', '总市值。', 214629466112.0),
        ),
    ),
    'stock_valuation_series_tdx': F10InterfaceSpec(
        name='stock_valuation_series_tdx',
        display_name_zh='单指标估值序列',
        category='F10数据',
        summary_zh='查询单个估值指标的历史序列和百分位，适合画 PE/PB/PS/PCF 曲线。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('metric', 'string', '指标：pe、pb、pcf、ps；默认 pe。', default='pe'),
            _param('start_date', 'string', '起始日期，可选；按 date 过滤。'),
            _param('end_date', 'string', '结束日期，可选；按 date 过滤。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '日期。', '20260601'),
            _field('metric', 'string', '指标。', 'pe'),
            _field('value', 'number', '指标值。', 4.95),
            _field('percentile', 'number', '历史百分位。', 37.49),
        ),
    ),
    'stock_valuation_band_tdx': F10InterfaceSpec(
        name='stock_valuation_band_tdx',
        display_name_zh='PE/PB估值通道',
        category='F10数据',
        summary_zh='查询 PE/PB Band 估值通道数据，用于绘制估值带图。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('metric', 'string', '指标：pe 或 pb；默认 pe。', default='pe'),
            _param('start_date', 'string', '起始日期，可选；按 date 过滤。'),
            _param('end_date', 'string', '结束日期，可选；按 date 过滤。'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('date', 'date/string', '日期。'),
            _field('band_value_1', 'number', '当前 PE 或 PB 指标值。'),
            _field('band_value_2', 'number', '通道辅助值 2，源端用于绘制 Band。'),
            _field('band_value_3', 'number', '通道辅助值 3，源端用于绘制 Band。'),
            _field('total_count', 'integer', '当前统计区间样本数。'),
            _field('min_value', 'number', '当前统计区间最小值。'),
            _field('mid_value', 'number', '当前统计区间中位值。'),
        ),
    ),
    'stock_return_calendar_tdx': F10InterfaceSpec(
        name='stock_return_calendar_tdx',
        display_name_zh='月度年度涨跌幅',
        category='F10数据',
        summary_zh='按年份汇总股票 1 至 12 月涨跌幅和全年涨跌幅，用于查看历史收益日历。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('year', 'string', '年份，可选；不传返回全部可用年份。'),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('symbol', 'string', '交易所原始六位代码。'),
            _field('year', 'string', '年份。', '2026'),
            _field('month_1_pct', 'number', '1 月涨跌幅，单位：%。', -5.0833),
            _field('month_2_pct', 'number', '2 月涨跌幅，单位：%。', 0.6463),
            _field('month_3_pct', 'number', '3 月涨跌幅，单位：%。', 1.6514),
            _field('month_4_pct', 'number', '4 月涨跌幅，单位：%。', 3.7004),
            _field('month_5_pct', 'number', '5 月涨跌幅，单位：%。', -4.8738),
            _field('month_6_pct', 'number', '6 月涨跌幅，单位：%。', 3.3852),
            _field('month_7_pct', 'number', '7 月涨跌幅，单位：%。', 0.0),
            _field('month_8_pct', 'number', '8 月涨跌幅，单位：%。', 0.0),
            _field('month_9_pct', 'number', '9 月涨跌幅，单位：%。', 0.0),
            _field('month_10_pct', 'number', '10 月涨跌幅，单位：%。', 0.0),
            _field('month_11_pct', 'number', '11 月涨跌幅，单位：%。', 0.0),
            _field('month_12_pct', 'number', '12 月涨跌幅，单位：%。', 0.0),
            _field('year_pct', 'number', '年度涨跌幅，单位：%。', -0.964),
        ),
    ),
    'stock_market_rankings_tdx': F10InterfaceSpec(
        name='stock_market_rankings_tdx',
        display_name_zh='排名明细',
        category='F10数据',
        summary_zh='查询市场或行业排名明细。',
        entry="",
        body_kind="",
        params=(
            _param('code', 'string/list', '股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。', required=True),
            _param('scope', 'string', '范围：market 全市场排名，industry 为传入股票所属行业内排名；默认 market。建议单只股票调用。', default='market'),
            _param('count', 'integer', '返回条数，默认 20。', default=20),
        ),
        fields=(
            _field('instrument_id', 'string', 'AxData 统一证券代码，例如 000001.SZ。'),
            _field('rank', 'integer', '排名。'),
            _field('rank_change', 'number', '排名变化。'),
            _field('symbol', 'string', '股票代码。'),
            _field('name', 'string', '证券简称。'),
            _field('exchange', 'string', 'AxData 交易所代码：SSE、SZSE 或 BSE。'),
            _field('market_code', 'string', '市场代码。'),
            _field('updated_time', 'datetime/string', '更新时间。'),
        ),
    ),
}

