"""TDX 7615 F10 interface specifications.

The specs describe product-facing AxData interfaces and the source request
shape needed by the 7615 adapter. User-facing catalogs can reuse the same names
without exposing source protocol details.
"""

from __future__ import annotations

from typing import Any

from .tdx_f10_models import F10FieldSpec, F10InterfaceSpec, F10ParamSpec


COMMON_STOCK_PARAMS = (
    F10ParamSpec(
        name="code",
        dtype="string/list",
        required=True,
        description_zh="股票代码：支持 000001、000001.SZ、sz000001；批量可传列表或英文逗号分隔字符串。",
    ),
)

COUNT_PARAM = F10ParamSpec(
    name="count",
    dtype="integer",
    required=False,
    default=20,
    description_zh="返回条数，默认 20。",
)

CURSOR_PARAM = F10ParamSpec(
    name="cursor",
    dtype="string",
    required=False,
    description_zh="分页游标；不传从第一页开始。",
)


def field(
    name: str,
    dtype: str,
    description_zh: str,
    source: str | tuple[str, ...] | None = None,
    example: Any = None,
) -> F10FieldSpec:
    return F10FieldSpec(name=name, dtype=dtype, description_zh=description_zh, source=source, example=example)


def param(
    name: str,
    dtype: str,
    description_zh: str,
    *,
    required: bool = False,
    default: Any = None,
) -> F10ParamSpec:
    return F10ParamSpec(name=name, dtype=dtype, required=required, description_zh=description_zh, default=default)


F10_INTERFACE_SPECS: dict[str, F10InterfaceSpec] = {
    "stock_ipo_listing_profile_tdx": F10InterfaceSpec(
        name="stock_ipo_listing_profile_tdx",
        display_name_zh="发行上市资料",
        category="F10数据",
        summary_zh="查询公司发行上市资料。",
        entry="CWServ.tdxf10_gg_gsgk",
        body_kind="params",
        params=COMMON_STOCK_PARAMS,
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("stock_type", "string", "股票类别。", "T035", "A股"),
            field("list_date", "date/string", "上市日期。", "T031", "19940509"),
            field("issue_method", "string", "发行方式。", "T051", "申请表抽签限额认购"),
            field("issue_system", "string", "发行制度。", "fxzd", "核准制"),
            field("par_value", "number", "每股面值，单位：元。", "mgmz", 1.0),
            field("issue_price", "number", "发行价格，单位：元。", "T042", 5.2),
            field("issue_volume", "number", "发行数量。", "T044", 4680),
            field("raised_amount", "number", "实际募资总额。", "T056", 24336),
            field("net_raised_amount", "number", "实际募资净额。", "T057", 23390.2),
            field("first_open", "number", "首日开盘价，单位：元。", "T059", 7.2),
            field("first_close", "number", "首日收盘价，单位：元。", "T060", 6.76),
            field("lead_underwriter", "string", "主承销商。", "zcxs", "巨田证券有限责任公司"),
            field("sponsor", "string", "上市保荐人。", "bjr", "巨田证券有限责任公司"),
        ),
        body_template={"Params": ["8", "{code}", ""]},
    ),
    "stock_index_constituent_changes_tdx": F10InterfaceSpec(
        name="stock_index_constituent_changes_tdx",
        display_name_zh="指数调入调出",
        category="F10数据",
        summary_zh="查询股票被指数调入或调出的历史记录。",
        entry="CWServ.tdxf10_gg_gsgk",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "起始日期，可选；不传返回全部记录。"),
            param("end_date", "string", "结束日期，可选；不传返回全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("publish_date", "date/string", "指数调整公布日期。", "N001", "20241129"),
            field("change_direction", "string", "指数调入/调出方向。", "N002", "调入"),
            field("index_name", "string", "指数名称。", "N003", "中证500"),
            field("publish_date_change_pct", "number", "公布日涨跌幅，单位：%。", "N004", 1.9496101),
            field("effective_date", "date/string", "指数调整日期。", "N005", "20241216"),
            field("effective_date_change_pct", "number", "调整日涨跌幅，单位：%。", "N006", -1.9343494),
        ),
        body_template={"Params": ["9", "{code}", ""]},
    ),
    "stock_company_profile_tdx": F10InterfaceSpec(
        name="stock_company_profile_tdx",
        display_name_zh="公司概况",
        category="F10数据",
        summary_zh="查询公司发行上市资料和指数调入调出记录。",
        entry="CWServ.tdxf10_gg_gsgk",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "type",
                "string",
                "资料类型：listing 发行上市信息，index_change 指数调入调出；默认 listing。",
                default="listing",
            ),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("stock_type", "string", "股票类别。", "T035", "A股"),
            field("list_date", "date/string", "上市日期。", "T031", "19940509"),
            field("issue_method", "string", "发行方式。", "T051", "申请表抽签限额认购"),
            field("issue_system", "string", "发行制度。", "fxzd", "核准制"),
            field("par_value", "number", "每股面值，单位：元。", "mgmz", 1.0),
            field("issue_price", "number", "发行价格，单位：元。", "T042", 5.2),
            field("issue_volume", "number", "发行数量。", "T044", 4680),
            field("raised_amount", "number", "实际募资总额。", "T056", 24336),
            field("net_raised_amount", "number", "实际募资净额。", "T057", 23390.2),
            field("first_open", "number", "首日开盘价，单位：元。", "T059", 7.2),
            field("first_close", "number", "首日收盘价，单位：元。", "T060", 6.76),
            field("lead_underwriter", "string", "主承销商。", "zcxs", "巨田证券有限责任公司"),
            field("sponsor", "string", "上市保荐人。", "bjr", "巨田证券有限责任公司"),
            field("publish_date", "date/string", "指数调整公布日期。", "N001"),
            field("change_direction", "string", "指数调入/调出方向。", "N002"),
            field("index_name", "string", "指数名称。", "N003"),
            field("publish_date_change_pct", "number", "公布日涨跌幅，单位：%。", "N004"),
            field("effective_date", "date/string", "指数调整日期。", "N005"),
            field("effective_date_change_pct", "number", "调整日涨跌幅，单位：%。", "N006"),
        ),
        function_param="type",
        function_default="listing",
        function_aliases={"listing": "8", "index_change": "9"},
        body_template={"Params": ["{function}", "{code}", ""]},
    ),
    "stock_business_composition_tdx": F10InterfaceSpec(
        name="stock_business_composition_tdx",
        display_name_zh="主营构成",
        category="F10数据",
        summary_zh="查询各报告期主营收入、成本、毛利和毛利率。",
        entry="CWServ.tdxf10_gg_jyfx",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("period", "string", "报告期，格式 YYYYMMDD；不传时返回全部可用报告期。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("report_period", "date/string", "报告期。", ("rq", "{period}"), "20251231"),
            field("dimension", "string", "分类方式。", "N000", "按产品"),
            field("item_order", "integer", "序号或层级。", "N001", 1),
            field("item_name", "string", "主营构成项目。", "N002", "数字化产品"),
            field("revenue", "number", "主营收入。", "N003", 123456.78),
            field("revenue_ratio_pct", "number", "收入占比，单位：%。", "N004", 62.3),
            field("cost", "number", "主营成本。", "N005", 80000.0),
            field("cost_ratio_pct", "number", "成本占比，单位：%。", "N006", 58.2),
            field("gross_profit", "number", "毛利。", "N007", 43456.78),
            field("profit_ratio_pct", "number", "利润占比，单位：%。", "N008", 66.1),
            field("gross_margin_pct", "number", "毛利率，单位：%。", "N009", 35.2),
        ),
        body_template={"Params": ["{code}", "zygc", "{period}"]},
    ),
    "stock_financial_statement_tdx": F10InterfaceSpec(
        name="stock_financial_statement_tdx",
        display_name_zh="资产负债表",
        category="F10数据",
        summary_zh="查询资产负债表。",
        entry="CWServ.tdxf10_gg_cwfx",
        body_kind="params",
        params=COMMON_STOCK_PARAMS,
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("report_period", "date/string", "报告期。", "rq", "20251231"),
            field("cash", "number", "货币资金。", "T007"),
            field("trading_financial_assets", "number", "交易性金融资产。", "T008"),
            field("notes_receivable", "number", "应收票据。", "T009"),
            field("accounts_receivable", "number", "应收账款。", "T010"),
            field("current_assets", "number", "流动资产合计。", "T020"),
            field("total_assets", "number", "资产总计。", "T039"),
            field("short_term_borrowing", "number", "短期借款。", "T040"),
            field("notes_payable", "number", "应付票据。", "T042"),
            field("accounts_payable", "number", "应付账款。", "T043"),
            field("current_liabilities", "number", "流动负债合计。", "T053"),
            field("total_liabilities", "number", "负债合计。", "T062"),
            field("share_capital", "number", "实收资本或股本。", "T063"),
            field("capital_reserve", "number", "资本公积金。", "T064"),
            field("undistributed_profit", "number", "未分配利润。", "T067"),
            field("parent_equity", "number", "归母权益合计。", "T077"),
            field("total_equity", "number", "所有者权益合计。", "T071"),
            field("liabilities_and_equity", "number", "负债和股东权益合计。", "T072"),
        ),
        body_template={"Params": ["{code}", "zcfzb", ""]},
    ),
    "stock_financial_diagnosis_tdx": F10InterfaceSpec(
        name="stock_financial_diagnosis_tdx",
        display_name_zh="财务诊断",
        category="F10数据",
        summary_zh="查询源端财务能力、预警和评分。该接口为源端评价，不代表 AxData 自有判断。",
        entry="CWServ.tdxf10_gg_cwzd",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "dimension",
                "string",
                "诊断维度：operation 营运能力、profit 盈利能力、growth 成长能力、cashflow 现金流、asset_quality 资产质量、z_score Z值预警、score 综合评分；默认 score。",
                default="score",
            ),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("stock_name", "string", "股票简称。", "N000"),
            field("compare_group", "string", "对比行业或板块。", "N001"),
            field("report_period", "date/string", "报告期。", "N002"),
            field("rank", "integer", "个股排名。", "N003"),
            field("rank_change", "number", "排名或评分变化。", "N004"),
            field("rating_code", "string", "评价等级码。", "N005"),
            field("score", "number", "源端综合评分。", "N006"),
            field("percentile", "number", "分位或打败比例。", "N007"),
            field("warning_value", "number", "Z 值或预警值。", "N002"),
        ),
        function_param="dimension",
        function_default="score",
        function_aliases={
            "operation": "yynl",
            "profit": "ylnl",
            "growth": "cznl",
            "cashflow": "xjl",
            "asset_quality": "zczl",
            "z_score": "zzyj",
            "score": "cwzpf_zx",
        },
        body_template={"Params": ["{function}", "{code}", ""]},
        evaluation=True,
    ),
    "stock_forecast_consensus_tdx": F10InterfaceSpec(
        name="stock_forecast_consensus_tdx",
        display_name_zh="盈利预测",
        category="F10数据",
        summary_zh="查询盈利预测统计，包括未来三年预测、历史实际值和预测机构数量。",
        entry="CWServ.tdxf10_gg_ybpj",
        body_kind="params",
        params=COMMON_STOCK_PARAMS,
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("forecast_start_year", "integer", "预测起始年份。", "nyear"),
            field("align_flag", "string", "年份对齐标记。", "flag"),
            field("eps_year1", "number", "未来第一年预测每股收益。", "T036"),
            field("eps_year2", "number", "未来第二年预测每股收益。", "T037"),
            field("eps_year3", "number", "未来第三年预测每股收益。", "T038"),
            field("net_profit_year1", "number", "未来第一年预测归母净利润。", "T033"),
            field("net_profit_year2", "number", "未来第二年预测归母净利润。", "T034"),
            field("net_profit_year3", "number", "未来第三年预测归母净利润。", "T035"),
            field("revenue_year1", "number", "未来第一年预测营业收入。", "T021"),
            field("revenue_year2", "number", "未来第二年预测营业收入。", "T022"),
            field("revenue_year3", "number", "未来第三年预测营业收入。", "T023"),
            field("forecast_institution_count", "integer", "预测机构数量。", "t023"),
        ),
        body_template={"Params": ["{code}", "ylyctj"]},
        main_table_index=1,
    ),
    "stock_dividend_history_tdx": F10InterfaceSpec(
        name="stock_dividend_history_tdx",
        display_name_zh="分红历史",
        category="F10数据",
        summary_zh="查询历史分红方案、登记日、除权日和方案进度。",
        entry="CWServ.tdxf10_gg_fhrz",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_year", "string", "起始年份，可选；不传返回全部记录。"),
            param("end_year", "string", "结束年份，可选；不传返回全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("report_period", "date/string", "分红年度或报告期。", "rq"),
            field("board_date", "date/string", "董事会日期。", "T003"),
            field("plan", "string", "分红方案。", "T004"),
            field("eps", "number", "每股收益。", "T006"),
            field("roe_weighted_pct", "number", "加权净资产收益率，单位：%。", "T026"),
            field("record_date", "date/string", "股权登记日。", "T021"),
            field("ex_dividend_date", "date/string", "除权派息日。", "T023"),
            field("progress", "string", "方案进度。", "T036"),
            field("progress_code", "string", "方案进度码。", "aT036"),
            field("payout_ratio_pct", "number", "股利支付率，单位：%。", "glzfl"),
            field("target_holder", "string", "派发对象。", "jdcode"),
        ),
        body_template={"Params": ["{code}", "fh"]},
    ),
    "stock_dividend_metrics_tdx": F10InterfaceSpec(
        name="stock_dividend_metrics_tdx",
        display_name_zh="分红指标",
        category="F10数据",
        summary_zh="查询股息率、股利支付率、派现融资等分红指标。",
        entry="CWServ.tdxf10_gg_fhrz",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "metric",
                "string",
                "指标：dividend_yield 股息率、payout_ratio 股利支付率、cash_financing 派现融资；默认 dividend_yield。",
                default="dividend_yield",
            ),
            param(
                "view",
                "string",
                "展示方式：trend 走势、ranking 排名、summary 总览；不传时 dividend_yield/payout_ratio 默认 trend，cash_financing 默认 summary。",
            ),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "日期或期间。", "N001"),
            field("metric_value", "number", "指标值。", ("N002", "N003", "gxl", "glzfl")),
            field("benchmark_value", "number", "对照值。", "N003"),
            field("rank", "integer", "排名。", "N001"),
            field("stock_name", "string", "证券简称。", "N002"),
            field("stock_code", "string", "股票代码。", "dm"),
            field("summary_total", "number", "汇总总额。", "total"),
            field("cash_dividend_total", "number", "累计现金分红。", "ljxjfh"),
        ),
        function_param="metric",
        function_default="dividend_yield",
        function_aliases={
            "dividend_yield": "fhlszs_gxl",
            "payout_ratio": "fhlszs_glzfl",
            "cash_financing": "pxmz",
            "dividend_yield_rank": "fhpm_gxl",
            "payout_ratio_rank": "fhpm_glzfl",
            "cash_financing_rank": "fhpm_pxrzb",
        },
        body_template={"Params": ["{code}", "{function}"]},
    ),
    "stock_equity_financing_events_tdx": F10InterfaceSpec(
        name="stock_equity_financing_events_tdx",
        display_name_zh="融资事件",
        category="F10数据",
        summary_zh="查询增发、配股、股权激励、可转债等融资相关事件。",
        entry="CWServ.tdxf10_gg_fhrz",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "event_type",
                "string",
                "事件类型：placement 增发、rights_issue 配股、incentive 股权激励、convertible_bond 可转债；默认 placement。",
                default="placement",
            ),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("event_date", "date/string", "事件日期。", ("T003", "T002", "rq", "N001", "N004")),
            field("event_type", "string", "事件类型。", "{function}"),
            field("plan", "string", "方案或关键条款。", ("T017", "T007", "N007")),
            field("amount", "number", "融资金额。", ("T025", "T008", "N008")),
            field("price", "number", "发行、配股、授予或转股价格。", ("T012", "N006", "N013")),
            field("volume", "number", "发行、配股、授予或债券规模。", ("T005", "T015", "N004", "N007")),
            field("progress", "string", "进度。", ("T016", "T023", "N002")),
        ),
        function_param="event_type",
        function_default="placement",
        function_aliases={
            "placement": "zf",
            "rights_issue": "pf",
            "incentive": "gqjl",
            "convertible_bond": "kzzdfxyss",
        },
        body_template={"Params": ["{code}", "{function}"]},
    ),
    "stock_private_placement_allocations_tdx": F10InterfaceSpec(
        name="stock_private_placement_allocations_tdx",
        display_name_zh="增发获配明细",
        category="F10数据",
        summary_zh="查询增发获配机构、获配数量和获配金额。",
        entry="CWServ.tdxf10_gg_fhrz_zfhpmx",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "event_date",
                "string",
                "增发日期，格式 YYYYMMDD 或 YYYY-MM-DD；不传返回全部可用增发日期的获配明细。",
            ),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("event_date", "date/string", "增发日期。", "rq"),
            field("allocator", "string", "获配机构。", "T004"),
            field("allocated_volume", "number", "获配数量，单位：股。", "T007"),
            field("subscribed_volume", "number", "申购数量，单位：股。", "T008"),
            field("allocated_amount", "number", "获配金额，单位：元。", "T012"),
            field("lock_months", "number", "锁定期，单位：月。", "T009"),
            field("institution_type", "string", "机构类型。", "T006"),
            field("unlock_date", "date/string", "解禁日期。", "jjrq"),
            field("shareholder_id", "string", "股东 ID。", "T002"),
        ),
        body_template={"Params": ["zfpg", "{code}", "{event_date_dash}"]},
    ),
    "stock_shareholder_change_plans_tdx": F10InterfaceSpec(
        name="stock_shareholder_change_plans_tdx",
        display_name_zh="股东增减持",
        category="F10数据",
        summary_zh="查询股东增持或减持计划。",
        entry="CWServ.tdxf10_gg_gdyj",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("direction", "string", "方向筛选：increase 增持、decrease 减持；不传返回全部方向。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("announcement_date", "date/string", "最新公告日。", "N001"),
            field("direction", "string", "变动方向。", "N002"),
            field("shareholder_name", "string", "股东名称。", "N003"),
            field("shareholder_role", "string", "股东身份或职务。", "N004"),
            field("planned_volume_upper", "number", "拟变动数量上限，单位：股。", "N005"),
            field("planned_ratio_upper_pct", "number", "拟变动上限占总股本比例，单位：%。", "N006"),
            field("planned_amount_upper", "number", "拟变动资金上限，单位：元；源端未按金额披露时为空。", "N008"),
            field("start_date", "date/string", "起始变动日期。", "N009"),
            field("end_date", "date/string", "截止变动日期。", "N010"),
            field("progress", "string", "进度。", "N011"),
            field("detail_id", "string", "详情记录 ID。", "N012"),
        ),
        body_template={"Params": ["{code}", "gdzjcjh", "", "", "{page}", "{page}", "{count}"]},
    ),
    "stock_northbound_holding_tdx": F10InterfaceSpec(
        name="stock_northbound_holding_tdx",
        display_name_zh="沪深股通持股",
        category="F10数据",
        summary_zh="查询沪深股通持股变化序列；不传日期默认返回全部可用记录。",
        entry="CWServ.tdxf10_gg_zlcc",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "起始日期，可选；不传返回全部记录。"),
            param("end_date", "string", "结束日期，可选；不传返回全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("channel_type", "string", "当前持股记录对应的交易通道；有记录的深市标为深股通，沪市标为沪股通。"),
            field("date", "date/string", "指标日期。", "N001"),
            field("holding_ratio_pct", "number", "持股比例，单位：%。", "N002"),
            field("holding_volume", "number", "持股数量，单位：股。", "N003"),
            field("change_volume", "number", "变动股数，单位：股。", "N004"),
            field("change_pct", "number", "较上期变化，单位：%。", "N005"),
            field("close", "number", "收盘价，单位：元。", "N006"),
        ),
        body_template={"Params": ["{code}", "bszj", "", "{page}", "{page}", "{count}"]},
    ),
    "stock_margin_trading_tdx": F10InterfaceSpec(
        name="stock_margin_trading_tdx",
        display_name_zh="融资融券",
        category="F10数据",
        summary_zh="查询源端融资融券统计。",
        entry="CWServ.tdxf10_gg_ggzp",
        body_kind="params",
        params=COMMON_STOCK_PARAMS + (param("start_date", "string", "起始日期，可选。"), param("end_date", "string", "结束日期，可选。")),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "日期。", "N001"),
            field("margin_net_buy", "number", "融资净买入。", "N002"),
            field("margin_balance", "number", "融资余额。", "N003"),
            field("short_balance", "number", "融券相关统计。", "N004"),
        ),
        body_template={"Params": ["rzrq", "{code}", "", ""]},
    ),
    "stock_chip_distribution_tdx": F10InterfaceSpec(
        name="stock_chip_distribution_tdx",
        display_name_zh="筹码分布",
        category="F10数据",
        summary_zh="查询源端筹码分布统计。",
        entry="CWServ.tdxf10_gg_ggzp",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "按统计日期过滤的起始日期；不传返回源端本次给出的全部记录。"),
            param("end_date", "string", "按统计日期过滤的结束日期；不传返回源端本次给出的全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "统计日期。", "N001"),
            field("profit_ratio_pct", "number", "获利比例，单位：%。", "N002"),
            field("cost90_concentration", "number", "90% 成本区间宽窄，数值越小表示筹码成本越集中。", "N003"),
            field("cost90_range", "string", "覆盖 90% 筹码的估算成本区间。", "N004"),
            field("cost70_concentration", "number", "70% 成本区间宽窄，数值越小表示核心筹码成本越集中。", "N005"),
            field("cost70_range", "string", "覆盖 70% 筹码的估算成本区间。", "N006"),
        ),
        body_template={"Params": ["cmfb", "{code}", "", ""]},
    ),
    "stock_research_reports_tdx": F10InterfaceSpec(
        name="stock_research_reports_tdx",
        display_name_zh="研报列表",
        category="F10数据",
        summary_zh="查询公司研究报告列表。",
        entry="CWServ.tdxf10_gg_gszx",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("rating", "string", "评级筛选：all、buy、overweight、neutral、underweight、sell；默认 all。", default="all"),
            param("keyword", "string", "标题关键字，可选。"),
            COUNT_PARAM,
            CURSOR_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("rating", "string", "评级类别。", "T004"),
            field("analyst", "string", "研究员。", "T009"),
            field("publish_date", "date/string", "撰写日期。", "T012"),
            field("detail_id", "string", "研报详情 ID。", "T011"),
            field("title", "string", "研报标题。", "T039"),
            field("attachment", "string", "研报附件标识。", "ybdz"),
        ),
        body_template={"Params": ["{code}", "gsyj", "{keyword}", "{rating_code}", "{page}", "{count}"]},
    ),
    "stock_analyst_rating_tdx": F10InterfaceSpec(
        name="stock_analyst_rating_tdx",
        display_name_zh="机构评级与目标价",
        category="F10数据",
        summary_zh="查询机构评级家数和目标价统计。",
        entry="CWServ.tdxf10_gg_ggzp",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "按评级统计日期过滤的起始日期；不传返回源端本次给出的记录。"),
            param("end_date", "string", "按评级统计日期过滤的结束日期；不传返回源端本次给出的记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "评级统计日期。", "N001"),
            field("buy_count", "integer", "买入家数。", "N002"),
            field("overweight_count", "integer", "增持家数。", "N003"),
            field("neutral_count", "integer", "中性家数。", "N004"),
            field("underweight_count", "integer", "减持家数。", "N005"),
            field("sell_count", "integer", "卖出家数。", "N006"),
            field("target_price", "number", "平均目标价。", "N005"),
            field("target_price_low", "number", "目标价下限。", "N007"),
            field("target_price_high", "number", "目标价上限。", "N008"),
            field("current_price", "number", "当前价。", "N006"),
            field("upside_pct", "number", "上涨空间，单位：%。", "N004"),
        ),
        body_template={"Params": ["jgpj", "{code}", "", ""]},
    ),
    "stock_institution_holding_tdx": F10InterfaceSpec(
        name="stock_institution_holding_tdx",
        display_name_zh="机构持仓",
        category="F10数据",
        summary_zh="查询机构持仓比例多期趋势。",
        entry="CWServ.tdxf10_gg_ggzp",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "按报告日期过滤的起始日期；不传返回源端本次给出的全部记录。"),
            param("end_date", "string", "按报告日期过滤的结束日期；不传返回源端本次给出的全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "报告日期。", "N001"),
            field("report_period", "string", "报告期名称，例如 2026一季报。", "N004"),
            field("institution_holding_ratio_pct", "number", "机构持仓比例，单位：%。", "N002"),
            field("close", "number", "当期收盘价，单位：元。", "N003"),
        ),
        body_template={"Params": ["jgcc_tb", "{code}", "", ""]},
    ),
    "stock_governance_guarantees_tdx": F10InterfaceSpec(
        name="stock_governance_guarantees_tdx",
        display_name_zh="担保明细",
        category="F10数据",
        summary_zh="查询担保方、被担保方、担保金额和担保期限。",
        entry="CWServ.tdxf10_gg_zbyz",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("period", "string", "报告期；不传自动取最新可用报告期。"),
            param("count", "integer", "返回条数，默认 20；该接口单期可能有大量明细。", default=20),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("report_period", "date/string", "报告期。", "N001"),
            field("guarantor", "string", "担保方。", "N002"),
            field("guaranteed_party", "string", "被担保方。", "N003"),
            field("amount", "number", "担保金额。", "N004"),
            field("currency", "string", "币种。", "N005"),
            field("guarantee_type", "string", "担保类型。", "N008"),
            field("is_completed", "string", "是否履行完毕。", "N009"),
            field("is_related_party", "string", "是否关联交易。", "N010"),
            field("actual_date", "date/string", "实际发生日。", "N011"),
            field("term", "number/string", "担保期限，源端原值，可能为数字或空。", "N012"),
        ),
        body_template={"Params": ["dbmx", "{code}", "{period}"]},
    ),
    "stock_violation_cases_tdx": F10InterfaceSpec(
        name="stock_violation_cases_tdx",
        display_name_zh="违规处理",
        category="F10数据",
        summary_zh="查询违规处理和处罚决定。",
        entry="CWServ.tdxf10_gg_zbyz",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "按立案日期过滤的起始日期；不传返回源端本次给出的全部记录。"),
            param("end_date", "string", "按立案日期过滤的结束日期；不传返回源端本次给出的全部记录。"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("case_date", "date/string", "立案日期。", "T003"),
            field("case_type", "string", "立案类型。", "T009"),
            field("publish_date", "date/string", "处罚公布日期，源端可能为空。", "T008"),
            field("progress", "string", "案情进展。", "T004"),
            field("detail_id", "string", "违法事实详情 ID。", "rec_id"),
            field("decision", "string", "处罚决定，源端可能为空。", "T007"),
        ),
        body_template={"Params": ["wgcl", "{code}", ""]},
    ),
    "stock_regulatory_actions_tdx": F10InterfaceSpec(
        name="stock_regulatory_actions_tdx",
        display_name_zh="监管措施",
        category="F10数据",
        summary_zh="查询监管措施或处罚函件。",
        entry="CWServ.tdxf10_gg_gszx",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "按处罚公布日期过滤的起始日期；不传返回源端本次给出的全部记录。"),
            param("end_date", "string", "按处罚公布日期过滤的结束日期；不传返回源端本次给出的全部记录。"),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("publish_date", "date/string", "处罚公布日期。", "N001"),
            field("target", "string", "处罚对象。", "N002"),
            field("action", "string", "监管措施。", "N003"),
            field("content", "string", "函件内容。", "N004"),
            field("link", "string", "链接，源端可能为空。", "N005"),
        ),
        body_template={"Params": ["{code}", "jgcs", "", "0", "{page}", "{count}"]},
    ),
    "stock_score_summary_tdx": F10InterfaceSpec(
        name="stock_score_summary_tdx",
        display_name_zh="综合评分",
        category="F10数据",
        summary_zh="查询源端综合评分、维度评分和排名。该接口为源端评价，不代表 AxData 自有判断。",
        entry="CWServ.tdxf10_gg_ggzp",
        body_kind="params",
        params=COMMON_STOCK_PARAMS,
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("score", "number", "源端综合评分。", "N001"),
            field("industry_rank", "integer", "行业排名名次。", "N002"),
            field("industry_rank_total", "integer", "行业排名总数。", "N003"),
            field("market_rank", "integer", "A 股市场排名名次。", "N004"),
            field("market_rank_total", "integer", "A 股市场排名总数。", "N005"),
            field("market_win_pct", "number", "打败 A 股百分比。", "N006"),
            field("date", "date/string", "日期。", "N007"),
            field("capital_score", "number", "资金面评分。", "N008"),
            field("fundamental_score", "number", "基本面评分。", "N009"),
            field("news_score", "number", "消息面评分。", "N010"),
            field("theme_score", "number", "主题面评分。", "N011"),
            field("industry_name", "string", "行业名。", "N012"),
            field("stock_name", "string", "股票名。", "N018"),
        ),
        body_template={"Params": ["pf", "{code}", "", ""]},
        evaluation=True,
    ),
    "stock_disclosure_feed_tdx": F10InterfaceSpec(
        name="stock_disclosure_feed_tdx",
        display_name_zh="新闻公告路演",
        category="F10数据",
        summary_zh="查询个股新闻、公告或路演列表。",
        entry="CWSearch.tzx_rcache",
        body_kind="cache",
        params=COMMON_STOCK_PARAMS
        + (
            param("category", "string", "类型：news 新闻、announcement 公告、roadshow 路演；默认 announcement。", default="announcement"),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("category", "string", "资讯类型。", "{category}"),
            field("issue_date", "datetime/string", "发布时间或公告日期；路演通常为空。", "issue_date"),
            field("title", "string", "标题。", "title"),
            field("source", "string", "来源；路演通常为空。", "source"),
            field("detail_table", "string", "详情来源表。", "tableid"),
            field("detail_id", "string", "记录 ID；路演通常为空。", "rec_id"),
            field("type_code", "string", "公告类型码；非公告通常为空。", "typecode"),
            field("type_name", "string", "公告类型名；非公告通常为空。", "typename"),
            field("url", "string", "PDF、新闻或活动链接；源端无链接时为空。", "url"),
            field("summary", "string", "摘要；源端无摘要时为空。", "summary"),
            field("start_date", "date/string", "路演开始日期；非路演为空。", "start_date"),
            field("start_time", "time/string", "路演开始时间；非路演为空。", "start_time"),
            field("end_time", "time/string", "路演结束时间；非路演为空。", "end_time"),
        ),
        function_param="category",
        function_default="announcement",
        function_aliases={"news": "xw", "announcement": "gg", "roadshow": "ly"},
        body_template={"action": "get", "key": "{function}:{market_id}_{code}", "bin": "1", "qsid": "tdx"},
    ),
    "stock_event_drivers_tdx": F10InterfaceSpec(
        name="stock_event_drivers_tdx",
        display_name_zh="历史事件关联",
        category="F10数据",
        summary_zh="查询个股历史事件关联记录；不是涨停原因库，可选补充详情正文。",
        entry="CWServ.tdxf10_gg_rdtc",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "起始日期，可选；按事件创建日期过滤。"),
            param("end_date", "string", "结束日期，可选；按事件创建日期过滤。"),
            param("include_detail", "boolean", "是否补充详情正文，默认 false。", default=False),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("event_date", "date/string", "事件创建日期。", "cjrq"),
            field("event_name", "string", "事件名称，不等同于涨停原因。", "sjmc"),
            field("detail_id", "string", "事件详情 ID。", "rec_id"),
            field("event_nature", "string", "事件性质。", "sjxz"),
            field("creation_change_pct", "number", "创建日涨跌幅，单位：%。", "cjrzdf"),
            field("has_detail", "boolean", "是否有详情正文。", None),
            field("detail_title", "string", "详情标题；include_detail=true 时补充。", None),
            field("detail_text", "string", "详情正文；include_detail=true 时补充。", None),
        ),
        body_template={"Params": ["{code}", "sjcd"]},
    ),
    "stock_topic_exposure_tdx": F10InterfaceSpec(
        name="stock_topic_exposure_tdx",
        display_name_zh="个股题材",
        category="短线数据",
        summary_zh="查询个股所属题材、关联度和入选原因。",
        entry="CWServ.tdxf10_gg_rdtc",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("topic_type", "string", "题材类型：sector 板块题材、theme 主题题材；默认 theme。", default="theme"),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("topic_type", "string", "题材类型：sector 板块题材、theme 主题题材。", None),
            field("created_date", "date/string", "创建日期。", "ztrq"),
            field("topic_name", "string", "题材名称。", "ztmc"),
            field("relevance", "number", "关联度，源端评价分值。", "gld"),
            field("selected_date", "date/string", "入选或更新日期；源端可能为空。", "rxsj"),
            field("reason", "string", "入选原因或栏目内容。", "ztnr"),
            field("topic_id", "string", "题材 ID。", "id"),
            field("group_code", "string", "源端分组类别码；主题题材可能为空。", "sslb"),
        ),
        function_param="topic_type",
        function_default="theme",
        function_aliases={"sector": "zttzbkz", "theme": "zttzztk"},
        body_template={"Params": ["{code}", "{function}"]},
    ),
    "concept_related_boards_tdx": F10InterfaceSpec(
        name="concept_related_boards_tdx",
        display_name_zh="相关板块",
        category="短线数据",
        summary_zh="查询个股当前关联板块列表。",
        entry="HQServ.hq_nlp_tcihq",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS,
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("board_market", "string", "板块市场。", "N001"),
            field("board_code", "string", "板块代码。", "N002"),
            field("board_name", "string", "板块名称。", "N003"),
            field("change_pct", "number", "涨幅，单位：%。", "N004"),
            field("limit_up_count", "integer", "涨停数。", "N005"),
        ),
        body_template={"ReqId": "200743", "setcode": "{market_id}", "code": "{code}", "zq_num": "30", "Page": -1, "PageSize": "{count}", "modname": "mod_tcihq.dll"},
        main_table_index=1,
    ),
    "concept_constituents_tdx": F10InterfaceSpec(
        name="concept_constituents_tdx",
        display_name_zh="板块成分股",
        category="短线数据",
        summary_zh="按板块代码查询当前成分股。",
        entry="HQServ.hq_nlp_tcihq",
        body_kind="hq",
        params=(
            param(
                "concept_code",
                "string",
                "板块代码；先用相关板块接口按股票代码查询，取返回的 board_code 填入。",
                required=True,
            ),
            param("count", "integer", "返回前多少只，默认 20，最大 500。", default=20),
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。", None, "000001.SZ"),
            field("symbol", "string", "交易所原始六位代码。", "N002", "000001"),
            field("exchange", "string", "AxData 交易所代码：SSE、SZSE 或 BSE。", None, "SZSE"),
            field("market_code", "string", "市场代码。", "N001", "0"),
            field("name", "string", "股票名称。", "N003", "平安银行"),
            field("change_pct", "number", "涨幅，单位：%。", "N004", -0.45),
            field("last_price", "number", "现价，单位：元。", "N005", 11.01),
        ),
        body_template={"ReqId": "200744", "setcode": 0, "code": "{concept_code}", "zq_num": "30", "Page": -1, "PageSize": "{count}", "modname": "mod_tcihq.dll"},
        main_table_index=1,
    ),
    "concept_capital_flow_tdx": F10InterfaceSpec(
        name="concept_capital_flow_tdx",
        display_name_zh="题材资金走势",
        category="短线数据",
        summary_zh="查询题材或行业主力资金走势。",
        entry="HQServ.hq_nlp_tcihq",
        body_kind="hq",
        params=(
            param(
                "concept_code",
                "string",
                "题材或行业 ID；可先从个股题材接口返回的 topic_id 中选择，部分 ID 可能没有资金走势。",
                required=True,
            ),
            param("start_date", "string", "起始日期，可选；按 date 过滤。"),
            param("end_date", "string", "结束日期，可选；按 date 过滤。"),
            param("count", "integer", "返回条数，默认 20，最大 500。", default=20),
        ),
        fields=(
            field("board_name", "string", "题材或行业名。", "N001", "化学制药"),
            field("date", "date/string", "日期。", "N002", "20260506"),
            field("main_amount", "number", "主力资金。", "N003", -2188328.25),
            field("main_buy_amount", "number", "主买资金。", "N004", -10129654.0),
            field("avg_main_amount", "number", "平均主力资金。", "N005", -4462953.86),
            field("avg_main_buy_amount", "number", "平均主买资金。", "N006", -6449633.2),
        ),
        body_template={"ReqId": "200742", "setcode": 0, "code": "{concept_code}", "zq_num": "30", "Page": -1, "PageSize": "{count}", "modname": "mod_tcihq.dll"},
        main_table_index=1,
    ),
    "concept_control_series_tdx": F10InterfaceSpec(
        name="concept_control_series_tdx",
        display_name_zh="主力控盘序列",
        category="F10数据",
        summary_zh="查询每日主力控盘比例序列。",
        entry="HQServ.hq_nlp_tcihq",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "起始日期，可选；按 date 过滤。"),
            param("end_date", "string", "结束日期，可选；按 date 过滤。"),
            COUNT_PARAM,
        ),
        fields=(
            field("date", "date/string", "日期。", "N001", "20260601"),
            field("control_ratio_pct", "number", "主力控盘比例，单位：%。", "N002", 41.58),
            field("board_code", "string", "所属板块代码。", "hy_code", "881386"),
            field("board_name", "string", "所属板块名称。", "hy_name", "全国性银行"),
            field("rank", "integer", "排名。", "rank", 6),
        ),
        body_template={"ReqId": "200745", "setcode": "{market_id}", "code": "{code}", "zq_num": "30", "Page": -1, "PageSize": "{count}", "modname": "mod_tcihq.dll"},
        main_table_index=1,
    ),
    "concept_control_ranking_tdx": F10InterfaceSpec(
        name="concept_control_ranking_tdx",
        display_name_zh="控盘榜单",
        category="F10数据",
        summary_zh="查询行业或题材按日期返回的控盘榜单；每个日期内通常是前十名。",
        entry="HQServ.hq_nlp_tcihq",
        body_kind="hq",
        params=(
            param(
                "concept_code",
                "string",
                "题材或行业 ID；可先从个股题材接口返回的 topic_id 中选择，部分 ID 可能没有控盘榜单。",
                required=True,
            ),
            param("count", "integer", "返回前多少条榜单记录，默认 20，最大 500；记录按日期榜单拍平后计数。", default=20),
        ),
        fields=(
            field("date", "date/string", "日期。", "N001", "20260506"),
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。", None, "002102.SZ"),
            field("exchange", "string", "AxData 交易所代码：SSE、SZSE 或 BSE。", None, "SZSE"),
            field("rank", "integer", "排名。", "pm", 1),
            field("market_code", "integer", "市场代码。", "sc", 0),
            field("symbol", "string", "股票代码。", "code", "002102"),
            field("name", "string", "股票名称。", "name", "ST能特"),
            field("control_ratio_pct", "number", "控盘比例，单位：%。", "zlkp", 57.8),
        ),
        body_template={"ReqId": "200747", "setcode": 0, "code": "{concept_code}", "zq_num": "30", "Page": -1, "PageSize": "{count}", "modname": "mod_tcihq.dll"},
        main_table_index=1,
    ),
    "concept_constituent_comparison_tdx": F10InterfaceSpec(
        name="concept_constituent_comparison_tdx",
        display_name_zh="题材内对比",
        category="F10数据",
        summary_zh="查询题材内股票涨幅、财务或市值对比。",
        entry="CWServ.tdxf10_gg_rdtc_gndb",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param("concept_code", "string", "题材 ID。", required=True),
            param("compare_type", "string", "对比类型：return 涨幅，financial 财务；默认 return。", default="return"),
            param("sort_by", "string", "源端排序字段，默认 zdf；实测不同字段可能仍按源端默认排序。", default="zdf"),
        ),
        fields=(
            field("rank", "integer", "排名。", "pm", 1),
            field("market_code", "integer", "市场代码。", "sc", 0),
            field("symbol", "string", "股票代码。", "zqdm", "301171"),
            field("name", "string", "股票简称。", "zqjc", "易点天下"),
            field("report_period", "date/string", "财务数据报告期；compare_type=financial 时返回。", "bgq", "20260331"),
            field("change_pct", "number", "涨幅，单位：%。", "zdf", 8.23),
            field("change_pct_3d", "number", "3 日涨幅，单位：%。", "zdf_3d", 0.42),
            field("change_pct_5d", "number", "5 日涨幅，单位：%。", "zdf_5d", -5.71),
            field("change_pct_20d", "number", "20 日涨幅，单位：%。", "zdf_20d", -17.31),
            field("change_pct_60d", "number", "60 日涨幅，单位：%。", "zdf_60d", 4.11),
            field("total_market_cap", "number", "总市值。", "T013", 12235300000.0),
            field("float_market_cap", "number", "流通市值。", "T012", 8932100000.0),
            field("revenue", "number", "营业收入。", "T003"),
            field("net_profit", "number", "归母净利润。", "T019"),
            field("revenue_yoy_pct", "number", "营收同比，单位：%。", "T116"),
            field("net_profit_yoy_pct", "number", "归母净利润同比，单位：%。", "T157"),
        ),
        function_param="compare_type",
        function_default="return",
        function_aliases={"return": "gndbzfsj", "financial": "gndbcwsj"},
        body_template={"Params": ["{function}", "{code}", "{concept_code}", "{sort_by}"]},
    ),
    "stock_valuation_metrics_tdx": F10InterfaceSpec(
        name="stock_valuation_metrics_tdx",
        display_name_zh="估值表",
        category="F10数据",
        summary_zh="查询估值、市值和估值百分位。",
        entry="HQServ.hq_nlp_gpsj",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS
        + (
            param("start_date", "string", "起始日期，可选；按 date 过滤。"),
            param("end_date", "string", "结束日期，可选；按 date 过滤。"),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。", None, "000001.SZ"),
            field("symbol", "string", "交易所原始六位代码。", None, "000001"),
            field("date", "date/string", "日期。", "DATE", "20260615"),
            field("pe_ttm", "number", "PE(TTM)。", "PETTM", 4.98),
            field("pe_percentile", "number", "PE 百分位。", "PEBFW", 41.21),
            field("pb_mrq", "number", "PB(MRQ)。", "PBMRQ", 0.46),
            field("pb_percentile", "number", "PB 百分位。", "PBBFW", 5.7),
            field("pcf_ttm", "number", "市现率(TTM)。", "PCFOCFTTM", 1.13),
            field("pcf_percentile", "number", "市现率百分位。", "PCFBFW", 42.69),
            field("ps_ttm", "number", "市销率(TTM)。", "PSTTM", 1.61),
            field("ps_percentile", "number", "市销率百分位。", "PSBFW", 64.66),
            field("peg", "number", "PEG。", "PEG", 0.1),
            field("float_market_cap", "number", "流通市值。", "AVGMVM", 214625959936.0),
            field("total_market_cap", "number", "总市值。", "ALIQMV", 214629466112.0),
        ),
        body_template={
            "ReqId": "200191",
            "Code": "{code}|{market_id}",
            "BeginDate": "{begin_date}",
            "EndDate": "{end_date_for_request}",
            "Page": "0",
            "PageSize": "{count}",
            "modname": "mod_gpsj.dll",
        },
        main_table_index=1,
    ),
    "stock_valuation_series_tdx": F10InterfaceSpec(
        name="stock_valuation_series_tdx",
        display_name_zh="单指标估值序列",
        category="F10数据",
        summary_zh="查询单个估值指标的历史序列和百分位，适合画 PE/PB/PS/PCF 曲线。",
        entry="HQServ.hq_nlp_gpsj",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS
        + (
            param("metric", "string", "指标：pe、pb、pcf、ps；默认 pe。", default="pe"),
            param("start_date", "string", "起始日期，可选；按 date 过滤。"),
            param("end_date", "string", "结束日期，可选；按 date 过滤。"),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "日期。", "DATE", "20260601"),
            field("metric", "string", "指标。", "{metric}", "pe"),
            field("value", "number", "指标值。", "value", 4.95),
            field("percentile", "number", "历史百分位。", "bfw", 37.49),
        ),
        function_param="metric",
        function_default="pe",
        function_aliases={"pe": "0", "pb": "1", "pcf": "2", "ps": "3"},
        body_template={
            "ReqId": "200192",
            "Code": "{code}|{market_id}",
            "BeginDate": "{begin_date}",
            "EndDate": "{end_date_for_request}",
            "Type": "{function}",
            "Page": "-1",
            "PageSize": "{count}",
            "modname": "mod_gpsj.dll",
        },
        main_table_index=1,
    ),
    "stock_valuation_band_tdx": F10InterfaceSpec(
        name="stock_valuation_band_tdx",
        display_name_zh="PE/PB估值通道",
        category="F10数据",
        summary_zh="查询 PE/PB Band 估值通道数据，用于绘制估值带图。",
        entry="HQServ.hq_nlp_gpsj",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS
        + (
            param("metric", "string", "指标：pe 或 pb；默认 pe。", default="pe"),
            param("start_date", "string", "起始日期，可选；按 date 过滤。"),
            param("end_date", "string", "结束日期，可选；按 date 过滤。"),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("date", "date/string", "日期。", "N001"),
            field("band_value_1", "number", "当前 PE 或 PB 指标值。", "N002"),
            field("band_value_2", "number", "通道辅助值 2，源端用于绘制 Band。", "N003"),
            field("band_value_3", "number", "通道辅助值 3，源端用于绘制 Band。", "N004"),
            field("total_count", "integer", "当前统计区间样本数。", "TotalNum"),
            field("min_value", "number", "当前统计区间最小值。", "Min"),
            field("mid_value", "number", "当前统计区间中位值。", "Mid"),
        ),
        function_param="metric",
        function_default="pe",
        function_aliases={"pe": "0", "pb": "1"},
        body_template={
            "ReqId": "200124",
            "code": "{code}",
            "setcode": "{market_id}",
            "sjfw": "1Y",
            "sdate": "{start_date_for_request}",
            "edate": "{end_date_text}",
            "zb": "{function}",
            "hqzq": "0",
            "cwppgz": 1,
            "jglx": 0,
            "Page": 1,
            "PageSize": "{count}",
            "modname": "mod_gpsj.dll",
        },
    ),
    "stock_return_calendar_tdx": F10InterfaceSpec(
        name="stock_return_calendar_tdx",
        display_name_zh="月度年度涨跌幅",
        category="F10数据",
        summary_zh="按年份汇总股票 1 至 12 月涨跌幅和全年涨跌幅，用于查看历史收益日历。",
        entry="HQServ.hq_nlp_gpsj",
        body_kind="hq",
        params=COMMON_STOCK_PARAMS + (param("year", "string", "年份，可选；不传返回全部可用年份。"),),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("symbol", "string", "交易所原始六位代码。"),
            field("year", "string", "年份。", "N001", "2026"),
            field("month_1_pct", "number", "1 月涨跌幅，单位：%。", "N002", -5.0833),
            field("month_2_pct", "number", "2 月涨跌幅，单位：%。", "N003", 0.6463),
            field("month_3_pct", "number", "3 月涨跌幅，单位：%。", "N004", 1.6514),
            field("month_4_pct", "number", "4 月涨跌幅，单位：%。", "N005", 3.7004),
            field("month_5_pct", "number", "5 月涨跌幅，单位：%。", "N006", -4.8738),
            field("month_6_pct", "number", "6 月涨跌幅，单位：%。", "N007", 3.3852),
            field("month_7_pct", "number", "7 月涨跌幅，单位：%。", "N008", 0.0),
            field("month_8_pct", "number", "8 月涨跌幅，单位：%。", "N009", 0.0),
            field("month_9_pct", "number", "9 月涨跌幅，单位：%。", "N010", 0.0),
            field("month_10_pct", "number", "10 月涨跌幅，单位：%。", "N011", 0.0),
            field("month_11_pct", "number", "11 月涨跌幅，单位：%。", "N012", 0.0),
            field("month_12_pct", "number", "12 月涨跌幅，单位：%。", "N013", 0.0),
            field("year_pct", "number", "年度涨跌幅，单位：%。", "N014", -0.964),
        ),
        body_template={"ReqId": "200135", "setcode": "{market_id}", "code": "{code}", "Page": -1, "PageSize": "{count}", "modname": "mod_gpsj.dll"},
    ),
    "stock_market_rankings_tdx": F10InterfaceSpec(
        name="stock_market_rankings_tdx",
        display_name_zh="排名明细",
        category="F10数据",
        summary_zh="查询市场或行业排名明细。",
        entry="CWServ.tdxf10_gg_zxts_rqpm",
        body_kind="params",
        params=COMMON_STOCK_PARAMS
        + (
            param(
                "scope",
                "string",
                "范围：market 全市场排名，industry 为传入股票所属行业内排名；默认 market。建议单只股票调用。",
                default="market",
            ),
            COUNT_PARAM,
        ),
        fields=(
            field("instrument_id", "string", "AxData 统一证券代码，例如 000001.SZ。"),
            field("rank", "integer", "排名。", "pm"),
            field("rank_change", "number", "排名变化。", "prepm"),
            field("symbol", "string", "股票代码。", ("zqdm", "gpdm")),
            field("name", "string", "证券简称。", "zqjc"),
            field("exchange", "string", "AxData 交易所代码：SSE、SZSE 或 BSE。"),
            field("market_code", "string", "市场代码。", "sc"),
            field("updated_time", "datetime/string", "更新时间。", "modtime"),
        ),
        function_param="scope",
        function_default="market",
        function_aliases={"market": "scpmdela", "industry": "hypmdelat"},
        body_template={"Params": ["{code}", "{function}"]},
        main_table_index=1,
    ),
}


