"""TDX extended-asset source request interface catalog."""

from __future__ import annotations

from axdata_core.sources.base import RequestExample, RequestField, RequestParameter, SourceRequestInterface


COMMON_CACHE_PARAMETERS = (
    RequestParameter(
        name="tdx_root",
        dtype="string",
        required=False,
        description="Optional local TDX installation or hq_cache directory path.",
        description_zh=(
            "本机通达信目录（可选，高级）：用于读取本机通达信扩展行情代码表；"
            "不填时自动发现。远程调用时指 API 服务器上的通达信目录，不是浏览器所在电脑。"
        ),
    ),
)

COMMON_LIST_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=False,
        description="Instrument code filter. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码过滤；可传单个、列表或英文逗号分隔字符串。",
    ),
    RequestParameter(
        name="exchange",
        dtype="string/list",
        required=False,
        description="Exchange or asset venue filter. Use all or omit for all.",
        description_zh="交易所或资产场所过滤；不传或 all 表示全部。",
    ),
    RequestParameter(
        name="name",
        dtype="string/list",
        required=False,
        description="Name or product keyword filter.",
        description_zh="名称、品种或市场关键词过滤。",
    ),
    RequestParameter(
        name="limit",
        dtype="integer",
        required=False,
        default=1000,
        description="Maximum rows returned. Default 1000.",
        description_zh="返回前多少行，默认 1000。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

COMMON_INSTRUMENT_FIELDS = (
    RequestField(
        name="instrument_id",
        dtype="string",
        description="AxData extended-asset instrument id.",
        description_zh="AxData 扩展资产统一代码。",
    ),
    RequestField(
        name="symbol",
        dtype="string",
        description="Source instrument code.",
        description_zh="源端品种代码。",
    ),
    RequestField(
        name="asset_type",
        dtype="string",
        description="Asset type: futures, option, fund, bond, fx, macro, or other.",
        description_zh="资产类型：futures 期货、option 期权、fund 基金、bond 债券、fx 外汇、macro 宏观。",
    ),
    RequestField(
        name="exchange",
        dtype="string",
        description="Normalized exchange or asset venue.",
        description_zh="归一后的交易所或资产场所。",
    ),
    RequestField(
        name="market_name",
        dtype="string",
        description="Market name shown by the local extended-asset catalog.",
        description_zh="本机扩展资产目录中的市场名称。",
    ),
    RequestField(
        name="market_group",
        dtype="string",
        description="Asset group shown by the local extended-asset catalog.",
        description_zh="本机扩展资产目录中的分组名称。",
    ),
)

PRODUCT_FIELDS = (
    RequestField(name="product_code", dtype="string", description="Product code.", description_zh="品种代码。"),
    RequestField(name="product_name", dtype="string", description="Product name.", description_zh="品种名称。"),
    RequestField(name="contract_month", dtype="string", description="Contract month, YYYYMM.", description_zh="合约月份，YYYYMM。"),
)

COMMON_CODE_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=True,
        description="Instrument code. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码；可传单个、列表或英文逗号分隔字符串。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

COMMON_KLINE_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=True,
        description="Instrument code. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码；可传单个、列表或英文逗号分隔字符串。",
    ),
    RequestParameter(
        name="period",
        dtype="string",
        required=False,
        default="day",
        description="K-line period.",
        description_zh="K线周期：1m、5m、15m、30m、60m、day、week、month、quarter、year；默认 day。",
    ),
    RequestParameter(
        name="limit",
        dtype="integer",
        required=False,
        default=30,
        description="Maximum bars returned per instrument. Default 30.",
        description_zh="每个品种返回前多少根，默认 30。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

COMMON_INTRADAY_HISTORY_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=True,
        description="Instrument code. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码；可传单个、列表或英文逗号分隔字符串。",
    ),
    RequestParameter(
        name="trade_date",
        dtype="date/string",
        required=True,
        description="Trading date, YYYYMMDD or YYYY-MM-DD.",
        description_zh="交易日期，YYYYMMDD 或 YYYY-MM-DD。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

COMMON_TRADES_HISTORY_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=True,
        description="Instrument code. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码；可传单个、列表或英文逗号分隔字符串。",
    ),
    RequestParameter(
        name="trade_date",
        dtype="date/string",
        required=True,
        description="Trading date, YYYYMMDD or YYYY-MM-DD.",
        description_zh="交易日期，YYYYMMDD 或 YYYY-MM-DD。",
    ),
    RequestParameter(
        name="limit",
        dtype="integer",
        required=False,
        default=120,
        description="Maximum trades returned per instrument. Default 120 latest rows; when all=true, it is an optional total cap.",
        description_zh="每个品种返回多少笔，默认返回最新一页的 120 笔；all=true 时作为总数量上限。",
    ),
    RequestParameter(
        name="all",
        dtype="boolean",
        required=False,
        default=False,
        description="Whether to page through all available trades and return rows in chronological order. Default false.",
        description_zh="是否自动翻页取完整逐笔，并按时间顺序返回；默认 false。",
    ),
    RequestParameter(
        name="page_size",
        dtype="integer",
        required=False,
        default=1800,
        description="Per-page trade count used only when all=true. Default 1800.",
        description_zh="all=true 时每页请求笔数，默认 1800。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

COMMON_TRADES_TODAY_PARAMETERS = (
    RequestParameter(
        name="code",
        dtype="string/list",
        required=True,
        description="Instrument code. Multiple codes can be a list or comma-separated string.",
        description_zh="品种代码；可传单个、列表或英文逗号分隔字符串。",
    ),
    RequestParameter(
        name="limit",
        dtype="integer",
        required=False,
        default=120,
        description="Maximum trades returned per instrument. Default 120 latest rows; when all=true, it is an optional total cap.",
        description_zh="每个品种返回多少笔，默认返回最新一页的 120 笔；all=true 时作为总数量上限。",
    ),
    RequestParameter(
        name="all",
        dtype="boolean",
        required=False,
        default=False,
        description="Whether to page through all available trades and return rows in chronological order. Default false.",
        description_zh="是否自动翻页取完整逐笔，并按时间顺序返回；默认 false。",
    ),
    RequestParameter(
        name="page_size",
        dtype="integer",
        required=False,
        default=1800,
        description="Per-page trade count used only when all=true. Default 1800.",
        description_zh="all=true 时每页请求笔数，默认 1800。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

OPTION_CHAIN_PARAMETERS = (
    RequestParameter(
        name="product_code",
        dtype="string/list",
        required=False,
        description="Option product code filter, such as AP.",
        description_zh="期权品种代码过滤，例如 AP；不传则按其它参数筛选。",
    ),
    RequestParameter(
        name="contract_month",
        dtype="string/list",
        required=False,
        description="Contract month filter, YYYYMM.",
        description_zh="合约月份过滤，YYYYMM。",
    ),
    RequestParameter(
        name="exchange",
        dtype="string/list",
        required=False,
        description="Exchange filter. Omit for all.",
        description_zh="交易所过滤；不传表示全部。",
    ),
    RequestParameter(
        name="limit",
        dtype="integer",
        required=False,
        default=100,
        description="Maximum option contracts requested before grouping. Default 100.",
        description_zh="拼 T 型报价前最多请求多少个期权合约，默认 100。",
    ),
    *COMMON_CACHE_PARAMETERS,
)

_LEVEL_ZH = {1: "一", 2: "二", 3: "三", 4: "四", 5: "五"}

QUOTE_LEVEL_FIELDS = tuple(
    field
    for level in range(1, 6)
    for field in (
        RequestField(
            name=f"bid{level}_price",
            dtype="number",
            description=f"Bid level {level} price when available.",
            description_zh=f"买{_LEVEL_ZH[level]}价；源端有值时返回。",
        ),
        RequestField(
            name=f"bid{level}_volume",
            dtype="integer",
            description=f"Bid level {level} volume when available.",
            description_zh=f"买{_LEVEL_ZH[level]}量；源端有值时返回。",
        ),
        RequestField(
            name=f"ask{level}_price",
            dtype="number",
            description=f"Ask level {level} price when available.",
            description_zh=f"卖{_LEVEL_ZH[level]}价；源端有值时返回。",
        ),
        RequestField(
            name=f"ask{level}_volume",
            dtype="integer",
            description=f"Ask level {level} volume when available.",
            description_zh=f"卖{_LEVEL_ZH[level]}量；源端有值时返回。",
        ),
    )
)

QUOTE_FIELDS = (
    RequestField(name="instrument_id", dtype="string", description="AxData instrument id.", description_zh="AxData 统一品种代码。"),
    RequestField(name="symbol", dtype="string", description="Source instrument code.", description_zh="源端品种代码。"),
    RequestField(name="exchange", dtype="string", description="Exchange or asset venue.", description_zh="交易所或资产场所。"),
    RequestField(name="name", dtype="string", description="Instrument name when known.", description_zh="可确认时返回品种名称。"),
    RequestField(name="trade_date", dtype="date/string", description="Quote date.", description_zh="行情日期。"),
    RequestField(name="last_price", dtype="number", description="Latest price/value.", description_zh="最新价或最新值。"),
    RequestField(name="pre_close", dtype="number", description="Previous close/value.", description_zh="昨收或上期值。"),
    RequestField(name="pre_settlement", dtype="number", description="Previous settlement when available.", description_zh="昨结算；源端有值时返回。"),
    RequestField(name="open", dtype="number", description="Open price/value.", description_zh="开盘价或本期值。"),
    RequestField(name="high", dtype="number", description="High price/value.", description_zh="最高价或本期高值。"),
    RequestField(name="low", dtype="number", description="Low price/value.", description_zh="最低价或本期低值。"),
    RequestField(name="settlement", dtype="number", description="Settlement when available.", description_zh="结算价；源端有值时返回。"),
    RequestField(name="average_price", dtype="number", description="Average price when available.", description_zh="均价；源端有值时返回。"),
    RequestField(name="volume", dtype="integer", description="Volume using the source quote unit.", description_zh="成交量，按源端行情口径返回。"),
    RequestField(name="amount", dtype="number", description="Turnover amount when available.", description_zh="成交额；源端有值时返回。"),
    RequestField(name="open_interest", dtype="integer", description="Open interest when available.", description_zh="持仓量；源端有值时返回。"),
    RequestField(name="open_interest_change", dtype="integer", description="Open interest change when available.", description_zh="持仓变化；源端有值时返回。"),
    RequestField(name="inside_volume", dtype="integer", description="Inside volume when available.", description_zh="内盘量；源端有值时返回。"),
    RequestField(name="outside_volume", dtype="integer", description="Outside volume when available.", description_zh="外盘量；源端有值时返回。"),
    *QUOTE_LEVEL_FIELDS,
)

KLINE_FIELDS = (
    RequestField(name="instrument_id", dtype="string", description="AxData instrument id.", description_zh="AxData 统一品种代码。"),
    RequestField(name="symbol", dtype="string", description="Source instrument code.", description_zh="源端品种代码。"),
    RequestField(name="exchange", dtype="string", description="Exchange or asset venue.", description_zh="交易所或资产场所。"),
    RequestField(name="name", dtype="string", description="Instrument name when known.", description_zh="可确认时返回品种名称。"),
    RequestField(name="trade_time", dtype="date/string", description="Bar date or time.", description_zh="K线日期或时间。"),
    RequestField(name="period", dtype="string", description="K-line period.", description_zh="K线周期。"),
    RequestField(name="open", dtype="number", description="Open price/value.", description_zh="开盘价或本期值。"),
    RequestField(name="high", dtype="number", description="High price/value.", description_zh="最高价或本期高值。"),
    RequestField(name="low", dtype="number", description="Low price/value.", description_zh="最低价或本期低值。"),
    RequestField(name="close", dtype="number", description="Close price/value.", description_zh="收盘价或本期值。"),
    RequestField(name="volume", dtype="integer", description="K-line volume in source period unit.", description_zh="K线成交量，按源端周期口径返回。"),
    RequestField(name="open_interest", dtype="integer", description="Open interest when available.", description_zh="持仓量；源端有值时返回。"),
    RequestField(name="settlement", dtype="number", description="Settlement when available.", description_zh="结算价；源端有值时返回。"),
)

INTRADAY_FIELDS = (
    RequestField(name="instrument_id", dtype="string", description="AxData instrument id.", description_zh="AxData 统一品种代码。"),
    RequestField(name="symbol", dtype="string", description="Source instrument code.", description_zh="源端品种代码。"),
    RequestField(name="exchange", dtype="string", description="Exchange or asset venue.", description_zh="交易所或资产场所。"),
    RequestField(name="name", dtype="string", description="Instrument name when known.", description_zh="可确认时返回品种名称。"),
    RequestField(name="trade_date", dtype="date/string", description="Trading date for historical intraday data.", description_zh="历史分时的交易日期；当日分时为空。"),
    RequestField(name="time_label", dtype="string", description="Intraday time label.", description_zh="分时时间。"),
    RequestField(name="price", dtype="number", description="Intraday price/value.", description_zh="分时价格或数值。"),
    RequestField(name="average_price", dtype="number", description="Intraday average price/value.", description_zh="分时均价或均值。"),
    RequestField(name="volume", dtype="integer", description="Intraday volume in source unit.", description_zh="分时成交量，按源端口径返回。"),
)

TRADE_FIELDS = (
    RequestField(name="instrument_id", dtype="string", description="AxData instrument id.", description_zh="AxData 统一品种代码。"),
    RequestField(name="symbol", dtype="string", description="Source instrument code.", description_zh="源端品种代码。"),
    RequestField(name="exchange", dtype="string", description="Exchange or asset venue.", description_zh="交易所或资产场所。"),
    RequestField(name="name", dtype="string", description="Instrument name when known.", description_zh="可确认时返回品种名称。"),
    RequestField(name="trade_date", dtype="date/string", description="Trading date.", description_zh="交易日期。"),
    RequestField(name="time_label", dtype="string", description="Trade time with seconds.", description_zh="成交时间，精确到秒。"),
    RequestField(name="price", dtype="number", description="Trade price.", description_zh="成交价。"),
    RequestField(name="volume", dtype="integer", description="Trade volume in source unit.", description_zh="成交量，按源端逐笔口径返回。"),
    RequestField(name="position_change", dtype="integer", description="Open-interest change for the trade when available.", description_zh="仓差；源端有值时返回。"),
    RequestField(name="open_close_type", dtype="string", description="Open/close label inferred from verified trade fields when possible.", description_zh="开平类型；可确认时返回，如双开、双平、多开、空开、多平、空平、多换、空换、换手。"),
)

OPTION_CHAIN_LEVEL_FIELDS = tuple(
    field
    for side, side_zh in (("call", "认购"), ("put", "认沽"))
    for level in range(1, 6)
    for field in (
        RequestField(
            name=f"{side}_bid{level}_price",
            dtype="number",
            description=f"{side} bid level {level} price.",
            description_zh=f"{side_zh}买{_LEVEL_ZH[level]}价。",
        ),
        RequestField(
            name=f"{side}_bid{level}_volume",
            dtype="integer",
            description=f"{side} bid level {level} volume.",
            description_zh=f"{side_zh}买{_LEVEL_ZH[level]}量。",
        ),
        RequestField(
            name=f"{side}_ask{level}_price",
            dtype="number",
            description=f"{side} ask level {level} price.",
            description_zh=f"{side_zh}卖{_LEVEL_ZH[level]}价。",
        ),
        RequestField(
            name=f"{side}_ask{level}_volume",
            dtype="integer",
            description=f"{side} ask level {level} volume.",
            description_zh=f"{side_zh}卖{_LEVEL_ZH[level]}量。",
        ),
    )
)

OPTION_CHAIN_FIELDS = (
    RequestField(name="product_code", dtype="string", description="Option product code.", description_zh="期权品种代码。"),
    RequestField(name="product_name", dtype="string", description="Option product name.", description_zh="期权品种名称。"),
    RequestField(name="exchange", dtype="string", description="Exchange.", description_zh="交易所。"),
    RequestField(name="contract_month", dtype="string", description="Contract month, YYYYMM.", description_zh="合约月份，YYYYMM。"),
    RequestField(name="strike_price", dtype="number", description="Strike price.", description_zh="行权价。"),
    RequestField(name="call_instrument_id", dtype="string", description="Call option instrument id.", description_zh="认购合约代码。"),
    RequestField(name="call_symbol", dtype="string", description="Call option source code.", description_zh="认购源端代码。"),
    RequestField(name="call_last_price", dtype="number", description="Call last price.", description_zh="认购最新价。"),
    RequestField(name="call_volume", dtype="integer", description="Call volume.", description_zh="认购成交量。"),
    RequestField(name="call_open_interest", dtype="integer", description="Call open interest.", description_zh="认购持仓量。"),
    RequestField(name="put_instrument_id", dtype="string", description="Put option instrument id.", description_zh="认沽合约代码。"),
    RequestField(name="put_symbol", dtype="string", description="Put option source code.", description_zh="认沽源端代码。"),
    RequestField(name="put_last_price", dtype="number", description="Put last price.", description_zh="认沽最新价。"),
    RequestField(name="put_volume", dtype="integer", description="Put volume.", description_zh="认沽成交量。"),
    RequestField(name="put_open_interest", dtype="integer", description="Put open interest.", description_zh="认沽持仓量。"),
    *OPTION_CHAIN_LEVEL_FIELDS,
)

MACRO_SNAPSHOT_FIELDS = (
    RequestField(name="indicator_id", dtype="string", description="AxData macro indicator id.", description_zh="AxData 宏观指标代码。"),
    RequestField(name="symbol", dtype="string", description="Source indicator code.", description_zh="源端指标代码。"),
    RequestField(name="name", dtype="string", description="Indicator name when known.", description_zh="可确认时返回指标名称。"),
    RequestField(name="indicator_category", dtype="string", description="Indicator category when known.", description_zh="指标分类；可确认时返回。"),
    RequestField(name="value", dtype="number", description="Latest value.", description_zh="最新值。"),
    RequestField(name="period_date", dtype="date/string", description="Value period date.", description_zh="指标期日期。"),
    RequestField(name="pre_value", dtype="number", description="Previous value.", description_zh="上一期值。"),
    RequestField(name="unit", dtype="string", description="Unit when verified.", description_zh="单位；未确认时为空。"),
    RequestField(name="frequency", dtype="string", description="Publishing frequency when verified.", description_zh="发布频度；未确认时为空。"),
)

MACRO_SERIES_FIELDS = (
    RequestField(name="indicator_id", dtype="string", description="AxData macro indicator id.", description_zh="AxData 宏观指标代码。"),
    RequestField(name="symbol", dtype="string", description="Source indicator code.", description_zh="源端指标代码。"),
    RequestField(name="name", dtype="string", description="Indicator name when known.", description_zh="可确认时返回指标名称。"),
    RequestField(name="period_date", dtype="date/string", description="Value period date.", description_zh="指标期日期。"),
    RequestField(name="period", dtype="string", description="Series period.", description_zh="序列周期。"),
    RequestField(name="value", dtype="number", description="Period value.", description_zh="本期值。"),
    RequestField(name="open", dtype="number", description="Open value when available.", description_zh="开值；源端有值时返回。"),
    RequestField(name="high", dtype="number", description="High value when available.", description_zh="高值；源端有值时返回。"),
    RequestField(name="low", dtype="number", description="Low value when available.", description_zh="低值；源端有值时返回。"),
    RequestField(name="unit", dtype="string", description="Unit when verified.", description_zh="单位；未确认时为空。"),
    RequestField(name="frequency", dtype="string", description="Publishing frequency when verified.", description_zh="发布频度；未确认时为空。"),
)


def _interface(
    *,
    name: str,
    display_name_zh: str,
    category: str,
    parameters: tuple[RequestParameter, ...],
    fields: tuple[RequestField, ...],
    example_request_params: dict[str, object],
    example_response: tuple[dict[str, object], ...],
    description: str,
) -> SourceRequestInterface:
    return SourceRequestInterface(
        name=name,
        display_name_zh=display_name_zh,
        source_code="tdx_ext",
        source_name_zh="通达信",
        category=category,
        request_mode="source_request",
        first_stage_strategy="临时读取本机扩展资产目录，默认不入库。",
        source_ability="Local TDX extended asset cache catalog",
        description=description,
        parameters=parameters,
        fields=fields,
        example=RequestExample(
            request={"params": example_request_params, "persist": False},
            response=example_response,
        ),
    )


INTERFACES: dict[str, SourceRequestInterface] = {
    "tdx_ext_markets_tdx": _interface(
        name="tdx_ext_markets_tdx",
        display_name_zh="扩展市场列表",
        category="基础数据",
        parameters=(
            RequestParameter(
                name="asset_type",
                dtype="string/list",
                required=False,
                description="Asset type filter.",
                description_zh="资产类型过滤：futures、option、fund、bond、fx、macro。",
            ),
            RequestParameter(
                name="name",
                dtype="string/list",
                required=False,
                description="Market keyword filter.",
                description_zh="市场名称关键词过滤。",
            ),
            RequestParameter(
                name="limit",
                dtype="integer",
                required=False,
                default=500,
                description="Maximum rows returned. Default 500.",
                description_zh="返回前多少行，默认 500。",
            ),
            *COMMON_CACHE_PARAMETERS,
        ),
        fields=(
            RequestField(name="market_name", dtype="string", description="Market name.", description_zh="市场名称。"),
            RequestField(name="short_name", dtype="string", description="Short market name.", description_zh="市场简称。"),
            RequestField(name="market_group", dtype="string", description="Market group.", description_zh="市场分组。"),
            RequestField(name="asset_type", dtype="string", description="Asset type.", description_zh="资产类型。"),
            RequestField(name="asset_type_zh", dtype="string", description="Chinese asset type.", description_zh="资产类型中文名。"),
        ),
        example_request_params={"asset_type": "futures", "limit": 3},
        example_response=(
            {
                "market_name": "纽约COMEX",
                "short_name": "CO",
                "market_group": "期货现货",
                "asset_type": "futures",
                "asset_type_zh": "期货",
            },
            {
                "market_name": "纽约NYMEX",
                "short_name": "NY",
                "market_group": "期货现货",
                "asset_type": "futures",
                "asset_type_zh": "期货",
            },
            {
                "market_name": "芝加哥CBOT",
                "short_name": "CB",
                "market_group": "期货现货",
                "asset_type": "futures",
                "asset_type_zh": "期货",
            },
        ),
        description="Return the local extended-asset market catalog used by AxData to classify futures, options, funds, bonds, FX, and macro indicators. It does not write raw/staging/core/factor data.",
    ),
    "tdx_ext_instruments_tdx": _interface(
        name="tdx_ext_instruments_tdx",
        display_name_zh="扩展品种列表",
        category="基础数据",
        parameters=(
            RequestParameter(
                name="asset_type",
                dtype="string/list",
                required=False,
                description="Asset type filter.",
                description_zh="资产类型过滤：futures、option、fund、bond、fx、macro。",
            ),
            *COMMON_LIST_PARAMETERS,
        ),
        fields=(
            *COMMON_INSTRUMENT_FIELDS,
            *PRODUCT_FIELDS,
            RequestField(name="contract_type", dtype="string", description="Contract type when known.", description_zh="可确认时返回合约类型。"),
            RequestField(name="option_type", dtype="string", description="Option type when known.", description_zh="期权方向，可确认时为 call 或 put。"),
            RequestField(name="strike_price", dtype="number", description="Option strike price.", description_zh="期权行权价。"),
            RequestField(name="fund_type", dtype="string", description="Fund market type.", description_zh="基金市场类型。"),
            RequestField(name="bond_type", dtype="string", description="Bond market type.", description_zh="债券市场类型。"),
            RequestField(name="base_currency", dtype="string", description="Base currency.", description_zh="基础货币。"),
            RequestField(name="quote_currency", dtype="string", description="Quote currency.", description_zh="报价货币。"),
            RequestField(name="indicator_category", dtype="string", description="Macro indicator category code.", description_zh="宏观指标分类。"),
        ),
        example_request_params={"asset_type": "fx", "limit": 3},
        example_response=(
            {
                "instrument_id": "AUDUSD.FX",
                "symbol": "AUDUSD",
                "asset_type": "fx",
                "exchange": "FX",
                "market_name": "基本汇率",
                "market_group": "环球行情",
                "base_currency": "AUD",
                "quote_currency": "USD",
            },
            {
                "instrument_id": "CNHHKD.FX",
                "symbol": "CNHHKD",
                "asset_type": "fx",
                "exchange": "FX",
                "market_name": "基本汇率",
                "market_group": "环球行情",
                "product_code": None,
                "product_name": None,
                "contract_month": None,
                "contract_type": None,
                "option_type": None,
                "strike_price": None,
                "fund_type": None,
                "bond_type": None,
                "base_currency": "CNH",
                "quote_currency": "HKD",
                "indicator_category": None,
            },
            {
                "instrument_id": "CNHUSD.FX",
                "symbol": "CNHUSD",
                "asset_type": "fx",
                "exchange": "FX",
                "market_name": "基本汇率",
                "market_group": "环球行情",
                "product_code": None,
                "product_name": None,
                "contract_month": None,
                "contract_type": None,
                "option_type": None,
                "strike_price": None,
                "fund_type": None,
                "bond_type": None,
                "base_currency": "CNH",
                "quote_currency": "USD",
                "indicator_category": None,
            },
        ),
        description="Return verified instrument metadata from the local extended-asset catalog. Fields that cannot be confirmed from the local cache are not exposed as formal fields.",
    ),
    "futures_contracts_tdx": _interface(
        name="futures_contracts_tdx",
        display_name_zh="期货合约列表",
        category="期货数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(*COMMON_INSTRUMENT_FIELDS, *PRODUCT_FIELDS, RequestField(name="contract_type", dtype="string", description="Contract type.", description_zh="合约类型。")),
        example_request_params={"exchange": "CFFEX", "limit": 3},
        example_response=(
            {
                "instrument_id": "IC2606.CFFEX",
                "symbol": "IC2606",
                "asset_type": "futures",
                "exchange": "CFFEX",
                "market_name": "中金所期货",
                "market_group": "期货现货",
                "product_code": "IC",
                "product_name": "中证",
                "contract_month": "202606",
                "contract_type": "contract",
            },
            {
                "instrument_id": "IC2607.CFFEX",
                "symbol": "IC2607",
                "asset_type": "futures",
                "exchange": "CFFEX",
                "market_name": "中金所期货",
                "market_group": "期货现货",
                "product_code": "IC",
                "product_name": "中证",
                "contract_month": "202607",
                "contract_type": "contract",
            },
            {
                "instrument_id": "IC2609.CFFEX",
                "symbol": "IC2609",
                "asset_type": "futures",
                "exchange": "CFFEX",
                "market_name": "中金所期货",
                "market_group": "期货现货",
                "product_code": "IC",
                "product_name": "中证",
                "contract_month": "202609",
                "contract_type": "contract",
            },
        ),
        description="Return futures contracts that can be identified from the local extended-asset catalog. This first version is a verified catalog/list interface, not a realtime quote interface.",
    ),
    "option_contracts_tdx": _interface(
        name="option_contracts_tdx",
        display_name_zh="期权合约列表",
        category="期权数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(
            *COMMON_INSTRUMENT_FIELDS,
            *PRODUCT_FIELDS,
            RequestField(name="option_type", dtype="string", description="call or put.", description_zh="期权方向：call 认购，put 认沽。"),
            RequestField(name="strike_price", dtype="number", description="Strike price.", description_zh="行权价。"),
        ),
        example_request_params={"exchange": "CZCE", "limit": 3},
        example_response=(
            {
                "instrument_id": "AP2610-C-10000.CZCE",
                "symbol": "AP2610-C-10000",
                "asset_type": "option",
                "exchange": "CZCE",
                "market_name": "郑州商品期权",
                "market_group": "期权",
                "product_code": "AP",
                "product_name": "苹果",
                "contract_month": "202610",
                "option_type": "call",
                "strike_price": 10000.0,
            },
            {
                "instrument_id": "AP2610-C-10200.CZCE",
                "symbol": "AP2610-C-10200",
                "asset_type": "option",
                "exchange": "CZCE",
                "market_name": "郑州商品期权",
                "market_group": "期权",
                "product_code": "AP",
                "product_name": "苹果",
                "contract_month": "202610",
                "option_type": "call",
                "strike_price": 10200.0,
            },
            {
                "instrument_id": "AP2610-C-6400.CZCE",
                "symbol": "AP2610-C-6400",
                "asset_type": "option",
                "exchange": "CZCE",
                "market_name": "郑州商品期权",
                "market_group": "期权",
                "product_code": "AP",
                "product_name": "苹果",
                "contract_month": "202610",
                "option_type": "call",
                "strike_price": 6400.0,
            },
        ),
        description="Return option contracts with verified direction, strike price, product, and contract month when the local symbol format supports it.",
    ),
    "fund_codes_tdx": _interface(
        name="fund_codes_tdx",
        display_name_zh="基金列表",
        category="基金数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(
            *COMMON_INSTRUMENT_FIELDS,
            RequestField(name="fund_type", dtype="string", description="Fund market type.", description_zh="基金市场类型。"),
            RequestField(name="update_date", dtype="date/string", description="Value update date when available.", description_zh="可确认时返回净值日期。"),
            RequestField(name="nav", dtype="number", description="Fund NAV when available.", description_zh="可确认时返回单位净值。"),
            RequestField(name="accumulated_nav", dtype="number", description="Accumulated NAV when available.", description_zh="可确认时返回累计净值或累计值。"),
        ),
        example_request_params={"code": "159007", "limit": 3},
        example_response=(
            {
                "instrument_id": "159007.FUND",
                "symbol": "159007",
                "asset_type": "fund",
                "exchange": "FUND",
                "market_name": "开放式基金",
                "market_group": "基金理财",
                "fund_type": "开放式基金",
                "update_date": "20260617",
                "nav": 0.7922,
                "accumulated_nav": 20560.32,
            },
        ),
        description="Return non-ETF fund catalog rows from the local extended-asset catalog. ETF trading interfaces remain under ETF data; this interface only exposes verified fund catalog/value fields.",
    ),
    "bond_codes_tdx": _interface(
        name="bond_codes_tdx",
        display_name_zh="债券列表",
        category="债券数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(*COMMON_INSTRUMENT_FIELDS, RequestField(name="bond_type", dtype="string", description="Bond market type.", description_zh="债券市场类型。")),
        example_request_params={"limit": 3},
        example_response=(
            {
                "instrument_id": "10YCDB.BOND",
                "symbol": "10YCDB",
                "asset_type": "bond",
                "exchange": "BOND",
                "market_name": "资金市场",
                "market_group": "其它",
                "bond_type": "资金市场",
            },
            {
                "instrument_id": "10YGB.BOND",
                "symbol": "10YGB",
                "asset_type": "bond",
                "exchange": "BOND",
                "market_name": "资金市场",
                "market_group": "其它",
                "bond_type": "资金市场",
            },
            {
                "instrument_id": "1YCDB.BOND",
                "symbol": "1YCDB",
                "asset_type": "bond",
                "exchange": "BOND",
                "market_name": "资金市场",
                "market_group": "其它",
                "bond_type": "资金市场",
            },
        ),
        description="Return bond-like instruments that can be reliably classified from the local extended-asset catalog. Yield and maturity fields are not exposed until a verified source is available.",
    ),
    "fx_codes_tdx": _interface(
        name="fx_codes_tdx",
        display_name_zh="外汇品种列表",
        category="外汇数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(
            *COMMON_INSTRUMENT_FIELDS,
            RequestField(name="base_currency", dtype="string", description="Base currency.", description_zh="基础货币。"),
            RequestField(name="quote_currency", dtype="string", description="Quote currency.", description_zh="报价货币。"),
        ),
        example_request_params={"code": ["USDCNY", "EURUSD"]},
        example_response=(
            {
                "instrument_id": "EURUSD.FX",
                "symbol": "EURUSD",
                "asset_type": "fx",
                "exchange": "FX",
                "market_name": "基本汇率",
                "market_group": "环球行情",
                "base_currency": "EUR",
                "quote_currency": "USD",
            },
            {
                "instrument_id": "USDCNY.FX",
                "symbol": "USDCNY",
                "asset_type": "fx",
                "exchange": "FX",
                "market_name": "基本汇率",
                "market_group": "环球行情",
                "base_currency": "USD",
                "quote_currency": "CNY",
            },
        ),
        description="Return FX pairs from the local extended-asset catalog. This interface is a catalog endpoint; bid/ask quotes will be added only after realtime source requests are verified.",
    ),
    "macro_indicators_tdx": _interface(
        name="macro_indicators_tdx",
        display_name_zh="宏观指标列表",
        category="宏观数据",
        parameters=COMMON_LIST_PARAMETERS,
        fields=(
            *COMMON_INSTRUMENT_FIELDS,
            RequestField(name="indicator_category", dtype="string", description="Indicator category.", description_zh="指标分类。"),
            RequestField(name="unit", dtype="string", description="Unit when verified.", description_zh="单位；未确认时为空。"),
            RequestField(name="frequency", dtype="string", description="Publishing frequency when verified.", description_zh="发布频度；未确认时为空。"),
        ),
        example_request_params={"limit": 3},
        example_response=(
            {
                "instrument_id": "1_GDP.MACRO",
                "symbol": "1_GDP",
                "asset_type": "macro",
                "exchange": "MACRO",
                "market_name": "宏观指标",
                "market_group": "其它",
                "indicator_category": "1",
                "unit": "亿元",
                "frequency": "年",
            },
            {
                "instrument_id": "2_CPI.MACRO",
                "symbol": "2_CPI",
                "asset_type": "macro",
                "exchange": "MACRO",
                "market_name": "宏观指标",
                "market_group": "其它",
                "indicator_category": "2",
                "unit": "元",
                "frequency": "月",
            },
            {
                "instrument_id": "1_MSR.MACRO",
                "symbol": "1_MSR",
                "asset_type": "macro",
                "exchange": "MACRO",
                "market_name": "宏观指标",
                "market_group": "其它",
                "indicator_category": "1",
                "unit": None,
                "frequency": None,
            },
        ),
        description="Return macro indicator codes from the local extended-asset catalog. Unit and publishing frequency are returned only for indicators that have been verified.",
    ),
}

INTERFACES.update(
    {
        "futures_realtime_snapshot_tdx": _interface(
            name="futures_realtime_snapshot_tdx",
            display_name_zh="期货实时快照",
            category="期货数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=QUOTE_FIELDS,
            example_request_params={"code": "IC2607.CFFEX"},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": "20260703",
                    "last_price": 8688.799805,
                    "pre_close": 8670.200195,
                    "pre_settlement": 8670.200195,
                    "open": 8671.200195,
                    "high": 8805.0,
                    "low": 8592.200195,
                    "settlement": 8718.799805,
                    "average_price": 8697.435547,
                    "volume": 45511,
                    "amount": 79166021632.0,
                    "open_interest": 60372,
                    "open_interest_change": 42173,
                    "inside_volume": 23107,
                    "outside_volume": 22404,
                    "bid1_price": 8688.0,
                    "bid1_volume": 9,
                    "ask1_price": 8693.799805,
                    "ask1_volume": 1,
                },
            ),
            description="Request realtime futures quote snapshots. The quote keeps futures-specific settlement and open-interest fields when the source returns them.",
        ),
        "futures_kline_tdx": _interface(
            name="futures_kline_tdx",
            display_name_zh="期货K线",
            category="期货数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=KLINE_FIELDS,
            example_request_params={"code": "IC2607.CFFEX", "period": "day", "limit": 3},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_time": "20260703",
                    "period": "day",
                    "open": 8671.200195,
                    "high": 8805.0,
                    "low": 8592.200195,
                    "close": 8688.799805,
                    "volume": 45511,
                    "open_interest": 60372,
                    "settlement": 8718.799805,
                },
            ),
            description="Request futures K-line bars. Volume follows the source period unit; settlement and open interest are returned when present.",
        ),
        "futures_intraday_today_tdx": _interface(
            name="futures_intraday_today_tdx",
            display_name_zh="期货当日分时",
            category="期货数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "IC2607.CFFEX"},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": None,
                    "time_label": "09:30",
                    "price": 8672.800781,
                    "average_price": 8682.989258,
                    "volume": 1593,
                },
            ),
            description="Request current-day futures intraday points. The returned timeline follows the source trading session for the instrument.",
        ),
        "futures_intraday_history_tdx": _interface(
            name="futures_intraday_history_tdx",
            display_name_zh="期货历史分时",
            category="期货数据",
            parameters=COMMON_INTRADAY_HISTORY_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "IC2607.CFFEX", "trade_date": "20260703"},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": "20260703",
                    "time_label": "09:30",
                    "price": 8672.800781,
                    "average_price": 8682.989258,
                    "volume": 1593,
                },
            ),
            description="Request historical futures intraday points for one trading date.",
        ),
        "futures_trades_history_tdx": _interface(
            name="futures_trades_history_tdx",
            display_name_zh="期货历史逐笔",
            category="期货数据",
            parameters=COMMON_TRADES_HISTORY_PARAMETERS,
            fields=TRADE_FIELDS,
            example_request_params={"code": "IC2607.CFFEX", "trade_date": "20260703", "limit": 3},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": "20260703",
                    "time_label": "14:59:58",
                    "price": 8688.0,
                    "volume": 1,
                    "position_change": 0,
                    "open_close_type": "空换",
                },
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": "20260703",
                    "time_label": "14:59:58",
                    "price": 8688.8,
                    "volume": 1,
                    "position_change": 0,
                    "open_close_type": "多换",
                },
            ),
            description="Request historical futures trade details. By default it returns the latest page; set all=true to page through the full available list and return it in chronological order.",
        ),
        "futures_trades_today_tdx": _interface(
            name="futures_trades_today_tdx",
            display_name_zh="期货当日逐笔",
            category="期货数据",
            parameters=COMMON_TRADES_TODAY_PARAMETERS,
            fields=TRADE_FIELDS,
            example_request_params={"code": "IC2607.CFFEX", "limit": 3},
            example_response=(
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": None,
                    "time_label": "14:59:58",
                    "price": 8688.0,
                    "volume": 1,
                    "position_change": 0,
                    "open_close_type": "空换",
                },
                {
                    "instrument_id": "IC2607.CFFEX",
                    "symbol": "IC2607",
                    "exchange": "CFFEX",
                    "name": "中证",
                    "trade_date": None,
                    "time_label": "14:59:58",
                    "price": 8688.8,
                    "volume": 1,
                    "position_change": 0,
                    "open_close_type": "多换",
                },
            ),
            description="Request current-day futures trade details. By default it returns the latest page; set all=true to page through the full available list and return it in chronological order.",
        ),
        "option_realtime_snapshot_tdx": _interface(
            name="option_realtime_snapshot_tdx",
            display_name_zh="期权实时快照",
            category="期权数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=QUOTE_FIELDS,
            example_request_params={"code": "AP2610-C-10000.CZCE"},
            example_response=(
                {
                    "instrument_id": "AP2610-C-10000.CZCE",
                    "symbol": "AP2610-C-10000",
                    "exchange": "CZCE",
                    "name": "苹果",
                    "trade_date": "20260703",
                    "last_price": 11.5,
                    "pre_close": 7.0,
                    "pre_settlement": 7.0,
                    "open": 12.5,
                    "high": 13.5,
                    "low": 11.0,
                    "settlement": 12.5,
                    "average_price": 12.344191,
                    "volume": 568,
                    "amount": 70000.0,
                    "open_interest": 8672,
                    "open_interest_change": 677,
                    "inside_volume": 306,
                    "outside_volume": 262,
                    "bid1_price": 11.0,
                    "bid1_volume": 1,
                    "ask1_price": 11.5,
                    "ask1_volume": 2,
                },
            ),
            description="Request realtime option quote snapshots. Greeks and implied volatility are not exposed unless a verified source field is available.",
        ),
        "option_chain_tdx": _interface(
            name="option_chain_tdx",
            display_name_zh="期权T型报价",
            category="期权数据",
            parameters=OPTION_CHAIN_PARAMETERS,
            fields=OPTION_CHAIN_FIELDS,
            example_request_params={"product_code": "AP", "contract_month": "202610", "limit": 3},
            example_response=(
                {
                    "product_code": "AP",
                    "product_name": "苹果",
                    "exchange": "CZCE",
                    "contract_month": "202610",
                    "strike_price": 6400.0,
                    "call_instrument_id": "AP2610-C-6400.CZCE",
                    "call_symbol": "AP2610-C-6400",
                    "call_last_price": None,
                    "call_bid1_price": 832.5,
                    "call_ask1_price": 1301.5,
                    "call_volume": 0,
                    "call_open_interest": 7,
                    "put_instrument_id": "AP2610-P-6400.CZCE",
                    "put_symbol": "AP2610-P-6400",
                    "put_last_price": 22.5,
                    "put_bid1_price": 19.0,
                    "put_ask1_price": 24.0,
                    "put_volume": 65,
                    "put_open_interest": 201,
                },
            ),
            description="Build a T-shaped option quote table from verified option contracts and realtime snapshots. It does not expose Greeks or implied volatility before those fields are verified.",
        ),
        "option_kline_tdx": _interface(
            name="option_kline_tdx",
            display_name_zh="期权K线",
            category="期权数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=KLINE_FIELDS,
            example_request_params={"code": "AP2610-C-10000.CZCE", "period": "day", "limit": 3},
            example_response=(
                {
                    "instrument_id": "AP2610-C-10000.CZCE",
                    "symbol": "AP2610-C-10000",
                    "exchange": "CZCE",
                    "name": "苹果",
                    "trade_time": "20260703",
                    "period": "day",
                    "open": 12.5,
                    "high": 13.5,
                    "low": 11.0,
                    "close": 11.5,
                    "volume": 568,
                    "open_interest": 8672,
                    "settlement": 12.5,
                },
            ),
            description="Request option K-line bars. Volume follows the source period unit; settlement and open interest are returned when present.",
        ),
        "option_intraday_today_tdx": _interface(
            name="option_intraday_today_tdx",
            display_name_zh="期权当日分时",
            category="期权数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "AP2610-C-10000.CZCE"},
            example_response=(
                {
                    "instrument_id": "AP2610-C-10000.CZCE",
                    "symbol": "AP2610-C-10000",
                    "exchange": "CZCE",
                    "name": "苹果",
                    "trade_date": None,
                    "time_label": "09:00",
                    "price": 7.0,
                    "average_price": 7.0,
                    "volume": 0,
                },
            ),
            description="Request current-day option intraday points.",
        ),
        "option_intraday_history_tdx": _interface(
            name="option_intraday_history_tdx",
            display_name_zh="期权历史分时",
            category="期权数据",
            parameters=COMMON_INTRADAY_HISTORY_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "AP2610-C-10000.CZCE", "trade_date": "20260703"},
            example_response=(
                {
                    "instrument_id": "AP2610-C-10000.CZCE",
                    "symbol": "AP2610-C-10000",
                    "exchange": "CZCE",
                    "name": "苹果",
                    "trade_date": "20260703",
                    "time_label": "09:00",
                    "price": 7.0,
                    "average_price": 7.0,
                    "volume": 0,
                },
            ),
            description="Request historical option intraday points for one trading date.",
        ),
        "fund_nav_tdx": _interface(
            name="fund_nav_tdx",
            display_name_zh="基金净值",
            category="基金数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=(
                RequestField(name="fund_id", dtype="string", description="AxData fund id.", description_zh="AxData 基金代码。"),
                RequestField(name="symbol", dtype="string", description="Fund code.", description_zh="基金代码。"),
                RequestField(name="fund_type", dtype="string", description="Fund type.", description_zh="基金类型。"),
                RequestField(name="name", dtype="string", description="Fund name when known.", description_zh="可确认时返回基金名称。"),
                RequestField(name="update_date", dtype="date/string", description="NAV update date.", description_zh="净值日期。"),
                RequestField(name="nav", dtype="number", description="Net asset value.", description_zh="单位净值。"),
                RequestField(name="accumulated_nav", dtype="number", description="Accumulated NAV/value.", description_zh="累计净值或累计值。"),
            ),
            example_request_params={"code": "159007"},
            example_response=(
                {
                    "fund_id": "159007.FUND",
                    "symbol": "159007",
                    "fund_type": "开放式基金",
                    "name": None,
                    "update_date": "20260617",
                    "nav": 0.7922,
                    "accumulated_nav": 20560.32,
                },
            ),
            description="Return verified fund NAV fields from the local extended-asset value cache. ETF trading data remains under ETF data.",
        ),
        "fund_nav_series_tdx": _interface(
            name="fund_nav_series_tdx",
            display_name_zh="基金净值走势",
            category="基金数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=KLINE_FIELDS,
            example_request_params={"code": "159007", "period": "day", "limit": 3},
            example_response=(
                {
                    "instrument_id": "159007.FUND",
                    "symbol": "159007",
                    "exchange": "FUND",
                    "name": None,
                    "trade_time": "20260618",
                    "period": "day",
                    "open": 0.7922,
                    "high": 0.7922,
                    "low": 0.7922,
                    "close": 0.7922,
                    "volume": 0,
                    "open_interest": 0,
                    "settlement": None,
                },
            ),
            description="Request fund value series from the extended-asset K-line source. For funds this should be read as net-value movement rather than exchange-traded price.",
        ),
        "bond_realtime_snapshot_tdx": _interface(
            name="bond_realtime_snapshot_tdx",
            display_name_zh="债券实时快照",
            category="债券数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=QUOTE_FIELDS,
            example_request_params={"code": "10YGB.BOND"},
            example_response=(
                {
                    "instrument_id": "10YGB.BOND",
                    "symbol": "10YGB",
                    "exchange": "BOND",
                    "name": None,
                    "trade_date": "20260618",
                    "last_price": 1.724,
                    "pre_close": 1.723,
                    "pre_settlement": None,
                    "open": 1.723,
                    "high": 1.725,
                    "low": 1.72,
                    "settlement": None,
                    "average_price": 1.721908,
                    "volume": 250,
                    "amount": 0.0,
                    "open_interest": 0,
                    "open_interest_change": 0,
                    "inside_volume": 191,
                    "outside_volume": 59,
                },
            ),
            description="Request bond-like realtime snapshots. Yield and remaining maturity are not exposed because they are not verified source fields in this interface.",
        ),
        "bond_kline_tdx": _interface(
            name="bond_kline_tdx",
            display_name_zh="债券K线",
            category="债券数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=KLINE_FIELDS,
            example_request_params={"code": "10YGB.BOND", "period": "day", "limit": 3},
            example_response=(
                {
                    "instrument_id": "10YGB.BOND",
                    "symbol": "10YGB",
                    "exchange": "BOND",
                    "name": None,
                    "trade_time": "20260618",
                    "period": "day",
                    "open": 1.723,
                    "high": 1.725,
                    "low": 1.72,
                    "close": 1.724,
                    "volume": 250,
                    "open_interest": 0,
                    "settlement": None,
                },
            ),
            description="Request bond-like K-line bars. Price/value semantics follow the source instrument; yield-only fields are not added unless verified.",
        ),
        "fx_realtime_snapshot_tdx": _interface(
            name="fx_realtime_snapshot_tdx",
            display_name_zh="外汇实时快照",
            category="外汇数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=QUOTE_FIELDS,
            example_request_params={"code": "USDCNY.FX"},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": "20260618",
                    "last_price": 6.7658,
                    "pre_close": 6.7575,
                    "pre_settlement": None,
                    "open": 6.7575,
                    "high": 6.77,
                    "low": 6.7573,
                    "settlement": None,
                    "average_price": None,
                    "volume": 0,
                    "amount": 0.0,
                    "open_interest": 0,
                    "open_interest_change": 0,
                    "inside_volume": 0,
                    "outside_volume": 0,
                    "bid1_price": 6.7648,
                    "bid1_volume": 0,
                    "ask1_price": 6.7668,
                    "ask1_volume": 0,
                },
            ),
            description="Request realtime FX snapshots. Bid and ask are returned when available.",
        ),
        "fx_kline_tdx": _interface(
            name="fx_kline_tdx",
            display_name_zh="外汇K线",
            category="外汇数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=KLINE_FIELDS,
            example_request_params={"code": "USDCNY.FX", "period": "day", "limit": 3},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_time": "20260618",
                    "period": "day",
                    "open": 6.7575,
                    "high": 6.77,
                    "low": 6.7573,
                    "close": 6.7658,
                    "volume": 0,
                    "open_interest": 0,
                    "settlement": None,
                },
            ),
            description="Request FX K-line bars.",
        ),
        "fx_intraday_today_tdx": _interface(
            name="fx_intraday_today_tdx",
            display_name_zh="外汇当日分时",
            category="外汇数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "USDCNY.FX"},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": None,
                    "time_label": "05:00",
                    "price": 6.7575,
                    "average_price": 6.7575,
                    "volume": 0,
                },
            ),
            description="Request current-day FX intraday points.",
        ),
        "fx_intraday_history_tdx": _interface(
            name="fx_intraday_history_tdx",
            display_name_zh="外汇历史分时",
            category="外汇数据",
            parameters=COMMON_INTRADAY_HISTORY_PARAMETERS,
            fields=INTRADAY_FIELDS,
            example_request_params={"code": "USDCNY.FX", "trade_date": "20260618"},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": "20260618",
                    "time_label": "05:00",
                    "price": 6.7575,
                    "average_price": 6.7575,
                    "volume": 0,
                },
            ),
            description="Request historical FX intraday points for one trading date.",
        ),
        "fx_trades_history_tdx": _interface(
            name="fx_trades_history_tdx",
            display_name_zh="外汇历史逐笔",
            category="外汇数据",
            parameters=COMMON_TRADES_HISTORY_PARAMETERS,
            fields=TRADE_FIELDS,
            example_request_params={"code": "USDCNY.FX", "trade_date": "20260618", "limit": 3},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": "20260618",
                    "time_label": "00:42:02",
                    "price": 6.7658,
                    "volume": 0,
                    "position_change": 0,
                    "open_close_type": None,
                },
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": "20260618",
                    "time_label": "00:52:02",
                    "price": 6.7671,
                    "volume": 0,
                    "position_change": 0,
                    "open_close_type": None,
                },
            ),
            description="Request historical FX tick details. By default it returns the latest page; set all=true to page through the full available list and return it in chronological order. FX source rows may have zero volume and no open/close label.",
        ),
        "fx_trades_today_tdx": _interface(
            name="fx_trades_today_tdx",
            display_name_zh="外汇当日逐笔",
            category="外汇数据",
            parameters=COMMON_TRADES_TODAY_PARAMETERS,
            fields=TRADE_FIELDS,
            example_request_params={"code": "USDCNY.FX", "limit": 3},
            example_response=(
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": None,
                    "time_label": "00:42:02",
                    "price": 6.7658,
                    "volume": 0,
                    "position_change": 0,
                    "open_close_type": None,
                },
                {
                    "instrument_id": "USDCNY.FX",
                    "symbol": "USDCNY",
                    "exchange": "FX",
                    "name": None,
                    "trade_date": None,
                    "time_label": "00:52:02",
                    "price": 6.7671,
                    "volume": 0,
                    "position_change": 0,
                    "open_close_type": None,
                },
            ),
            description="Request current-day FX tick details. By default it returns the latest page; set all=true to page through the full available list and return it in chronological order.",
        ),
        "macro_indicator_snapshot_tdx": _interface(
            name="macro_indicator_snapshot_tdx",
            display_name_zh="宏观指标快照",
            category="宏观数据",
            parameters=COMMON_CODE_PARAMETERS,
            fields=MACRO_SNAPSHOT_FIELDS,
            example_request_params={"code": "1_GDP.MACRO"},
            example_response=(
                {
                    "indicator_id": "1_GDP.MACRO",
                    "symbol": "1_GDP",
                    "name": None,
                    "indicator_category": None,
                    "value": 1401879.25,
                    "period_date": "20251231",
                    "pre_value": 1348066.25,
                    "unit": "亿元",
                    "frequency": "年",
                },
            ),
            description="Request the latest macro indicator value from the extended-asset source. Unit and publishing frequency are returned only for indicators that have been verified.",
        ),
        "macro_indicator_series_tdx": _interface(
            name="macro_indicator_series_tdx",
            display_name_zh="宏观指标序列",
            category="宏观数据",
            parameters=COMMON_KLINE_PARAMETERS,
            fields=MACRO_SERIES_FIELDS,
            example_request_params={"code": "1_GDP.MACRO", "period": "day", "limit": 3},
            example_response=(
                {
                    "indicator_id": "1_GDP.MACRO",
                    "symbol": "1_GDP",
                    "name": None,
                    "period_date": "20251231",
                    "period": "day",
                    "value": 1401879.25,
                    "open": 1401879.25,
                    "high": 1401879.25,
                    "low": 1401879.25,
                    "unit": "亿元",
                    "frequency": "年",
                },
            ),
            description="Request macro indicator series from the extended-asset source. Unit and publishing frequency are returned only for indicators that have been verified.",
        ),
    }
)
