"""Core schemas, storage, querying, and quality checks for AxData.

The root package keeps the historical ``from axdata_core import ...`` exports,
but resolves them lazily so Provider packages can import narrow submodules such
as ``axdata_core.plugins`` without loading request routers, built-in providers,
or downloader machinery.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORT_MODULES: dict[str, str] = {
    "AxDataPaths": ".paths",
    "DATA_LAYERS": ".paths",
    "MANIFEST_FILE_NAME": ".plugins",
    "MANIFEST_VERSION": ".plugins",
    "PLUGIN_API_VERSION": ".plugins",
    "AssetClass": ".plugins",
    "CollectorSpec": ".plugins",
    "ConfigSchema": ".plugins",
    "DependencySpec": ".plugins",
    "DownloaderMode": ".plugins",
    "DownloaderProfile": ".plugins",
    "FieldSpec": ".plugins",
    "FieldType": ".plugins",
    "InterfaceCollectionSpec": ".plugins",
    "InterfaceSpec": ".plugins",
    "ManifestError": ".plugins",
    "ParameterSpec": ".plugins",
    "ParameterType": ".plugins",
    "PluginStatus": ".plugins",
    "PluginTrustLevel": ".plugins",
    "PluginInfo": ".plugins",
    "PLUGIN_MANIFEST_FILE_NAME": ".plugins",
    "ProviderInfo": ".plugins",
    "ProviderManifest": ".plugins",
    "RequiredConfig": ".plugins",
    "RequestMode": ".plugins",
    "SourceAdapter": ".plugins",
    "SourceProvider": ".plugins",
    "SourceResult": ".plugins",
    "manifest_from_provider": ".plugins",
    "validate_manifest": ".plugins",
    "CollectorRegistry": ".collector_registry",
    "CollectorRegistration": ".collector_registry",
    "CollectorRegistrySnapshot": ".collector_registry",
    "RegisteredCollectorPlugin": ".collector_registry",
    "build_collector_registry": ".collector_registry",
    "InterfaceRegistration": ".provider_registry",
    "ProviderRegistry": ".provider_registry",
    "ProviderRegistrySnapshot": ".provider_registry",
    "RegisteredProvider": ".provider_registry",
    "build_builtin_provider_registry": ".provider_catalog",
    "list_registry_collector_dicts": ".provider_catalog",
    "list_registry_interface_dicts": ".provider_catalog",
    "EXPECTED_OPTIONAL_PROVIDERS": ".plugin_status",
    "TDX_EXT_PROVIDER_ID": ".plugin_status",
    "TDX_PROVIDER_ID": ".plugin_status",
    "expected_provider_statuses": ".plugin_status",
    "install_source_for_provider": ".plugin_status",
    "managed_provider_ids": ".plugin_status",
    "provider_kind_for_provider": ".plugin_status",
    "provider_management_fields": ".plugin_status",
    "provider_status_row": ".plugin_status",
    "uninstall_mode_for_source": ".plugin_status",
    "uninstall_block_reason_for_source": ".plugin_status",
    "PLUGIN_CONFIG_FILE_NAME": ".plugin_config",
    "PLUGIN_CONFIG_VERSION": ".plugin_config",
    "PluginConfig": ".plugin_config",
    "PluginConfigError": ".plugin_config",
    "disable_provider": ".plugin_config",
    "enable_provider": ".plugin_config",
    "load_plugin_config": ".plugin_config",
    "plugin_config_path": ".plugin_config",
    "remove_provider": ".plugin_config",
    "save_plugin_config": ".plugin_config",
    "set_provider_override": ".plugin_config",
    "CollectorError": ".collector_runner",
    "CollectorRunPlan": ".collector_runner",
    "CollectorRunRequest": ".collector_runner",
    "build_collector_run_plan": ".collector_runner",
    "run_collector": ".collector_runner",
    "ACTIVE_RUN_STATUSES": ".collector_scheduler",
    "COLLECTOR_SCHEDULER_FILE_NAME": ".collector_scheduler",
    "FINAL_RUN_STATUSES": ".collector_scheduler",
    "SCHEDULER_STORE_VERSION": ".collector_scheduler",
    "CollectorRun": ".collector_scheduler",
    "CollectorSchedulerError": ".collector_scheduler",
    "CollectorSchedulerService": ".collector_scheduler",
    "CollectorSchedulerStore": ".collector_scheduler",
    "CollectorTask": ".collector_scheduler",
    "TaskStatus": ".collector_scheduler",
    "TriggerType": ".collector_scheduler",
    "collector_run_signature": ".collector_scheduler",
    "collector_scheduler_store_path": ".collector_scheduler",
    "collector_run_guidance": ".collector_scheduler",
    "collector_task_guidance": ".collector_scheduler",
    "compute_next_run_at": ".collector_scheduler",
    "create_collector_task": ".collector_scheduler",
    "create_run_from_task": ".collector_scheduler",
    "normalize_date_range": ".collector_scheduler",
    "refresh_task_dependency_status": ".collector_scheduler",
    "seed_default_collector_tasks": ".collector_scheduler",
    "task_run_kwargs": ".collector_scheduler",
    "CollectorTemplateError": ".collector_templates",
    "DEFAULT_TASK_TEMPLATE_IDS": ".collector_templates",
    "TaskTemplate": ".collector_templates",
    "default_task_templates": ".collector_templates",
    "default_task_to_create_kwargs": ".collector_templates",
    "get_task_template": ".collector_templates",
    "list_task_templates": ".collector_templates",
    "task_template_to_create_kwargs": ".collector_templates",
    "DefaultRequestPlanner": ".downloader_engine",
    "DownloadMetadataWriter": ".downloader_engine",
    "DownloadQualityChecker": ".downloader_engine",
    "DownloadWriter": ".downloader_engine",
    "DataBrowserError": ".data_browser",
    "DataPreview": ".data_browser",
    "DatasetSummary": ".data_browser",
    "clamp_limit": ".data_browser",
    "delete_dataset": ".data_browser",
    "get_dataset": ".data_browser",
    "list_datasets": ".data_browser",
    "preview_dataset": ".data_browser",
    "AXP_CHECKSUMS_FILE_NAME": ".axp",
    "AXP_MANIFEST_FILE_NAME": ".axp",
    "AXP_SITE_PACKAGES_DIR_NAME": ".axp",
    "AxpAlreadyInstalledError": ".axp",
    "AxpDependencyStatus": ".axp",
    "AxpError": ".axp",
    "AxpInstalledPlugin": ".axp",
    "AxpInstallResult": ".axp",
    "AxpPreview": ".axp",
    "AxpUninstallError": ".axp",
    "AxpUninstallResult": ".axp",
    "AxpWheelInfo": ".axp",
    "axp_plugin_site_packages": ".axp",
    "AxpExportResult": ".axp",
    "export_axp_plugin": ".axp",
    "install_axp": ".axp",
    "list_installed_axp_plugins": ".axp",
    "preview_axp": ".axp",
    "uninstall_axp_plugin": ".axp",
    "BuiltinSourceAdapter": ".builtin_providers",
    "BuiltinSourceProvider": ".builtin_providers",
    "get_builtin_provider": ".builtin_providers",
    "list_builtin_providers": ".builtin_providers",
    "QualityIssue": ".quality",
    "check_missing_required": ".quality",
    "check_primary_key_duplicates": ".quality",
    "validate_table": ".quality",
    "query_table": ".query",
    "Field": ".schema",
    "TableSchema": ".schema",
    "get_schema": ".schema",
    "list_tables": ".schema",
    "normalize_table_name": ".schema",
    "SourceAdapterError": ".source_errors",
    "SourceAdapterNotFound": ".source_errors",
    "SourceInterfaceNotFound": ".source_errors",
    "SourceRequestError": ".source_errors",
    "SourceRequestResult": ".source_request",
    "SourceRequestValidationError": ".source_errors",
    "SourceUnavailableError": ".source_errors",
    "LocalSourceSession": ".source_session",
    "SessionSourceRequestAdapter": ".source_session",
    "SUPPORTED_SESSION_SOURCES": ".source_session",
    "create_source_session": ".source_session",
    "request_interface": ".source_request",
    "DownloadRequestPlan": ".downloader_engine",
    "DownloaderError": ".downloaders",
    "build_request_plan": ".downloaders",
    "get_downloader_profile": ".downloaders",
    "list_downloader_profiles": ".downloaders",
    "run_downloader": ".downloaders",
    "TradeCalendarCacheError": ".trade_calendar_cache",
    "check_trade_calendar_cache": ".trade_calendar_cache",
    "ensure_trade_calendar_cache": ".trade_calendar_cache",
    "get_trade_calendar_cache_status": ".trade_calendar_cache",
    "refresh_trade_calendar_cache": ".trade_calendar_cache",
    "trade_calendar_cache_path": ".trade_calendar_cache",
    "update_trade_calendar_cache_from_records": ".trade_calendar_cache",
    "core_table_duckdb_path": ".storage",
    "core_table_partition_path": ".storage",
    "core_table_path": ".storage",
    "core_table_read_path": ".storage",
    "read_core_table": ".storage",
    "write_core_table": ".storage",
    "build_local_diagnostics": ".diagnostics",
    "initialize_local_environment": ".diagnostics",
    "local_config": ".diagnostics",
    "provider_guidance": ".diagnostics",
    "resolve_data_root": ".diagnostics",
    "RequestExample": ".sources",
    "RequestField": ".sources",
    "RequestParameter": ".sources",
    "SourceRequestInterface": ".sources",
    "get_request_interface": ".sources",
    "list_request_interface_dicts": ".sources",
    "list_request_interface_names": ".sources",
    "list_request_interfaces": ".sources",
}

__all__ = sorted(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
