"""Cninfo source request interface catalog."""

from __future__ import annotations

from axdata_core.sources.base import (
    RequestExample,
    RequestField,
    RequestParameter,
    SourceRequestInterface,
)


def F(name: str, dtype: str, description_zh: str, description: str | None = None) -> RequestField:
    return RequestField(name, dtype, description or description_zh, description_zh)


ANNOUNCEMENT_FIELDS = (
    RequestField("instrument_id", "string", "AxData instrument id.", "AxData 统一证券代码。"),
    RequestField("symbol", "string", "Six-digit stock symbol.", "六位证券代码。"),
    RequestField("exchange", "string", "Exchange code.", "交易所代码：SSE、SZSE、BSE。"),
    RequestField("name", "string", "Security short name.", "证券简称。"),
    RequestField("announcement_id", "string", "Announcement id.", "公告 ID。"),
    RequestField("title", "string", "Announcement title.", "公告标题。"),
    RequestField("publish_date", "date/string", "Publish date, YYYYMMDD.", "公告发布日期，格式 YYYYMMDD。"),
    RequestField("file_type", "string", "Attachment file type.", "附件类型，例如 PDF。"),
    RequestField("file_size_kb", "float64", "Attachment size in KB.", "附件大小，单位：KB。"),
    RequestField("download_url", "string", "PDF download URL.", "PDF 下载地址。"),
)

STOCK_PROFILE_FIELDS = (
    RequestField("instrument_id", "string", "AxData instrument id.", "AxData 统一证券代码。"),
    RequestField("symbol", "string", "Six-digit stock symbol.", "六位证券代码。"),
    RequestField("exchange", "string", "Exchange code.", "交易所代码：SSE、SZSE、BSE。"),
    RequestField("company_name", "string", "Company legal name.", "公司全称。"),
    RequestField("english_name", "string", "English company name.", "英文名称。"),
    RequestField("former_short_name", "string", "Former security short names.", "曾用简称。"),
    RequestField("a_share_code", "string", "A-share code.", "A 股代码。"),
    RequestField("a_share_name", "string", "A-share short name.", "A 股简称。"),
    RequestField("b_share_code", "string", "B-share code.", "B 股代码。"),
    RequestField("b_share_name", "string", "B-share short name.", "B 股简称。"),
    RequestField("h_share_code", "string", "H-share code.", "H 股代码。"),
    RequestField("h_share_name", "string", "H-share short name.", "H 股简称。"),
    RequestField("selected_indexes", "string", "Source selected index labels.", "入选指数，沿用巨潮源端文本。"),
    RequestField("market", "string", "Listed market.", "所属市场。"),
    RequestField("industry", "string", "Industry name.", "所属行业。"),
    RequestField("legal_representative", "string", "Legal representative.", "法人代表。"),
    RequestField("registered_capital", "float64", "Registered capital, source unit.", "注册资金，沿用巨潮源端单位/口径。"),
    RequestField("founded_date", "date/string", "Company founded date.", "成立日期，格式 YYYYMMDD。"),
    RequestField("listing_date", "date/string", "Listing date.", "上市日期，格式 YYYYMMDD。"),
    RequestField("website", "string", "Official website.", "官方网站。"),
    RequestField("email", "string", "Investor contact email.", "电子邮箱。"),
    RequestField("phone", "string", "Investor contact phone.", "联系电话。"),
    RequestField("fax", "string", "Fax number.", "传真。"),
    RequestField("registered_address", "string", "Registered address.", "注册地址。"),
    RequestField("office_address", "string", "Office address.", "办公地址。"),
    RequestField("postcode", "string", "Postal code.", "邮政编码。"),
    RequestField("main_business", "string", "Main business.", "主营业务。"),
    RequestField("business_scope", "string", "Business scope.", "经营范围。"),
    RequestField("organization_profile", "string", "Organization profile.", "机构简介。"),
)

STOCK_ALLOTMENT_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("record_id", "string", "源端记录标识。"),
    F("name", "string", "证券简称。"),
    F("suspend_start_date", "date/string", "停牌起始日，格式 YYYYMMDD。"),
    F("listing_announcement_date", "date/string", "上市公告日期，格式 YYYYMMDD。"),
    F("payment_start_date", "date/string", "配股缴款起始日，格式 YYYYMMDD。"),
    F("convertible_allotment_shares", "float64", "可转配股数量，单位/口径沿用巨潮源端。"),
    F("suspend_end_date", "date/string", "停牌截止日，格式 YYYYMMDD。"),
    F("actual_allotment_shares", "float64", "实际配股数量，单位/口径沿用巨潮源端。"),
    F("allotment_price", "float64", "配股价格，单位：元。"),
    F("allotment_ratio", "float64", "配股比例，源端数值口径。"),
    F("pre_total_share", "float64", "配股前总股本，单位/口径沿用巨潮源端。"),
    F("transfer_fee_per_share", "float64", "每股配权转让费，单位：元。"),
    F("legal_person_actual_shares", "float64", "法人股实配数量，单位/口径沿用巨潮源端。"),
    F("raised_funds_net", "float64", "实际募资净额，金额单位/口径沿用巨潮源端。"),
    F("major_shareholder_subscribe_method", "string", "大股东认购方式。"),
    F("other_allotment_name", "string", "其他配售简称。"),
    F("issue_method", "string", "发行方式。"),
    F("failed_refund_date", "date/string", "配股失败退还申购款日期，格式 YYYYMMDD。"),
    F("ex_right_date", "date/string", "除权基准日，格式 YYYYMMDD。"),
    F("expected_issue_expense", "float64", "预计发行费用，金额单位/口径沿用巨潮源端。"),
    F("issue_result_announcement_date", "date/string", "配股发行结果公告日，格式 YYYYMMDD。"),
    F("warrant_trade_end_date", "date/string", "配股权证交易截止日，格式 YYYYMMDD。"),
    F("other_actual_shares", "float64", "其他股份实配数量，单位/口径沿用巨潮源端。"),
    F("state_actual_shares", "float64", "国家股实配数量，单位/口径沿用巨潮源端。"),
    F("entrusted_unit", "string", "委托单位。"),
    F("public_transfer_shares", "float64", "公众获转配数量，单位/口径沿用巨潮源端。"),
    F("other_allotment_code", "string", "其他配售代码。"),
    F("allotment_target", "string", "配售对象。"),
    F("warrant_trade_start_date", "date/string", "配股权证交易起始日，格式 YYYYMMDD。"),
    F("fund_arrival_date", "date/string", "资金到账日，格式 YYYYMMDD。"),
    F("organization_name", "string", "机构名称。"),
    F("record_date", "date/string", "股权登记日，格式 YYYYMMDD。"),
    F("raised_funds_gross", "float64", "实际募资总额，金额单位/口径沿用巨潮源端。"),
    F("expected_raised_funds", "float64", "预计募集资金，金额单位/口径沿用巨潮源端。"),
    F("major_shareholder_subscribe_shares", "float64", "大股东认购数量，单位/口径沿用巨潮源端。"),
    F("public_actual_shares", "float64", "公众股实配数量，单位/口径沿用巨潮源端。"),
    F("transfer_actual_shares", "float64", "转配股实配数量，单位/口径沿用巨潮源端。"),
    F("underwriting_fee", "float64", "承销费用，金额单位/口径沿用巨潮源端。"),
    F("legal_person_transfer_shares", "float64", "法人获转配数量，单位/口径沿用巨潮源端。"),
    F("post_float_share", "float64", "配股后流通股本，单位/口径沿用巨潮源端。"),
    F("stock_class", "string", "股票类别。"),
    F("public_allotment_name", "string", "公众配售简称。"),
    F("issue_method_code", "string", "发行方式编码。"),
    F("underwriting_method", "string", "承销方式。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("allotment_listing_date", "date/string", "配股上市日，格式 YYYYMMDD。"),
    F("payment_end_date", "date/string", "配股缴款截止日，格式 YYYYMMDD。"),
    F("underwriting_balance", "float64", "承销余额，单位/口径沿用巨潮源端。"),
    F("expected_allotment_shares", "float64", "预计配股数量，单位/口径沿用巨潮源端。"),
    F("post_total_share", "float64", "配股后总股本，单位/口径沿用巨潮源端。"),
    F("employee_actual_shares", "float64", "职工股实配数量，单位/口径沿用巨潮源端。"),
    F("underwriting_method_code", "string", "承销方式编码。"),
    F("issue_expenses_total", "float64", "发行费用总额，金额单位/口径沿用巨潮源端。"),
    F("pre_float_share", "float64", "配股前流通股本，单位/口径沿用巨潮源端。"),
    F("stock_class_code", "string", "股票类别编码。"),
    F("public_allotment_code", "string", "公众配售代码。"),
)

STOCK_DIVIDEND_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("announcement_date", "date/string", "实施方案公告日期，格式 YYYYMMDD。"),
    F("dividend_type", "string", "分红类型。"),
    F("bonus_share_ratio", "float64", "送股比例，源端数值口径。"),
    F("transfer_share_ratio", "float64", "转增比例，源端数值口径。"),
    F("cash_dividend_ratio", "float64", "派息比例，源端数值口径。"),
    F("record_date", "date/string", "股权登记日，格式 YYYYMMDD。"),
    F("ex_right_date", "date/string", "除权日，格式 YYYYMMDD。"),
    F("dividend_payment_date", "date/string", "派息日，格式 YYYYMMDD。"),
    F("share_arrival_date", "date/string", "股份到账日，格式 YYYYMMDD。"),
    F("plan_description", "string", "实施方案分红说明。"),
    F("report_period", "string", "报告时间/报告期，沿用巨潮源端文本。"),
)

STOCK_HOLD_CHANGE_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("trade_market", "string", "交易市场。"),
    F("name", "string", "证券简称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("change_date", "date/string", "变动日期，格式 YYYYMMDD。"),
    F("change_reason", "string", "变动原因。"),
    F("total_share", "float64", "总股本，单位/口径沿用巨潮源端。"),
    F("circulated_share", "float64", "已流通股份，单位/口径沿用巨潮源端。"),
    F("circulated_ratio", "float64", "已流通比例，源端数值口径。"),
    F("restricted_share", "float64", "流通受限股份，单位/口径沿用巨潮源端。"),
)

STOCK_HOLD_CONTROL_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("name", "string", "证券简称。"),
    F("change_date", "date/string", "变动日期，格式 YYYYMMDD。"),
    F("actual_controller_name", "string", "实际控制人名称。"),
    F("holding_shares", "float64", "控股数量，单位/口径沿用巨潮源端。"),
    F("holding_ratio", "float64", "控股比例，源端数值口径。"),
    F("direct_controller_name", "string", "直接控制人名称。"),
    F("control_type", "string", "控制类型。"),
)

STOCK_HOLD_NUM_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("report_date", "date/string", "请求报告期日期，格式 YYYYMMDD。"),
    F("name", "string", "证券简称。"),
    F("change_date", "date/string", "变动日期，格式 YYYYMMDD。"),
    F("shareholder_count", "float64", "本期股东人数，单位：户。"),
    F("prev_shareholder_count", "float64", "上期股东人数，单位：户。"),
    F("shareholder_count_change_pct", "float64", "股东人数增幅，源端百分比数值口径。"),
    F("avg_holding", "float64", "本期人均持股数量，单位/口径沿用巨潮源端。"),
    F("prev_avg_holding", "float64", "上期人均持股数量，单位/口径沿用巨潮源端。"),
    F("avg_holding_change_pct", "float64", "人均持股数量增幅，源端百分比数值口径。"),
)

STOCK_INDUSTRY_CATEGORY_FIELDS = (
    F("parent_code", "string", "父类编码。"),
    F("category_code", "string", "类目编码。"),
    F("category_name", "string", "类目名称。"),
    F("category_name_en", "string", "类目英文名称。"),
    F("end_date", "date/string", "终止日期，格式 YYYYMMDD；仍有效时可能为空。"),
    F("industry_type_code", "string", "行业类型编码。"),
    F("industry_type", "string", "行业类型。"),
    F("level", "integer", "按类目编码长度推导的层级，从 0 开始。"),
)

STOCK_IPO_SUMMARY_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("prospectus_announcement_date", "date/string", "招股公告日期，格式 YYYYMMDD。"),
    F("lottery_rate_announcement_date", "date/string", "中签率公告日，格式 YYYYMMDD。"),
    F("par_value", "float64", "每股面值，单位：元。"),
    F("total_issue_shares", "float64", "总发行数量，单位/口径沿用巨潮源端。"),
    F("nav_per_share_before_issue", "float64", "发行前每股净资产，单位：元。"),
    F("diluted_pe", "float64", "摊薄发行市盈率。"),
    F("raised_funds_net", "float64", "募集资金净额，金额单位/口径沿用巨潮源端。"),
    F("online_issue_date", "date/string", "上网发行日期，格式 YYYYMMDD。"),
    F("listing_date", "date/string", "上市日期，格式 YYYYMMDD。"),
    F("issue_price", "float64", "发行价格，单位：元。"),
    F("issue_expenses_total", "float64", "发行费用总额，金额单位/口径沿用巨潮源端。"),
    F("nav_per_share_after_issue", "float64", "发行后每股净资产，单位：元。"),
    F("online_lottery_rate", "float64", "上网发行中签率，源端百分比数值口径。"),
    F("lead_underwriter", "string", "主承销商。"),
)

STOCK_NEW_IPO_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("name", "string", "证券简称。"),
    F("listing_date", "date/string", "上市日期，格式 YYYYMMDD。"),
    F("subscription_date", "date/string", "申购日期，格式 YYYYMMDD。"),
    F("issue_price", "float64", "发行价，单位：元。"),
    F("total_issue_shares", "float64", "总发行数量，单位/口径沿用巨潮源端。"),
    F("issue_pe", "float64", "发行市盈率。"),
    F("online_lottery_rate", "float64", "上网发行中签率，源端百分比数值口径。"),
    F("lottery_result_announcement_date", "date/string", "摇号结果公告日，格式 YYYYMMDD。"),
    F("winning_announcement_date", "date/string", "中签公告日，格式 YYYYMMDD。"),
    F("payment_date", "date/string", "中签缴款日，格式 YYYYMMDD。"),
    F("online_subscription_limit", "float64", "网上申购上限，单位/口径沿用巨潮源端。"),
    F("online_issue_shares", "float64", "上网发行数量，单位/口径沿用巨潮源端。"),
)

STOCK_NEW_GH_FIELDS = (
    F("company_name", "string", "公司名称。"),
    F("meeting_date", "date/string", "上会日期，格式 YYYYMMDD。"),
    F("review_type", "string", "审核类型。"),
    F("review_content", "string", "审议内容。"),
    F("review_result", "string", "审核结果。"),
    F("announcement_date", "date/string", "审核公告日，格式 YYYYMMDD。"),
)

STOCK_SHARE_CHANGE_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。", "Six-digit stock symbol."),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。", "Exchange code."),
    F("name", "string", "证券简称。"),
    F("organization_name", "string", "机构名称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("change_date", "date/string", "变动日期，格式 YYYYMMDD。"),
    F("change_reason_code", "string", "变动原因编码。"),
    F("change_reason", "string", "变动原因。"),
    F("total_share", "float64", "总股本，单位/口径沿用巨潮源端。"),
    F("non_circulating_share", "float64", "未流通股份，单位/口径沿用巨潮源端。"),
    F("promoter_share", "float64", "发起人股份，单位/口径沿用巨潮源端。"),
    F("state_share", "float64", "国家持股，单位/口径沿用巨潮源端。"),
    F("state_owned_legal_person_share", "float64", "国有法人持股，单位/口径沿用巨潮源端。"),
    F("domestic_legal_person_share", "float64", "境内法人持股，单位/口径沿用巨潮源端。"),
    F("foreign_legal_person_share", "float64", "境外法人持股，单位/口径沿用巨潮源端。"),
    F("natural_person_share", "float64", "自然人持股，单位/口径沿用巨潮源端。"),
    F("raised_legal_person_share", "float64", "募集法人股，单位/口径沿用巨潮源端。"),
    F("employee_share", "float64", "内部职工股，单位/口径沿用巨潮源端。"),
    F("transferred_share", "float64", "转配股，单位/口径沿用巨潮源端。"),
    F("other_restricted_share", "float64", "其他流通受限股份，单位/口径沿用巨潮源端。"),
    F("preferred_share", "float64", "优先股，单位/口径沿用巨潮源端。"),
    F("other_non_circulating_share", "float64", "其他未流通股，单位/口径沿用巨潮源端。"),
    F("circulating_share", "float64", "已流通股份，单位/口径沿用巨潮源端。"),
    F("a_share", "float64", "人民币普通股，单位/口径沿用巨潮源端。"),
    F("b_share", "float64", "境内上市外资股 B 股，单位/口径沿用巨潮源端。"),
    F("h_share", "float64", "境外上市外资股 H 股，单位/口径沿用巨潮源端。"),
    F("executive_share", "float64", "高管股，单位/口径沿用巨潮源端。"),
    F("other_circulating_share", "float64", "其他流通股，单位/口径沿用巨潮源端。"),
    F("restricted_share", "float64", "流通受限股份，单位/口径沿用巨潮源端。"),
    F("allocated_legal_person_share", "float64", "配售法人股，单位/口径沿用巨潮源端。"),
    F("strategic_investor_share", "float64", "战略投资者持股，单位/口径沿用巨潮源端。"),
    F("securities_investment_fund_share", "float64", "证券投资基金持股，单位/口径沿用巨潮源端。"),
    F("general_legal_person_share", "float64", "一般法人持股，单位/口径沿用巨潮源端。"),
    F("state_restricted_share", "float64", "国家持股-受限，单位/口径沿用巨潮源端。"),
    F("state_owned_legal_person_restricted_share", "float64", "国有法人持股-受限，单位/口径沿用巨潮源端。"),
    F("other_domestic_restricted_share", "float64", "其他内资持股-受限，单位/口径沿用巨潮源端。"),
    F("domestic_legal_person_restricted_share", "float64", "其中：境内法人持股，单位/口径沿用巨潮源端。"),
    F("domestic_natural_person_restricted_share", "float64", "其中：境内自然人持股，单位/口径沿用巨潮源端。"),
    F("foreign_restricted_share", "float64", "外资持股-受限，单位/口径沿用巨潮源端。"),
    F("foreign_legal_person_restricted_share", "float64", "其中：境外法人持股，单位/口径沿用巨潮源端。"),
    F("foreign_natural_person_restricted_share", "float64", "其中：境外自然人持股，单位/口径沿用巨潮源端。"),
    F("restricted_executive_share", "float64", "其中：限售高管股，单位/口径沿用巨潮源端。"),
    F("restricted_b_share", "float64", "其中：限售 B 股，单位/口径沿用巨潮源端。"),
    F("restricted_h_share", "float64", "其中：限售 H 股，单位/口径沿用巨潮源端。"),
    F("controlling_shareholder_actual_controller_share", "float64", "控股股东、实际控制人持股，单位/口径沿用巨潮源端。"),
)

FUND_ASSET_ALLOCATION_FIELDS = (
    F("report_date", "date/string", "报告期，格式 YYYYMMDD。"),
    F("fund_count", "float64", "基金覆盖家数，单位：只。"),
    F("equity_asset_pct", "float64", "股票权益类占净资产比例，源端百分比数值口径。"),
    F("bond_asset_pct", "float64", "债券固定收益类占净资产比例，源端百分比数值口径。"),
    F("cash_asset_pct", "float64", "现金货币类占净资产比例，源端百分比数值口径。"),
    F("fund_market_net_assets", "float64", "基金市场净资产规模，金额单位/口径沿用巨潮源端。"),
)

FUND_INDUSTRY_ALLOCATION_FIELDS = (
    F("industry_code", "string", "证监会行业编码。"),
    F("industry_name", "string", "证监会行业名称。"),
    F("report_date", "date/string", "报告期，格式 YYYYMMDD。"),
    F("fund_count", "float64", "基金覆盖家数，单位：只。"),
    F("industry_scale", "float64", "行业规模，金额单位/口径沿用巨潮源端。"),
    F("net_asset_pct", "float64", "占净资产比例，源端百分比数值口径。"),
)

FUND_STOCK_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码；若源端不是六位 A 股代码则为空。", "AxData instrument id when source code is a six-digit A-share symbol."),
    F("symbol", "string", "证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE；无法识别时为空。"),
    F("record_id", "string", "源端记录序号。"),
    F("name", "string", "股票简称。"),
    F("report_date", "date/string", "报告期，格式 YYYYMMDD。"),
    F("fund_count", "float64", "基金覆盖家数，单位：只。"),
    F("holding_shares", "float64", "持股总数，单位/口径沿用巨潮源端。"),
    F("holding_market_value", "float64", "持股总市值，金额单位/口径沿用巨潮源端。"),
)

STOCK_CG_EQUITY_MORTGAGE_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("stat_date", "date/string", "请求统计日期，格式 YYYYMMDD。"),
    F("name", "string", "股票简称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("pledgor", "string", "出质人。"),
    F("pledgee", "string", "质权人。"),
    F("pledged_shares", "float64", "质押数量，单位/口径沿用巨潮源端。"),
    F("pledged_total_share_pct", "float64", "占总股本比例，源端百分比数值口径。"),
    F("released_pledge_shares", "float64", "质押解除数量，单位/口径沿用巨潮源端。"),
    F("pledge_event", "string", "质押事项。"),
    F("cumulative_pledge_total_share_pct", "float64", "累计质押占总股本比例，源端百分比数值口径。"),
)

STOCK_CG_GUARANTEE_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "证券简称。"),
    F("announcement_period", "string", "公告统计区间，沿用巨潮源端文本。"),
    F("guarantee_count", "float64", "担保笔数，单位：笔。"),
    F("guarantee_amount", "float64", "担保金额，金额单位/口径沿用巨潮源端。"),
    F("parent_equity", "float64", "归属于母公司所有者权益，金额单位/口径沿用巨潮源端。"),
    F("guarantee_amount_net_asset_pct", "float64", "担保金额占净资产比例，源端百分比数值口径。"),
)

STOCK_CG_LAWSUIT_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "证券简称。"),
    F("announcement_period", "string", "公告统计区间，沿用巨潮源端文本。"),
    F("lawsuit_count", "float64", "诉讼次数，单位：次。"),
    F("lawsuit_amount", "float64", "诉讼金额，金额单位/口径沿用巨潮源端。"),
)

STOCK_HOLD_MANAGEMENT_DETAIL_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "证券简称。"),
    F("change_type", "string", "变动类型：增持、减持。"),
    F("end_date", "date/string", "截止日期，格式 YYYYMMDD。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("executive_name", "string", "高管姓名。"),
    F("director_supervisor_senior_name", "string", "董监高姓名。"),
    F("director_supervisor_senior_position", "string", "董监高职务。"),
    F("changer_relation", "string", "变动人与董监高关系。"),
    F("beginning_holding_shares", "float64", "期初持股数量，单位/口径沿用巨潮源端。"),
    F("ending_holding_shares", "float64", "期末持股数量，单位/口径沿用巨潮源端。"),
    F("change_shares", "float64", "变动数量，单位/口径沿用巨潮源端。"),
    F("change_ratio", "float64", "变动比例，源端百分比数值口径。"),
    F("average_price", "float64", "成交均价，单位：元。"),
    F("ending_market_value", "float64", "期末市值，金额单位/口径沿用巨潮源端。"),
    F("change_reason", "string", "持股变动原因。"),
    F("data_source", "string", "数据来源。"),
)

STOCK_INDUSTRY_CHANGE_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "新证券简称。"),
    F("organization_name", "string", "机构名称。"),
    F("change_date", "date/string", "行业归属变更日期，格式 YYYYMMDD。"),
    F("classification_standard_code", "string", "分类标准编码。"),
    F("classification_standard", "string", "分类标准名称。"),
    F("industry_code", "string", "行业编码。"),
    F("industry_sector", "string", "行业门类。"),
    F("industry_subcategory", "string", "行业次类。"),
    F("industry_major", "string", "行业大类。"),
    F("industry_middle", "string", "行业中类。"),
    F("latest_record_flag", "string", "最新记录标识，沿用巨潮源端。"),
)

STOCK_INDUSTRY_PE_RATIO_FIELDS = (
    F("change_date", "date/string", "变动日期/查询日期，格式 YYYYMMDD。"),
    F("classification", "string", "行业分类。"),
    F("industry_level", "integer", "行业层级。"),
    F("industry_code", "string", "行业编码。"),
    F("industry_name", "string", "行业名称。"),
    F("company_count", "float64", "公司数量，单位：家。"),
    F("included_company_count", "float64", "纳入计算公司数量，单位：家。"),
    F("total_market_value_static", "float64", "总市值-静态，金额单位/口径沿用巨潮源端。"),
    F("net_profit_static", "float64", "净利润-静态，金额单位/口径沿用巨潮源端。"),
    F("static_pe_weighted", "float64", "静态市盈率-加权平均。"),
    F("static_pe_median", "float64", "静态市盈率-中位数。"),
    F("static_pe_mean", "float64", "静态市盈率-算术平均。"),
)

STOCK_RANK_FORECAST_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。", "AxData instrument id."),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "证券简称。"),
    F("publish_date", "date/string", "发布日期，格式 YYYYMMDD。"),
    F("institution_short_name", "string", "研究机构简称。"),
    F("analyst_name", "string", "研究员名称。"),
    F("rating", "string", "投资评级。"),
    F("is_first_rating", "string", "是否首次评级，沿用巨潮源端文本。"),
    F("rating_change", "string", "评级变化。"),
    F("previous_rating", "string", "前一次投资评级。"),
    F("target_price_low", "float64", "目标价格下限，单位：元。"),
    F("target_price_high", "float64", "目标价格上限，单位：元。"),
)

BOND_CORPORATE_ISSUE_FIELDS = (
    F("bond_code", "string", "债券代码。"),
    F("bond_short_name", "string", "债券简称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("online_issue_start_date", "date/string", "交易所网上发行起始日，格式 YYYYMMDD。"),
    F("online_issue_end_date", "date/string", "交易所网上发行终止日，格式 YYYYMMDD。"),
    F("planned_issue_amount", "float64", "计划发行总量，单位/口径沿用巨潮源端。"),
    F("actual_issue_amount", "float64", "实际发行总量，单位/口径沿用巨潮源端。"),
    F("par_value", "float64", "发行面值，单位：元。"),
    F("issue_price", "float64", "发行价格，单位：元。"),
    F("issue_method", "string", "发行方式。"),
    F("issue_target", "string", "发行对象。"),
    F("issue_scope", "string", "发行范围。"),
    F("underwriting_method", "string", "承销方式。"),
    F("min_subscription_unit", "float64", "最小认购单位，单位/口径沿用巨潮源端。"),
    F("fundraising_use", "string", "募资用途说明。"),
    F("min_subscription_amount", "float64", "最低认购额，金额单位/口径沿用巨潮源端。"),
    F("bond_name", "string", "债券名称。"),
)

BOND_COV_ISSUE_FIELDS = (
    F("bond_code", "string", "债券代码。"),
    F("bond_short_name", "string", "债券简称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("issue_start_date", "date/string", "发行起始日，格式 YYYYMMDD。"),
    F("issue_end_date", "date/string", "发行终止日，格式 YYYYMMDD。"),
    F("planned_issue_amount", "float64", "计划发行总量，单位/口径沿用巨潮源端。"),
    F("actual_issue_amount", "float64", "实际发行总量，单位/口径沿用巨潮源端。"),
    F("par_value", "float64", "发行面值，单位：元。"),
    F("issue_price", "float64", "发行价格，单位：元。"),
    F("issue_method", "string", "发行方式。"),
    F("issue_target", "string", "发行对象。"),
    F("issue_scope", "string", "发行范围。"),
    F("underwriting_method", "string", "承销方式。"),
    F("fundraising_use", "string", "募资用途说明。"),
    F("initial_conversion_price", "float64", "初始转股价格，单位：元。"),
    F("conversion_start_date", "date/string", "转股开始日期，格式 YYYYMMDD。"),
    F("conversion_end_date", "date/string", "转股终止日期，格式 YYYYMMDD。"),
    F("online_subscription_date", "date/string", "网上申购日期，格式 YYYYMMDD。"),
    F("online_subscription_code", "string", "网上申购代码。"),
    F("online_subscription_short_name", "string", "网上申购简称。"),
    F("online_subscription_max", "float64", "网上申购数量上限，单位/口径沿用巨潮源端。"),
    F("online_subscription_min", "float64", "网上申购数量下限，单位/口径沿用巨潮源端。"),
    F("online_subscription_unit", "float64", "网上申购单位，单位/口径沿用巨潮源端。"),
    F("online_lottery_result_refund_date", "date/string", "网上申购中签结果公告日及退款日，格式 YYYYMMDD。"),
    F("priority_subscription_date", "date/string", "优先申购日，格式 YYYYMMDD。"),
    F("allotment_price", "float64", "配售价格，单位：元。"),
    F("bondholder_record_date", "date/string", "债权登记日，格式 YYYYMMDD。"),
    F("priority_subscription_payment_date", "date/string", "优先申购缴款日，格式 YYYYMMDD。"),
    F("conversion_code", "string", "转股代码。"),
    F("trading_market", "string", "交易市场。"),
    F("bond_name", "string", "债券名称。"),
)

BOND_COV_STOCK_ISSUE_FIELDS = (
    F("bond_code", "string", "债券代码。"),
    F("bond_short_name", "string", "债券简称。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("conversion_code", "string", "转股代码。"),
    F("conversion_short_name", "string", "转股简称。"),
    F("conversion_price", "float64", "转股价格，单位：元。"),
    F("voluntary_conversion_start_date", "date/string", "自愿转换期起始日，格式 YYYYMMDD。"),
    F("voluntary_conversion_end_date", "date/string", "自愿转换期终止日，格式 YYYYMMDD。"),
    F("underlying_stock", "string", "标的股票。"),
    F("bond_name", "string", "债券名称。"),
)

BOND_PUBLIC_ISSUE_FIELDS = (
    F("bond_code", "string", "债券代码。"),
    F("bond_short_name", "string", "债券简称。"),
    F("issue_start_date", "date/string", "发行起始日，格式 YYYYMMDD。"),
    F("issue_end_date", "date/string", "发行终止日，格式 YYYYMMDD。"),
    F("planned_issue_amount", "float64", "计划发行总量，单位/口径沿用巨潮源端。"),
    F("actual_issue_amount", "float64", "实际发行总量，单位/口径沿用巨潮源端。"),
    F("issue_price", "float64", "发行价格，单位：元。"),
    F("par_value", "float64", "单位面值，单位：元。"),
    F("payment_date", "date/string", "缴款日，格式 YYYYMMDD。"),
    F("additional_issue_count", "float64", "增发次数，源端数值口径。"),
    F("trading_market", "string", "交易市场。"),
    F("issue_method", "string", "发行方式。"),
    F("issue_target", "string", "发行对象。"),
    F("announcement_date", "date/string", "公告日期，格式 YYYYMMDD。"),
    F("bond_name", "string", "债券名称。"),
)


INTERFACES: dict[str, SourceRequestInterface] = {
    "cninfo_announcements": SourceRequestInterface(
        name="cninfo_announcements",
        display_name_zh="公告列表",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公告数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮公告列表，返回公告元信息，默认不入库。",
        source_ability="Cninfo announcement list metadata",
        description=(
            "Return Cninfo announcement metadata for one or more A-share securities. "
            "publish_date is the source announcement date. file_size_kb is the source attachment size in KB."
        ),
        parameters=(
            RequestParameter("code", "string/list", True, "Stock code(s).", "股票代码，支持 000001、000001.SZ、sh600000 或列表。"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size, capped at 100.", "每页条数，默认 30，最大 100。", 30),
        ),
        fields=ANNOUNCEMENT_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "000001.SZ",
                    "start_date": "20240101",
                    "end_date": "20240131",
                    "limit": 3,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "000001.SZ",
                    "symbol": "000001",
                    "exchange": "SZSE",
                    "name": "平安银行",
                    "announcement_id": "1218968511",
                    "title": "关联交易公告",
                    "publish_date": "20240123",
                    "file_type": "PDF",
                    "file_size_kb": 156.0,
                    "download_url": "https://static.cninfo.com.cn/finalpage/2024-01-23/1218968511.PDF",
                },
            ),
        ),
    ),
    "stock_irm_cninfo": SourceRequestInterface(
        name="stock_irm_cninfo",
        display_name_zh="互动易提问",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="互动易",
        request_mode="source_request",
        first_stage_strategy="临时请求互动易提问列表，默认不入库。",
        source_ability="Cninfo IRM question list",
        description=(
            "Return Cninfo IRM question rows for one A-share security. question_time and update_time are "
            "converted from source milliseconds to Asia/Shanghai YYYYMMDDHHMMSS strings."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 002594、002594.SZ。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size, capped at 1000.", "每页条数，默认 30，最大 1000。", 30),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD；可选。"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD；可选。"),
            RequestParameter("keyword", "string", False, "Keyword.", "关键词；可选。"),
        ),
        fields=(
            RequestField("instrument_id", "string", "AxData instrument id.", "AxData 统一证券代码。"),
            RequestField("symbol", "string", "Six-digit stock symbol.", "六位证券代码。"),
            RequestField("exchange", "string", "Exchange code.", "交易所代码：SSE、SZSE、BSE。"),
            RequestField("name", "string", "Company short name.", "公司简称。"),
            RequestField("industry", "string", "Source industry name.", "源端行业名称。"),
            RequestField("industry_code", "string", "Source industry code.", "源端行业代码。"),
            RequestField("question_id", "string", "Question id.", "互动易问题编号。"),
            RequestField("question", "string", "Question content.", "提问内容。"),
            RequestField("questioner", "string", "Questioner name.", "提问者。"),
            RequestField("questioner_id", "string", "Questioner id.", "提问者编号。"),
            RequestField("source", "string", "Question source.", "提问来源：APP、公众号、网站等。"),
            RequestField("question_time", "datetime/string", "Question timestamp.", "提问时间，Asia/Shanghai，格式 YYYYMMDDHHMMSS。"),
            RequestField("update_time", "datetime/string", "Update timestamp.", "更新时间，Asia/Shanghai，格式 YYYYMMDDHHMMSS。"),
            RequestField("answer_id", "string", "Attached answer id.", "已关联回答 ID；未回答时为空。"),
            RequestField("answer", "string", "Attached answer content.", "已关联回答内容；未回答时为空。"),
            RequestField("answerer", "string", "Answer author.", "回答者；未回答时为空。"),
        ),
        example=RequestExample(
            request={"params": {"code": "002594.SZ", "page": 1, "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "002594.SZ",
                    "symbol": "002594",
                    "exchange": "SZSE",
                    "name": "比亚迪",
                    "industry": "制造业",
                    "industry_code": "012002",
                    "question_id": "2301823909845012480",
                    "question": "尊敬的董秘你好，贵司的研发费用，Q2Q3财报上面，请部分资本化率一些，不要太难看了，让小股东对贵司有点信心，也让投资者对中国新能源产业有点信心，谢谢",
                    "questioner": "irm3229095",
                    "questioner_id": "2227137287091273728",
                    "source": "APP",
                    "question_time": "20260629112612",
                    "update_time": "20260703145809",
                    "answer_id": None,
                    "answer": None,
                    "answerer": None,
                },
            ),
        ),
    ),
    "stock_irm_ans_cninfo": SourceRequestInterface(
        name="stock_irm_ans_cninfo",
        display_name_zh="互动易回答详情",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="互动易",
        request_mode="source_request",
        first_stage_strategy="临时请求互动易单条问答详情，默认不入库。",
        source_ability="Cninfo IRM question detail",
        description=(
            "Return one Cninfo IRM question-answer detail row. question_time and answer_time are converted "
            "from source milliseconds to Asia/Shanghai YYYYMMDDHHMMSS strings."
        ),
        parameters=(
            RequestParameter("question_id", "string", True, "Question id.", "互动易问题编号，可从 stock_irm_cninfo 的 question_id 获取。"),
        ),
        fields=(
            RequestField("instrument_id", "string", "AxData instrument id.", "AxData 统一证券代码。"),
            RequestField("symbol", "string", "Six-digit stock symbol.", "六位证券代码。"),
            RequestField("exchange", "string", "Exchange code.", "交易所代码：SSE、SZSE、BSE。"),
            RequestField("name", "string", "Company short name.", "公司简称。"),
            RequestField("question_id", "string", "Question id.", "互动易问题编号。"),
            RequestField("question", "string", "Question content.", "提问内容。"),
            RequestField("answer", "string", "Reply content.", "回答内容。"),
            RequestField("questioner", "string", "Questioner name.", "提问者。"),
            RequestField("question_time", "datetime/string", "Question timestamp.", "提问时间，Asia/Shanghai，格式 YYYYMMDDHHMMSS。"),
            RequestField("answer_time", "datetime/string", "Reply timestamp.", "回答时间，Asia/Shanghai，格式 YYYYMMDDHHMMSS。"),
        ),
        example=RequestExample(
            request={"params": {"question_id": "1495108801386602496"}, "persist": False},
            response=(
                {
                    "instrument_id": "002594.SZ",
                    "symbol": "002594",
                    "exchange": "SZSE",
                    "name": "比亚迪",
                    "question_id": "1495108801386602496",
                    "question": "建议比亚迪公司研究研究“老车主付费升级辅助驾驶系统”的可行性，一来可以提升用户使用体验，二来可以增加收入。",
                    "answer": "您好！比亚迪一直秉承用技术创新，满足人们对美好生活的向往，持续关注消费者的需求，并适时推出符合需求的产品。您的建议我们已经收到，感谢您对公司的关注！",
                    "questioner": "irm1541214",
                    "question_time": "20230708121253",
                    "answer_time": "20230712083431",
                },
            ),
        ),
    ),
    "stock_zh_a_disclosure_report_cninfo": SourceRequestInterface(
        name="stock_zh_a_disclosure_report_cninfo",
        display_name_zh="信息披露公告",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公告数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮信息披露公告列表，返回公告元信息，默认不入库。",
        source_ability="Cninfo disclosure report list",
        description="Return Cninfo disclosure report metadata for one A-share security.",
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 000001、000001.SZ。"),
            RequestParameter("market", "string", False, "Market scope.", "市场范围，当前支持 沪深京，默认 沪深京。", "沪深京"),
            RequestParameter("keyword", "string", False, "Search keyword.", "搜索关键词；可选。"),
            RequestParameter("category", "string", False, "Disclosure category.", "公告类别中文名，例如 年报、权益分派、配股；可选。"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size, capped at 100.", "每页条数，默认 30，最大 100。", 30),
        ),
        fields=ANNOUNCEMENT_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "000001.SZ",
                    "start_date": "20240101",
                    "end_date": "20240131",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "000001.SZ",
                    "symbol": "000001",
                    "exchange": "SZSE",
                    "name": "平安银行",
                    "announcement_id": "1218968511",
                    "title": "关联交易公告",
                    "publish_date": "20240123",
                    "file_type": "PDF",
                    "file_size_kb": 156.0,
                    "download_url": "https://static.cninfo.com.cn/finalpage/2024-01-23/1218968511.PDF",
                },
            ),
        ),
    ),
    "stock_zh_a_disclosure_relation_cninfo": SourceRequestInterface(
        name="stock_zh_a_disclosure_relation_cninfo",
        display_name_zh="预约披露调研公告",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公告数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮预约披露调研公告列表，返回公告元信息，默认不入库。",
        source_ability="Cninfo disclosure relation list",
        description="Return Cninfo relation/disclosure research metadata for one A-share security.",
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 000001、000001.SZ。"),
            RequestParameter("market", "string", False, "Market scope.", "市场范围，当前支持 沪深京，默认 沪深京。", "沪深京"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size, capped at 100.", "每页条数，默认 30，最大 100。", 30),
        ),
        fields=ANNOUNCEMENT_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "000001.SZ",
                    "start_date": "20230619",
                    "end_date": "20231220",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "000001.SZ",
                    "symbol": "000001",
                    "exchange": "SZSE",
                    "name": "平安银行",
                    "announcement_id": "1218282445",
                    "title": "投资者关系活动记录表",
                    "publish_date": "20231108",
                    "file_type": "PDF",
                    "file_size_kb": 257.0,
                    "download_url": "https://static.cninfo.com.cn/finalpage/2023-11-08/1218282445.PDF",
                },
            ),
        ),
    ),
    "stock_allotment_cninfo": SourceRequestInterface(
        name="stock_allotment_cninfo",
        display_name_zh="配股实施方案",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮配股实施方案 webapi，返回单只股票配股明细，默认不入库。",
        source_ability="Cninfo stock allotment implementation webapi",
        description=(
            "Return Cninfo stock allotment implementation rows for one A-share security. "
            "Dates are normalized to YYYYMMDD; share and money fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 600030、600030.SH。"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 19900101。", "19900101"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20991231。", "20991231"),
        ),
        fields=STOCK_ALLOTMENT_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "600030.SH",
                    "start_date": "19900101",
                    "end_date": "20241022",
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "600030.SH",
                    "symbol": "600030",
                    "exchange": "SSE",
                    "record_id": "4475575959",
                    "name": "中信证券",
                    "suspend_start_date": "20220119",
                    "listing_announcement_date": "20220210",
                    "payment_start_date": "20220119",
                    "convertible_allotment_shares": None,
                    "suspend_end_date": "20220126",
                    "actual_allotment_shares": 155202.1645,
                    "allotment_price": 14.43,
                    "allotment_ratio": 1.5,
                    "pre_total_share": 1292677.6029,
                    "transfer_fee_per_share": None,
                    "legal_person_actual_shares": None,
                    "raised_funds_net": 2231819.5732,
                    "major_shareholder_subscribe_method": "公司第一大股东中国中信有限公司已承诺，将根据公司本次配股股权登记日收市后的持股数量，以现金方式全额认购根据公司配股方案确定的可获配股份。",
                    "other_allotment_name": None,
                    "issue_method": "上网定价发行",
                    "failed_refund_date": "20220127",
                    "ex_right_date": "20220127",
                    "expected_issue_expense": None,
                    "issue_result_announcement_date": "20220127",
                    "warrant_trade_end_date": None,
                    "other_actual_shares": None,
                    "state_actual_shares": None,
                    "entrusted_unit": None,
                    "public_transfer_shares": None,
                    "other_allotment_code": None,
                    "allotment_target": "截至股权登记日2022年1月18日(T日）上交所收市后，在中国证券登记结算有限责任公司上海分公司登记在册的公司全体A股股东配售。",
                    "warrant_trade_start_date": None,
                    "fund_arrival_date": None,
                    "organization_name": "中信证券股份有限公司",
                    "record_date": "20220118",
                    "raised_funds_gross": 2239567.2337,
                    "expected_raised_funds": 2304856.6403,
                    "major_shareholder_subscribe_shares": 29995.4362,
                    "public_actual_shares": 155202.1645,
                    "transfer_actual_shares": None,
                    "underwriting_fee": None,
                    "legal_person_transfer_shares": None,
                    "post_float_share": 1364501.1045,
                    "stock_class": "A股",
                    "public_allotment_name": "中信配股",
                    "issue_method_code": "049012",
                    "underwriting_method": "代销",
                    "announcement_date": "20220114",
                    "allotment_listing_date": "20220215",
                    "payment_end_date": "20220125",
                    "underwriting_balance": None,
                    "expected_allotment_shares": 159726.7249,
                    "post_total_share": 1447879.7674,
                    "employee_actual_shares": None,
                    "underwriting_method_code": "051002",
                    "issue_expenses_total": 7747.6606,
                    "pre_float_share": 1209298.94,
                    "stock_class_code": "001001",
                    "public_allotment_code": "700030",
                },
            ),
        ),
    ),
    "stock_dividend_cninfo": SourceRequestInterface(
        name="stock_dividend_cninfo",
        display_name_zh="历史分红",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="分红融资",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮历史分红 webapi，返回单只股票分红实施方案，默认不入库。",
        source_ability="Cninfo stock dividend webapi",
        description=(
            "Return historical dividend plan rows from Cninfo for one A-share security. "
            "Dates are normalized to YYYYMMDD; share and cash ratios keep Cninfo source caliber."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 600009、600009.SH。"),
        ),
        fields=STOCK_DIVIDEND_FIELDS,
        example=RequestExample(
            request={"params": {"code": "600009.SH"}, "persist": False},
            response=(
                {
                    "instrument_id": "600009.SH",
                    "symbol": "600009",
                    "exchange": "SSE",
                    "announcement_date": "19981128",
                    "dividend_type": "中期分红",
                    "bonus_share_ratio": 5.0,
                    "transfer_share_ratio": 0.0,
                    "cash_dividend_ratio": 0.0,
                    "record_date": "19981202",
                    "ex_right_date": "19981203",
                    "dividend_payment_date": None,
                    "share_arrival_date": None,
                    "plan_description": "10转增5股",
                    "report_period": "1998半年报",
                },
            ),
        ),
    ),
    "stock_hold_change_cninfo": SourceRequestInterface(
        name="stock_hold_change_cninfo",
        display_name_zh="股本变动",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮股本变动专题统计，返回所选市场的股本变动行，默认不入库。",
        source_ability="Cninfo stock share-capital change thematic webapi",
        description=(
            "Return share-capital change rows from Cninfo thematic statistics. "
            "market accepts Chinese market names or source market codes; market=全部 is kept as a source option but may be flaky upstream."
        ),
        parameters=(
            RequestParameter(
                "market",
                "string",
                False,
                "Market filter.",
                "市场范围：深市主板、沪市、创业板、科创板、北交所、全部；默认 沪市。源端全部口径可能返回 403。",
                "沪市",
            ),
        ),
        fields=STOCK_HOLD_CHANGE_FIELDS,
        example=RequestExample(
            request={"params": {"market": "沪市"}, "persist": False},
            response=(
                {
                    "instrument_id": "600000.SH",
                    "symbol": "600000",
                    "exchange": "SSE",
                    "trade_market": "上交所",
                    "name": "浦发银行",
                    "announcement_date": "20260331",
                    "change_date": "20251231",
                    "change_reason": "定期报告",
                    "total_share": 3330583.83,
                    "circulated_share": 3330583.83,
                    "circulated_ratio": 100.0,
                    "restricted_share": None,
                },
            ),
        ),
    ),
    "stock_hold_control_cninfo": SourceRequestInterface(
        name="stock_hold_control_cninfo",
        display_name_zh="实际控制人持股变动",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮实际控制人持股变动专题统计，默认不入库。",
        source_ability="Cninfo actual-controller holding change webapi",
        description=(
            "Return actual-controller holding change rows from Cninfo thematic statistics. "
            "control_type accepts Chinese names or source control-type codes."
        ),
        parameters=(
            RequestParameter(
                "control_type",
                "string",
                False,
                "Control type filter.",
                "控制类型：单独控制、实际控制人、一致行动人、家族控制、全部；默认 实际控制人。",
                "实际控制人",
            ),
        ),
        fields=STOCK_HOLD_CONTROL_FIELDS,
        example=RequestExample(
            request={"params": {"control_type": "实际控制人"}, "persist": False},
            response=(
                {
                    "instrument_id": "600081.SH",
                    "symbol": "600081",
                    "exchange": "SSE",
                    "name": "东风科技",
                    "change_date": "20140630",
                    "actual_controller_name": "国务院国有资产监督管理委员会;法国雷诺公司",
                    "holding_shares": 20381.0,
                    "holding_ratio": 65.0,
                    "direct_controller_name": "东风汽车公司;日产自动车株式会社",
                    "control_type": "实际控制人",
                },
            ),
        ),
    ),
    "stock_hold_num_cninfo": SourceRequestInterface(
        name="stock_hold_num_cninfo",
        display_name_zh="股东人数及持股集中度",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮股东人数及持股集中度专题统计，默认不入库。",
        source_ability="Cninfo shareholder count and concentration webapi",
        description=(
            "Return shareholder-count and average-holding rows for a report date. "
            "date is usually a quarter-end date such as 20210630."
        ),
        parameters=(
            RequestParameter("date", "string", False, "Report date.", "报告期日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210630。", "20210630"),
        ),
        fields=STOCK_HOLD_NUM_FIELDS,
        example=RequestExample(
            request={"params": {"date": "20210630"}, "persist": False},
            response=(
                {
                    "instrument_id": "002054.SZ",
                    "symbol": "002054",
                    "exchange": "SZSE",
                    "report_date": "20210630",
                    "name": "德美化工",
                    "change_date": "20210630",
                    "shareholder_count": 17768.0,
                    "prev_shareholder_count": 19463.0,
                    "shareholder_count_change_pct": -8.71,
                    "avg_holding": 27134.0,
                    "prev_avg_holding": 24771.0,
                    "avg_holding_change_pct": 9.54,
                },
            ),
        ),
    ),
    "stock_industry_category_cninfo": SourceRequestInterface(
        name="stock_industry_category_cninfo",
        display_name_zh="行业分类数据",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="行业数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮行业分类字典，返回分类树行，默认不入库。",
        source_ability="Cninfo industry category dictionary webapi",
        description=(
            "Return Cninfo industry classification rows for one classification standard. "
            "level is inferred from the source category-code length. The 巨潮行业分类标准 option is currently flaky upstream."
        ),
        parameters=(
            RequestParameter(
                "industry_type",
                "string",
                False,
                "Classification standard.",
                "行业分类标准：证监会行业分类标准、巨潮行业分类标准、申银万国行业分类标准、新财富行业分类标准、国资委行业分类标准、巨潮产业细分标准、天相行业分类标准、全球行业分类标准；默认 证监会行业分类标准。巨潮行业分类标准源端当前可能失败。",
                "证监会行业分类标准",
            ),
        ),
        fields=STOCK_INDUSTRY_CATEGORY_FIELDS,
        example=RequestExample(
            request={"params": {"industry_type": "008001"}, "persist": False},
            response=(
                {
                    "parent_code": "008",
                    "category_code": "0",
                    "category_name": "中国上市公司协会上市公司行业分类",
                    "category_name_en": "CAPCO Industry Classification",
                    "end_date": None,
                    "industry_type_code": "008001",
                    "industry_type": "中国上市公司协会上市公司行业分类标准",
                    "level": 0,
                },
            ),
        ),
    ),
    "stock_ipo_summary_cninfo": SourceRequestInterface(
        name="stock_ipo_summary_cninfo",
        display_name_zh="上市相关",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="新股数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮单股上市相关 webapi，默认不入库。",
        source_ability="Cninfo single-stock IPO summary webapi",
        description="Return IPO/listing summary fields for one A-share security from Cninfo.",
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 600030、600030.SH。"),
        ),
        fields=STOCK_IPO_SUMMARY_FIELDS,
        example=RequestExample(
            request={"params": {"code": "600030.SH"}, "persist": False},
            response=(
                {
                    "instrument_id": "600030.SH",
                    "symbol": "600030",
                    "exchange": "SSE",
                    "prospectus_announcement_date": "20021213",
                    "lottery_rate_announcement_date": None,
                    "par_value": 1.0,
                    "total_issue_shares": 40000.0,
                    "nav_per_share_before_issue": 1.67,
                    "diluted_pe": 15.0,
                    "raised_funds_net": 175967.3375,
                    "online_issue_date": "20021217",
                    "listing_date": "20030106",
                    "issue_price": 4.5,
                    "issue_expenses_total": 4032.6625,
                    "nav_per_share_after_issue": 2.11,
                    "online_lottery_rate": 0.282,
                    "lead_underwriter": "广发证券股份有限公司",
                },
            ),
        ),
    ),
    "stock_new_gh_cninfo": SourceRequestInterface(
        name="stock_new_gh_cninfo",
        display_name_zh="新股过会",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="新股数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮新股过会列表，默认只返回本地 limit 条且不入库。",
        source_ability="Cninfo IPO meeting approval list webapi",
        description="Return IPO meeting approval rows from Cninfo. limit is applied after source retrieval.",
        parameters=(
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_NEW_GH_FIELDS,
        example=RequestExample(
            request={"params": {"limit": 1}, "persist": False},
            response=(),
        ),
    ),
    "stock_new_ipo_cninfo": SourceRequestInterface(
        name="stock_new_ipo_cninfo",
        display_name_zh="新股发行",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="新股数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮新股发行列表，默认只返回本地 limit 条且不入库。",
        source_ability="Cninfo new IPO issue list webapi",
        description="Return new IPO issue rows from Cninfo. limit is applied after source retrieval.",
        parameters=(
            RequestParameter("time_type", "string/integer", False, "Source time type.", "源端时间范围参数 timetype，默认 36。", "36"),
            RequestParameter("market", "string", False, "Source market code.", "源端市场代码，默认 ALL。", "ALL"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_NEW_IPO_FIELDS,
        example=RequestExample(
            request={"params": {"time_type": "36", "market": "ALL", "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "301583.SZ",
                    "symbol": "301583",
                    "exchange": "SZSE",
                    "name": "托伦斯",
                    "listing_date": None,
                    "subscription_date": "20260629",
                    "issue_price": 22.6,
                    "total_issue_shares": 4636.8423,
                    "issue_pe": 44.82,
                    "online_lottery_rate": 0.01526105,
                    "lottery_result_announcement_date": "20260701",
                    "winning_announcement_date": "20260630",
                    "payment_date": "20260701",
                    "online_subscription_limit": 0.95,
                    "online_issue_shares": 1622.9,
                },
            ),
        ),
    ),
    "stock_share_change_cninfo": SourceRequestInterface(
        name="stock_share_change_cninfo",
        display_name_zh="公司股本变动",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮单股公司股本变动 webapi，默认不入库。",
        source_ability="Cninfo single-stock share-capital change webapi",
        description=(
            "Return share-capital change rows for one A-share security. "
            "Dates are normalized to YYYYMMDD; capital fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 002594、002594.SZ。"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 19900101。", "19900101"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20991231。", "20991231"),
        ),
        fields=STOCK_SHARE_CHANGE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "002594.SZ",
                    "start_date": "20091227",
                    "end_date": "20241021",
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "002594.SZ",
                    "symbol": "002594",
                    "exchange": "SZSE",
                    "name": "比亚迪",
                    "organization_name": "比亚迪股份有限公司",
                    "announcement_date": "20110823",
                    "change_date": "20110630",
                    "change_reason_code": "015001,015019",
                    "change_reason": "A股上市,定期报告",
                    "total_share": 235410.0,
                    "non_circulating_share": 0.0,
                    "promoter_share": 0.0,
                    "state_share": None,
                    "state_owned_legal_person_share": None,
                    "domestic_legal_person_share": None,
                    "foreign_legal_person_share": None,
                    "natural_person_share": None,
                    "raised_legal_person_share": None,
                    "employee_share": None,
                    "transferred_share": None,
                    "other_restricted_share": 148200.0,
                    "preferred_share": None,
                    "other_non_circulating_share": None,
                    "circulating_share": 85710.0,
                    "a_share": 6400.0,
                    "b_share": 0.0,
                    "h_share": 79310.0,
                    "executive_share": 0.0,
                    "other_circulating_share": 0.0,
                    "restricted_share": 149700.0,
                    "allocated_legal_person_share": 1500.0,
                    "strategic_investor_share": None,
                    "securities_investment_fund_share": 0.0,
                    "general_legal_person_share": 1500.0,
                    "state_restricted_share": 0.0,
                    "state_owned_legal_person_restricted_share": None,
                    "other_domestic_restricted_share": 146457.396,
                    "domestic_legal_person_restricted_share": 16939.146,
                    "domestic_natural_person_restricted_share": 129518.25,
                    "foreign_restricted_share": 1742.604,
                    "foreign_legal_person_restricted_share": 1742.604,
                    "foreign_natural_person_restricted_share": 0.0,
                    "restricted_executive_share": None,
                    "restricted_b_share": None,
                    "restricted_h_share": None,
                    "controlling_shareholder_actual_controller_share": None,
                },
            ),
        ),
    ),
    "fund_report_asset_allocation_cninfo": SourceRequestInterface(
        name="fund_report_asset_allocation_cninfo",
        display_name_zh="基金资产配置",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="基金报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮基金资产配置专题统计，默认不入库。",
        source_ability="Cninfo fund asset allocation thematic webapi",
        description="Return fund-market asset allocation rows from Cninfo thematic statistics.",
        parameters=(),
        fields=FUND_ASSET_ALLOCATION_FIELDS,
        example=RequestExample(
            request={"params": {}, "persist": False},
            response=(
                {
                    "report_date": "20260331",
                    "fund_count": 13659.0,
                    "equity_asset_pct": 21.68,
                    "bond_asset_pct": 56.75,
                    "cash_asset_pct": 16.84,
                    "fund_market_net_assets": 371430.37,
                },
            ),
        ),
    ),
    "fund_report_industry_allocation_cninfo": SourceRequestInterface(
        name="fund_report_industry_allocation_cninfo",
        display_name_zh="基金行业配置",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="基金报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮基金行业配置专题统计，按报告期返回，默认不入库。",
        source_ability="Cninfo fund industry allocation thematic webapi",
        description=(
            "Return fund industry-allocation rows from Cninfo thematic statistics. "
            "date should usually be a quarter-end report date from 2017 onward."
        ),
        parameters=(
            RequestParameter("date", "string", False, "Report date.", "报告期日期，YYYYMMDD 或 YYYY-MM-DD；通常为季末日期，默认 20210630。", "20210630"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=FUND_INDUSTRY_ALLOCATION_FIELDS,
        example=RequestExample(
            request={"params": {"date": "20210630", "limit": 1}, "persist": False},
            response=(
                {
                    "industry_code": "A",
                    "industry_name": "农、林、牧、渔业",
                    "report_date": "20210630",
                    "fund_count": 3164.0,
                    "industry_scale": 227.13,
                    "net_asset_pct": 0.1,
                },
            ),
        ),
    ),
    "fund_report_stock_cninfo": SourceRequestInterface(
        name="fund_report_stock_cninfo",
        display_name_zh="基金重仓股",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="基金报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮基金重仓股专题统计，按报告期返回，默认不入库。",
        source_ability="Cninfo fund heavy-stock thematic webapi",
        description=(
            "Return fund heavy-stock rows from Cninfo thematic statistics. "
            "date should usually be a quarter-end report date."
        ),
        parameters=(
            RequestParameter("date", "string", False, "Report date.", "报告期日期，YYYYMMDD 或 YYYY-MM-DD；通常为季末日期，默认 20210630。", "20210630"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=FUND_STOCK_FIELDS,
        example=RequestExample(
            request={"params": {"date": "20210630", "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "605011.SH",
                    "symbol": "605011",
                    "exchange": "SSE",
                    "record_id": "1.0",
                    "name": "杭州热电",
                    "report_date": "20210630",
                    "fund_count": 3723.0,
                    "holding_shares": 1929150.0,
                    "holding_market_value": 1713.09,
                },
            ),
        ),
    ),
    "stock_cg_equity_mortgage_cninfo": SourceRequestInterface(
        name="stock_cg_equity_mortgage_cninfo",
        display_name_zh="股权质押",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公司治理",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮股权质押专题统计，按统计日期返回，默认不入库。",
        source_ability="Cninfo equity mortgage thematic webapi",
        description=(
            "Return equity mortgage rows from Cninfo corporate-governance statistics. "
            "date is normalized to YYYYMMDD and passed to the source as tdate."
        ),
        parameters=(
            RequestParameter("date", "string", False, "Statistic date.", "统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210930。", "20210930"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_CG_EQUITY_MORTGAGE_FIELDS,
        example=RequestExample(
            request={"params": {"date": "20210930", "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "000510.SZ",
                    "symbol": "000510",
                    "exchange": "SZSE",
                    "stat_date": "20210930",
                    "name": "新金路",
                    "announcement_date": "20210930",
                    "pledgor": "刘江东",
                    "pledgee": "华创证券有限责任公司",
                    "pledged_shares": None,
                    "pledged_total_share_pct": 1.31,
                    "released_pledge_shares": 800.0,
                    "pledge_event": (
                        "本公司实际控制人、第一大股东、高管成员刘江东将2017年11月23日质押给"
                        "华创证券有限责任公司的8000000股解除质押，解除日期为2021年09月28日。"
                    ),
                    "cumulative_pledge_total_share_pct": 8.74,
                },
            ),
        ),
    ),
    "stock_cg_guarantee_cninfo": SourceRequestInterface(
        name="stock_cg_guarantee_cninfo",
        display_name_zh="对外担保",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公司治理",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮对外担保专题统计，按公告区间和市场返回，默认不入库。",
        source_ability="Cninfo external guarantee thematic webapi",
        description=(
            "Return external guarantee summary rows from Cninfo corporate-governance statistics. "
            "market uses Cninfo board labels such as 全部、沪市、深市主板、创业板、科创板."
        ),
        parameters=(
            RequestParameter("market", "string", False, "Market board.", "市场板块：全部、沪市、深市主板、创业板、科创板；默认 全部。", "全部"),
            RequestParameter("start_date", "string", False, "Start date.", "公告统计开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 20180630。", "20180630"),
            RequestParameter("end_date", "string", False, "End date.", "公告统计结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210927。", "20210927"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_CG_GUARANTEE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "market": "全部",
                    "start_date": "20180630",
                    "end_date": "20210927",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "000031.SZ",
                    "symbol": "000031",
                    "exchange": "SZSE",
                    "name": "大悦城",
                    "announcement_period": "2018-06-30---2021-09-27",
                    "guarantee_count": 190.0,
                    "guarantee_amount": 24667281.89,
                    "parent_equity": 1022714.87,
                    "guarantee_amount_net_asset_pct": 2411.94,
                },
            ),
        ),
    ),
    "stock_cg_lawsuit_cninfo": SourceRequestInterface(
        name="stock_cg_lawsuit_cninfo",
        display_name_zh="公司诉讼",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公司治理",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮公司诉讼专题统计，按公告区间和市场返回，默认不入库。",
        source_ability="Cninfo company lawsuit thematic webapi",
        description=(
            "Return company lawsuit summary rows from Cninfo corporate-governance statistics. "
            "market uses Cninfo board labels such as 全部、沪市、深市主板、创业板、科创板."
        ),
        parameters=(
            RequestParameter("market", "string", False, "Market board.", "市场板块：全部、沪市、深市主板、创业板、科创板；默认 沪市。", "沪市"),
            RequestParameter("start_date", "string", False, "Start date.", "公告统计开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 20180630。", "20180630"),
            RequestParameter("end_date", "string", False, "End date.", "公告统计结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210927。", "20210927"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_CG_LAWSUIT_FIELDS,
        example=RequestExample(
            request={"params": {"market": "沪市", "start_date": "20180630", "end_date": "20210927", "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "603507.SH",
                    "symbol": "603507",
                    "exchange": "SSE",
                    "name": "振江股份",
                    "announcement_period": "2018-06-30---2021-09-27",
                    "lawsuit_count": 1.0,
                    "lawsuit_amount": None,
                },
            ),
        ),
    ),
    "stock_hold_management_detail_cninfo": SourceRequestInterface(
        name="stock_hold_management_detail_cninfo",
        display_name_zh="高管持股变动明细",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="股本股东",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮高管持股变动明细，按变动类型和公告区间返回，默认不入库。",
        source_ability="Cninfo management holding change detail webapi",
        description=(
            "Return management holding-change detail rows from Cninfo shareholder statistics. "
            "change_type maps to the source varytype parameter."
        ),
        parameters=(
            RequestParameter("change_type", "string", False, "Change type.", "变动类型：增持、减持；默认 增持。", "增持"),
            RequestParameter("start_date", "string", False, "Start date.", "公告开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 20240101。", "20240101"),
            RequestParameter("end_date", "string", False, "End date.", "公告结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20241231。", "20241231"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_HOLD_MANAGEMENT_DETAIL_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "change_type": "增持",
                    "start_date": "20240101",
                    "end_date": "20241231",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "000034.SZ",
                    "symbol": "000034",
                    "exchange": "SZSE",
                    "name": "神州数码",
                    "change_type": "增持",
                    "end_date": "20240630",
                    "announcement_date": "20240831",
                    "executive_name": "李岩",
                    "director_supervisor_senior_name": "李岩",
                    "director_supervisor_senior_position": None,
                    "changer_relation": None,
                    "beginning_holding_shares": 16.88,
                    "ending_holding_shares": 18.38,
                    "change_shares": 15000.0,
                    "change_ratio": None,
                    "average_price": None,
                    "ending_market_value": None,
                    "change_reason": None,
                    "data_source": "定期报告",
                },
            ),
        ),
    ),
    "stock_industry_change_cninfo": SourceRequestInterface(
        name="stock_industry_change_cninfo",
        display_name_zh="行业归属变动",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="行业数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮上市公司行业归属变动，按单只股票和日期区间返回，默认不入库。",
        source_ability="Cninfo stock industry change webapi",
        description=(
            "Return stock industry-classification change rows from Cninfo. "
            "Dates are normalized to YYYYMMDD."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 002594、002594.SZ。"),
            RequestParameter("start_date", "string", False, "Start date.", "变动开始日期，YYYYMMDD 或 YYYY-MM-DD；默认 20091227。", "20091227"),
            RequestParameter("end_date", "string", False, "End date.", "变动结束日期，YYYYMMDD 或 YYYY-MM-DD；默认 20220713。", "20220713"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_INDUSTRY_CHANGE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "code": "002594.SZ",
                    "start_date": "20091227",
                    "end_date": "20220713",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "instrument_id": "002594.SZ",
                    "symbol": "002594",
                    "exchange": "SZSE",
                    "name": "比亚迪",
                    "organization_name": "比亚迪股份有限公司",
                    "change_date": "20110608",
                    "classification_standard_code": "008004",
                    "classification_standard": "新财富行业分类标准",
                    "industry_code": "N13",
                    "industry_sector": "汽车和汽车零部件",
                    "industry_subcategory": "汽车和汽车零部件",
                    "industry_major": "汽车和汽车零部件",
                    "industry_middle": "汽车和汽车零部件",
                    "latest_record_flag": "1",
                },
            ),
        ),
    ),
    "stock_industry_pe_ratio_cninfo": SourceRequestInterface(
        name="stock_industry_pe_ratio_cninfo",
        display_name_zh="行业市盈率",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="行业数据",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮行业市盈率专题统计，按日期和行业分类返回，默认不入库。",
        source_ability="Cninfo industry PE ratio thematic webapi",
        description=(
            "Return industry PE-ratio rows from Cninfo industry analysis. "
            "classification supports 证监会行业分类、国证行业分类 or source sortcode."
        ),
        parameters=(
            RequestParameter("classification", "string", False, "Industry classification.", "行业分类：证监会行业分类、国证行业分类；也支持 008001、008200；默认 证监会行业分类。", "证监会行业分类"),
            RequestParameter("date", "string", False, "Query date.", "查询日期，YYYYMMDD 或 YYYY-MM-DD；默认 20240617。", "20240617"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_INDUSTRY_PE_RATIO_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "classification": "证监会行业分类",
                    "date": "20240617",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "change_date": "20240617",
                    "classification": "中国上市公司协会上市公司行业分类标准",
                    "industry_level": 1,
                    "industry_code": "A",
                    "industry_name": "农、林、牧、渔业",
                    "company_count": 44.0,
                    "included_company_count": 25.0,
                    "total_market_value_static": 1763.9036,
                    "net_profit_static": 162.8539,
                    "static_pe_weighted": 10.83,
                    "static_pe_median": 30.31,
                    "static_pe_mean": 50.03,
                },
            ),
        ),
    ),
    "stock_rank_forecast_cninfo": SourceRequestInterface(
        name="stock_rank_forecast_cninfo",
        display_name_zh="投资评级",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="评级预测",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮投资评级专题统计，按日期返回，默认不入库。",
        source_ability="Cninfo stock investment-rating forecast webapi",
        description=(
            "Return investment-rating forecast rows from Cninfo rating statistics. "
            "Target prices keep source units and may be null."
        ),
        parameters=(
            RequestParameter("date", "string", False, "Query date.", "查询日期，YYYYMMDD 或 YYYY-MM-DD；默认 20230817。", "20230817"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=STOCK_RANK_FORECAST_FIELDS,
        example=RequestExample(
            request={"params": {"date": "20230817", "limit": 1}, "persist": False},
            response=(
                {
                    "instrument_id": "000552.SZ",
                    "symbol": "000552",
                    "exchange": "SZSE",
                    "name": "甘肃能化",
                    "publish_date": "20230817",
                    "institution_short_name": "民生证券",
                    "analyst_name": "周泰,李航",
                    "rating": "增持",
                    "is_first_rating": "不是首次评级",
                    "rating_change": "维持",
                    "previous_rating": "增持",
                    "target_price_low": None,
                    "target_price_high": None,
                },
            ),
        ),
    ),
    "bond_corporate_issue_cninfo": SourceRequestInterface(
        name="bond_corporate_issue_cninfo",
        display_name_zh="企业债发行",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="债券报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮企业债发行专题统计，按日期范围返回，默认不入库。",
        source_ability="Cninfo corporate bond issue thematic webapi",
        description=(
            "Return corporate bond issue rows from Cninfo thematic statistics. "
            "Date fields are normalized to YYYYMMDD; amount fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("start_date", "string", False, "Start date.", "开始统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210911。", "20210911"),
            RequestParameter("end_date", "string", False, "End date.", "结束统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20211110。", "20211110"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=BOND_CORPORATE_ISSUE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "start_date": "20210911",
                    "end_date": "20211110",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "bond_code": "184109",
                    "bond_short_name": "21开泰01",
                    "announcement_date": "20211104",
                    "online_issue_start_date": "20211110",
                    "online_issue_end_date": "20211112",
                    "planned_issue_amount": 80000.0,
                    "actual_issue_amount": 80000.0,
                    "par_value": 100.0,
                    "issue_price": 100.0,
                    "issue_method": "交易所系统网下向机构投资者协议发行,承销团成员设置的发行网点向境内机构投资者发行",
                    "issue_target": (
                        "在承销团成员设置的发行网点发行对象为在中央国债登记公司开户的中国境内机构投资者"
                        "（国家法律、法规另有规定者除外）；在上海证券交易所市场的发行对象为在中国证券登记公司"
                        "上海分公司开立合格基金证券账户或A股证券账户的机构投资者（国家法律、法规禁止购买者除外）。"
                    ),
                    "issue_scope": "银行间市场,上交所固定收益平台,债券柜台交易市场,上海证券交易所",
                    "underwriting_method": "余额包销",
                    "min_subscription_unit": 1000000.0,
                    "fundraising_use": "如东县县城停车场建设项目,补充公司营运资金",
                    "min_subscription_amount": 10000000.0,
                    "bond_name": "2021年如东县开泰城建投资有限公司城市停车场建设专项债券(品种一)",
                },
            ),
        ),
    ),
    "bond_cov_issue_cninfo": SourceRequestInterface(
        name="bond_cov_issue_cninfo",
        display_name_zh="可转债发行",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="债券报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮可转债发行专题统计，按日期范围返回，默认不入库。",
        source_ability="Cninfo convertible bond issue thematic webapi",
        description=(
            "Return convertible bond issue rows from Cninfo thematic statistics. "
            "Date fields are normalized to YYYYMMDD; amount fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("start_date", "string", False, "Start date.", "开始统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210913。", "20210913"),
            RequestParameter("end_date", "string", False, "End date.", "结束统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20211112。", "20211112"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=BOND_COV_ISSUE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "start_date": "20210913",
                    "end_date": "20211112",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "bond_code": "110083",
                    "bond_short_name": "苏租转债",
                    "announcement_date": "20211109",
                    "issue_start_date": "20211111",
                    "issue_end_date": "20211111",
                    "planned_issue_amount": 500000.0,
                    "actual_issue_amount": 500000.0,
                    "par_value": 100.0,
                    "issue_price": 100.0,
                    "issue_method": "网上网下优先配售,交易所系统网上向社会公众投资者发行",
                    "issue_target": (
                        "本次可转债的发行对象为持有中国证券登记结算有限责任公司上海分公司证券账户的自然人、"
                        "法人、证券投资基金、符合法律规定的其他投资者等（国家法律、法规禁止者除外）。"
                    ),
                    "issue_scope": "上交所固定收益平台",
                    "underwriting_method": "余额包销",
                    "fundraising_use": "补充公司的核心一级资本",
                    "initial_conversion_price": 5.42,
                    "conversion_start_date": "20220517",
                    "conversion_end_date": "20211110",
                    "online_subscription_date": "20211111",
                    "online_subscription_code": "733901",
                    "online_subscription_short_name": "苏租发债",
                    "online_subscription_max": 100.0,
                    "online_subscription_min": 0.1,
                    "online_subscription_unit": 0.1,
                    "online_lottery_result_refund_date": "20211115",
                    "priority_subscription_date": "20211111",
                    "allotment_price": 100.0,
                    "bondholder_record_date": "20241017",
                    "priority_subscription_payment_date": "20211111",
                    "conversion_code": "600901",
                    "trading_market": "上交所",
                    "bond_name": "2021年江苏金融租赁股份有限公司公开发行A股可转换公司债券",
                },
            ),
        ),
    ),
    "bond_cov_stock_issue_cninfo": SourceRequestInterface(
        name="bond_cov_stock_issue_cninfo",
        display_name_zh="可转债转股",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="债券报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮可转债转股专题统计，默认不入库。",
        source_ability="Cninfo convertible bond conversion thematic webapi",
        description=(
            "Return convertible bond conversion rows from Cninfo thematic statistics. "
            "Date fields are normalized to YYYYMMDD; price fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000；该参数为 AxData 本地裁剪。", 100),
        ),
        fields=BOND_COV_STOCK_ISSUE_FIELDS,
        example=RequestExample(
            request={"params": {"limit": 1}, "persist": False},
            response=(
                {
                    "bond_code": "132024",
                    "bond_short_name": "26江铜EB",
                    "announcement_date": "20260402",
                    "conversion_code": None,
                    "conversion_short_name": None,
                    "conversion_price": 53.0,
                    "voluntary_conversion_start_date": "20270412",
                    "voluntary_conversion_end_date": "20310409",
                    "underlying_stock": "600362",
                    "bond_name": "2026年江西铜业集团有限公司面向专业投资者公开发行可交换公司债券",
                },
            ),
        ),
    ),
    "bond_local_government_issue_cninfo": SourceRequestInterface(
        name="bond_local_government_issue_cninfo",
        display_name_zh="地方债发行",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="债券报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮地方债发行专题统计，按日期范围返回，默认不入库。",
        source_ability="Cninfo local-government bond issue thematic webapi",
        description=(
            "Return local-government bond issue rows from Cninfo thematic statistics. "
            "Date fields are normalized to YYYYMMDD; amount fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("start_date", "string", False, "Start date.", "开始统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210911。", "20210911"),
            RequestParameter("end_date", "string", False, "End date.", "结束统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20211110。", "20211110"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=BOND_PUBLIC_ISSUE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "start_date": "20210911",
                    "end_date": "20211110",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "bond_code": "186882",
                    "bond_short_name": "21兵团11",
                    "issue_start_date": "20211110",
                    "issue_end_date": "20211110",
                    "planned_issue_amount": 3.633,
                    "actual_issue_amount": 3.633,
                    "issue_price": 100.0,
                    "par_value": 100.0,
                    "payment_date": "20211111",
                    "additional_issue_count": 0.0,
                    "trading_market": "上交所",
                    "issue_method": "荷兰式招标发行",
                    "issue_target": None,
                    "announcement_date": "20211103",
                    "bond_name": "2021年新疆维吾尔自治区(新疆生产建设兵团)再融资一般债券(二期)",
                },
            ),
        ),
    ),
    "bond_treasure_issue_cninfo": SourceRequestInterface(
        name="bond_treasure_issue_cninfo",
        display_name_zh="国债发行",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="债券报表",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮国债发行专题统计，按日期范围返回，默认不入库。",
        source_ability="Cninfo treasury bond issue thematic webapi",
        description=(
            "Return treasury bond issue rows from Cninfo thematic statistics. "
            "Date fields are normalized to YYYYMMDD; amount fields keep Cninfo source units."
        ),
        parameters=(
            RequestParameter("start_date", "string", False, "Start date.", "开始统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20210910。", "20210910"),
            RequestParameter("end_date", "string", False, "End date.", "结束统计日期，YYYYMMDD 或 YYYY-MM-DD；默认 20211109。", "20211109"),
            RequestParameter("limit", "integer", False, "Maximum rows returned, capped at 1000.", "最多返回行数，默认 100，最大 1000。", 100),
        ),
        fields=BOND_PUBLIC_ISSUE_FIELDS,
        example=RequestExample(
            request={
                "params": {
                    "start_date": "20210910",
                    "end_date": "20211109",
                    "limit": 1,
                },
                "persist": False,
            },
            response=(
                {
                    "bond_code": "020450",
                    "bond_short_name": "21贴债53",
                    "issue_start_date": "20211105",
                    "issue_end_date": "20211105",
                    "planned_issue_amount": 500.0,
                    "actual_issue_amount": 500.0,
                    "issue_price": 98.91,
                    "par_value": 100.0,
                    "payment_date": "20211108",
                    "additional_issue_count": 0.0,
                    "trading_market": "上交所",
                    "issue_method": "多种价格（混合式）招标发行",
                    "issue_target": "在国债登记公司开立债券账户及在证券登记公司开立股票和基金账户的各类投资者",
                    "announcement_date": "20211029",
                    "bond_name": "2021年记账式贴现(五十三期)国债",
                },
            ),
        ),
    ),
    "stock_profile_cninfo": SourceRequestInterface(
        name="stock_profile_cninfo",
        display_name_zh="公司概况",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公司资料",
        request_mode="source_request",
        first_stage_strategy="临时请求巨潮公司概况 webapi，返回单家公司资料，默认不入库。",
        source_ability="Cninfo company profile webapi",
        description=(
            "Return company profile rows from Cninfo webapi. Dates are normalized to YYYYMMDD; "
            "registered_capital keeps the source unit and caliber."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 600030、600030.SH。"),
        ),
        fields=STOCK_PROFILE_FIELDS,
        example=RequestExample(
            request={"params": {"code": "600030.SH"}, "persist": False},
            response=(
                {
                    "instrument_id": "600030.SH",
                    "symbol": "600030",
                    "exchange": "SSE",
                    "company_name": "中信证券股份有限公司",
                    "english_name": "CITIC Securities Company Limited",
                    "former_short_name": None,
                    "a_share_code": "600030",
                    "a_share_name": "中信证券",
                    "b_share_code": None,
                    "b_share_name": None,
                    "h_share_code": "06030",
                    "h_share_name": "中信证券",
                    "selected_indexes": "分析师指数,国证Ａ指,国证红利,沪深300,巨潮100,巨潮大盘,上证180,上证50,中证央企",
                    "market": "上交所",
                    "industry": "资本市场服务",
                    "legal_representative": "张佑君",
                    "registered_capital": 1482054.6829,
                    "founded_date": "19951025",
                    "listing_date": "20030106",
                    "website": "www.citics.com",
                    "email": "ir@citics.com",
                    "phone": "0755-23835888",
                    "fax": "0755-23835861",
                    "registered_address": "广东省深圳市福田区中心三路8号卓越时代广场(二期)北座",
                    "office_address": "北京市朝阳区亮马桥路48号中信证券大厦；广东省深圳市福田区中心三路8号中信证券大厦",
                    "postcode": "100026",
                    "main_business": "主要从事证券承销和上市推荐证券自营买卖资产管理和证券代理买卖等业务。",
                    "business_scope": "证券经纪（限山东省、河南省、浙江省天台县、浙江省苍南县以外区域）；证券投资咨询；与证券交易、证券投资活动有关的财务顾问；证券承销与保荐；证券自营；证券资产管理；融资融券；证券投资基金代销；为期货公司提供中间介绍业务；代销金融产品；股票期权做市。",
                    "organization_profile": "公司的前身中信证券有限责任公司是经中国人民银行银复[1995]313号文批准，由中信公司，中信兴业信托投资公司，中信上海信托投资公司和中信宁波公司于1995年10月25日出资设立的。",
                },
            ),
        ),
    ),
    "cninfo_announcement_detail": SourceRequestInterface(
        name="cninfo_announcement_detail",
        display_name_zh="公告PDF元信息",
        source_code="cninfo",
        source_name_zh="巨潮",
        category="公告数据",
        request_mode="source_request",
        first_stage_strategy="只确认公告 PDF 的类型、大小和下载地址，默认不解析正文、不入库。",
        source_ability="Cninfo announcement PDF metadata",
        description=(
            "Return PDF metadata for a Cninfo announcement URL. This interface does not parse PDF text."
        ),
        parameters=(
            RequestParameter("announcement_id", "string", False, "Announcement id.", "公告 ID；可选。"),
            RequestParameter("url", "string", True, "PDF path or URL.", "公告 PDF 路径或完整 URL。"),
            RequestParameter("title", "string", False, "Optional title passed through.", "可选公告标题，用于透传。"),
        ),
        fields=(
            RequestField("announcement_id", "string", "Announcement id.", "公告 ID。"),
            RequestField("title", "string", "Announcement title if provided.", "公告标题；传入时返回。"),
            RequestField("content_type", "string", "HTTP content type.", "文件类型，例如 application/pdf。"),
            RequestField("file_size_bytes", "integer", "File size in bytes.", "文件大小，单位：字节。"),
            RequestField("download_url", "string", "PDF download URL.", "PDF 下载地址。"),
        ),
        example=RequestExample(
            request={
                "params": {
                    "announcement_id": "1218968511",
                    "url": "https://static.cninfo.com.cn/finalpage/2024-01-23/1218968511.PDF",
                },
                "persist": False,
            },
            response=(
                {
                    "announcement_id": "1218968511",
                    "title": None,
                    "content_type": "application/pdf",
                    "file_size_bytes": 158287,
                    "download_url": "https://static.cninfo.com.cn/finalpage/2024-01-23/1218968511.PDF",
                },
            ),
        ),
    ),
}
