"""CLS source request interface catalog."""

from __future__ import annotations

from axdata_core.sources.base import (
    RequestExample,
    RequestField,
    RequestParameter,
    SourceRequestInterface,
)


def P(
    name: str,
    dtype: str,
    required: bool,
    zh: str,
    default: object | None = None,
) -> RequestParameter:
    return RequestParameter(name, dtype, required, name, zh, default)


def F(name: str, dtype: str, zh: str) -> RequestField:
    return RequestField(name, dtype, name, zh)


SECURITY_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。"),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("secu_code", "string", "财联社证券代码，例如 sh600000。"),
    F("secu_name", "string", "证券简称。"),
)


INTERFACES: dict[str, SourceRequestInterface] = {
    "cls_market_emotion": SourceRequestInterface(
        name="cls_market_emotion",
        display_name_zh="市场情绪",
        source_code="cls",
        source_name_zh="财联社",
        category="情绪数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社市场情绪快照，默认不入库。",
        source_ability="CLS A-share market emotion snapshot",
        description="Return CLS market emotion snapshot as one row.",
        parameters=(),
        fields=(
            F("market_degree", "float64", "市场热度。"),
            F("shsz_balance", "string", "两市成交额文字。"),
            F("preview_balance", "string", "预测量能文字。"),
            F("up_ratio", "string", "封板率文字。"),
            F("up_ratio_num", "integer", "封板数量。"),
            F("up_open_num", "integer", "触及涨停数量。"),
            F("performance", "string", "昨日涨停今日表现。"),
            F("rise_num", "integer", "上涨家数。"),
            F("fall_num", "integer", "下跌家数。"),
            F("flat_num", "integer", "平盘家数。"),
            F("up_num", "integer", "涨停家数。"),
            F("down_num", "integer", "跌停家数。"),
            F("raw_up_down_dis", "object/string", "涨跌分布原始摘要。"),
            F("raw_limit_up_board", "object/string", "连板分布原始摘要。"),
        ),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"market_degree": 59, "up_num": 127},)),
    ),
    "cls_market_wind": SourceRequestInterface(
        name="cls_market_wind",
        display_name_zh="今日风口板块",
        source_code="cls",
        source_name_zh="财联社",
        category="题材数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社今日风口板块，默认不入库。",
        source_ability="CLS today tuyere sectors",
        description="Return today's tuyere sector list.",
        parameters=(),
        fields=(F("plate_code", "string", "板块代码。"), F("plate_name", "string", "板块名称。"), F("catalyst", "string", "催化剂/解读。")),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"plate_code": "cls80198", "plate_name": "锂电池"},)),
    ),
    "cls_market_wind_stocks": SourceRequestInterface(
        name="cls_market_wind_stocks",
        display_name_zh="风口板块龙头股",
        source_code="cls",
        source_name_zh="财联社",
        category="题材数据",
        request_mode="source_request",
        first_stage_strategy="按财联社板块代码请求风口龙头股，默认不入库。",
        source_ability="CLS tuyere sector stocks",
        description="Return lead stocks for one CLS tuyere sector.",
        parameters=(P("plate_code", "string", True, "板块代码，例如 cls80198。"),),
        fields=(*SECURITY_FIELDS, F("last_price", "float64", "最新价。"), F("change_pct", "float64", "涨跌幅。"), F("continuous_count", "integer", "连板数。")),
        example=RequestExample(request={"params": {"plate_code": "cls80198"}, "persist": False}, response=({"secu_code": "sh603929", "secu_name": "亚翔集成"},)),
    ),
    "cls_market_mainline": SourceRequestInterface(
        name="cls_market_mainline",
        display_name_zh="今日主线机会",
        source_code="cls",
        source_name_zh="财联社",
        category="题材数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社今日主线机会，默认不入库。",
        source_ability="CLS today mainline opportunities",
        description="Return mainline opportunity blocks flattened from CLS payload.",
        parameters=(),
        fields=(F("block_key", "string", "主线块键名。"), F("title", "string", "标题。"), F("summary", "string", "摘要。"), F("raw_item", "object/string", "原始块摘要。")),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"block_key": "faucet_1", "title": "AI主线"},)),
    ),
    "cls_sector_industry": SourceRequestInterface(
        name="cls_sector_industry",
        display_name_zh="行业板块实时行情",
        source_code="cls",
        source_name_zh="财联社",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社行业板块实时行情，默认不入库。",
        source_ability="CLS industry sector realtime quotes",
        description="Return CLS industry sector quote rows.",
        parameters=(),
        fields=(
            F("plate_code", "string", "板块代码。"),
            F("plate_name", "string", "板块名称。"),
            F("change_pct", "float64", "涨跌幅。"),
            F("main_fund_diff", "float64", "主力净流入。"),
            F("rise_count", "integer", "上涨家数。"),
            F("fall_count", "integer", "下跌家数。"),
            F("limit_up_count", "integer", "涨停家数。"),
            F("limit_down_count", "integer", "跌停家数。"),
            F("trade_status", "string", "交易状态。"),
            F("raw_first_stock", "object/string", "领涨股原始摘要。"),
        ),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"plate_code": "cls82074", "plate_name": "通信"},)),
    ),
    "cls_sector_heat": SourceRequestInterface(
        name="cls_sector_heat",
        display_name_zh="板块热度排行",
        source_code="cls",
        source_name_zh="财联社",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社板块热度排行，默认不入库。",
        source_ability="CLS sector heat ranking",
        description="Return CLS sector heat ranking.",
        parameters=(),
        fields=(F("plate_code", "string", "板块代码。"), F("plate_name", "string", "板块名称。"), F("rank", "integer", "当前排名。"), F("cur_heat", "float64", "当前热度。"), F("rank_change", "integer", "排名变化。"), F("is_new", "boolean", "是否新上榜。")),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"plate_code": "cls80195", "plate_name": "半导体芯片"},)),
    ),
    "cls_sector_popular_stocks": SourceRequestInterface(
        name="cls_sector_popular_stocks",
        display_name_zh="板块热门股",
        source_code="cls",
        source_name_zh="财联社",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="按财联社板块代码请求近期热门股，默认不入库。",
        source_ability="CLS sector popular stocks",
        description="Return popular stocks for one CLS sector.",
        parameters=(P("plate_code", "string", True, "板块代码，例如 cls80025。"),),
        fields=(*SECURITY_FIELDS, F("change_text", "string", "涨跌幅文字。"), F("change", "float64", "涨跌幅数值。"), F("change_px", "float64", "涨跌额。"), F("board_tag", "string", "连板/强势标签。"), F("head_rank", "integer", "龙头排名。")),
        example=RequestExample(request={"params": {"plate_code": "cls80025"}, "persist": False}, response=({"secu_code": "sz002552", "secu_name": "宝鼎科技"},)),
    ),
    "cls_sector_rotation": SourceRequestInterface(
        name="cls_sector_rotation",
        display_name_zh="板块轮动",
        source_code="cls",
        source_name_zh="财联社",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="请求近 N 日每日涨幅靠前板块，默认不入库。",
        source_ability="CLS sector rotation",
        description="Return flattened CLS sector rotation rows.",
        parameters=(P("days", "integer", False, "查询天数，默认 4。", 4),),
        fields=(F("trade_date", "date/string", "交易日期。"), F("plate_code", "string", "板块代码。"), F("plate_name", "string", "板块名称。"), F("change_pct", "float64", "涨跌幅。"), F("rank", "integer", "当日排名。")),
        example=RequestExample(request={"params": {"days": 4}, "persist": False}, response=({"trade_date": "20260522", "plate_name": "MLCC", "rank": 1},)),
    ),
    "cls_limit_up_pool": SourceRequestInterface(
        name="cls_limit_up_pool",
        display_name_zh="涨停池含原因",
        source_code="cls",
        source_name_zh="财联社",
        category="短线数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社当日涨停池，包含涨停原因，默认不入库。",
        source_ability="CLS current limit-up pool with reasons",
        description="Return current CLS limit-up pool rows.",
        parameters=(),
        fields=(*SECURITY_FIELDS, F("last_price", "float64", "最新价。"), F("change_pct", "float64", "涨跌幅。"), F("up_reason", "string", "涨停原因。")),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"secu_code": "sh603929", "up_reason": "新能源汽车概念"},)),
    ),
    "cls_stock_timeline": SourceRequestInterface(
        name="cls_stock_timeline",
        display_name_zh="个股分时",
        source_code="cls",
        source_name_zh="财联社",
        category="实时数据",
        request_mode="source_request",
        first_stage_strategy="请求单只股票当日分时，默认不入库。",
        source_ability="CLS stock timeline",
        description="Return intraday timeline rows for one stock.",
        parameters=(P("code", "string", True, "股票代码，支持 002664 或 002664.SZ。"),),
        fields=(*SECURITY_FIELDS, F("trade_date", "date/string", "交易日期。"), F("minute", "string", "分钟。"), F("last_price", "float64", "最新价。"), F("amount", "float64", "成交额。"), F("volume", "float64", "成交量。"), F("open", "float64", "开盘价。"), F("pre_close", "float64", "昨收价。"), F("avg_price", "float64", "均价。")),
        example=RequestExample(request={"params": {"code": "002664.SZ"}, "persist": False}, response=({"instrument_id": "002664.SZ", "minute": "0930", "last_price": 11.5},)),
    ),
    "cls_stock_kline": SourceRequestInterface(
        name="cls_stock_kline",
        display_name_zh="个股K线",
        source_code="cls",
        source_name_zh="财联社",
        category="行情数据",
        request_mode="source_request",
        first_stage_strategy="请求单只股票 K 线，默认不入库。",
        source_ability="CLS stock kline",
        description="Return stock kline rows for one stock.",
        parameters=(P("code", "string", True, "股票代码，支持 002664 或 002664.SZ。"), P("kline_type", "string", False, "K线类型：daily、weekly、monthly、yearly。", "daily"), P("limit", "integer", False, "返回条数，默认 50。", 50), P("offset", "integer", False, "偏移量，默认 0。", 0)),
        fields=(*SECURITY_FIELDS, F("trade_date", "date/string", "交易日期。"), F("open", "float64", "开盘价。"), F("high", "float64", "最高价。"), F("low", "float64", "最低价。"), F("close", "float64", "收盘价。"), F("volume", "float64", "成交量。"), F("amount", "float64", "成交额。"), F("change", "float64", "涨跌额。"), F("change_pct", "float64", "涨跌幅。")),
        example=RequestExample(request={"params": {"code": "002664.SZ", "limit": 5}, "persist": False}, response=({"instrument_id": "002664.SZ", "trade_date": "20260522", "close": 11.5},)),
    ),
    "cls_news_telegraph": SourceRequestInterface(
        name="cls_news_telegraph",
        display_name_zh="电报快讯",
        source_code="cls",
        source_name_zh="财联社",
        category="资讯数据",
        request_mode="source_request",
        first_stage_strategy="请求财联社电报快讯，支持日期和分类，默认不入库。",
        source_ability="CLS telegraph news",
        description="Return CLS telegraph news rows.",
        parameters=(P("date", "string", False, "查询日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"), P("category", "string", False, "分类：all、important、company。", "important"), P("limit", "integer", False, "最多返回条数，默认 20。", 20)),
        fields=(F("news_id", "string", "电报 ID。"), F("title", "string", "标题。"), F("content", "string", "正文。"), F("publish_time", "datetime/string", "发布时间。"), F("ctime", "integer", "发布时间戳。"), F("category", "string", "分类。")),
        example=RequestExample(request={"params": {"category": "important", "limit": 5}, "persist": False}, response=({"title": "重要快讯", "category": "important"},)),
    ),
}
