"""KPH source request interface catalog."""

from __future__ import annotations

from axdata_core.sources.base import (
    RequestExample,
    RequestField,
    RequestParameter,
    SourceRequestInterface,
)


def P(
    name: str,
    dtype: str,
    required: bool,
    zh: str,
    default: object | None = None,
) -> RequestParameter:
    return RequestParameter(name, dtype, required, name, zh, default)


def F(name: str, dtype: str, zh: str) -> RequestField:
    return RequestField(name, dtype, name, zh)


STOCK_FIELDS = (
    F("instrument_id", "string", "AxData 统一证券代码。"),
    F("symbol", "string", "六位证券代码。"),
    F("exchange", "string", "交易所代码：SSE、SZSE、BSE。"),
    F("name", "string", "股票简称。"),
)


LIMIT_HISTORY_FIELDS = (
    F("trade_date", "date/string", "交易日期，格式 YYYYMMDD。"),
    *STOCK_FIELDS,
    F("limit_time", "integer", "涨停/跌停时间戳。"),
    F("open_time", "integer", "开板时间戳，0 表示未开。"),
    F("seal_amount", "float64", "封单量。"),
    F("seal_money", "float64", "封单金额，单位：元。"),
    F("limit_tag", "string", "连板标签。"),
    F("limit_count", "integer", "连板数。"),
    F("themes", "string", "题材。"),
    F("reason", "string", "涨停原因。"),
    F("net_inflow", "float64", "净流入，单位：元。"),
    F("turnover", "float64", "成交额，单位：元。"),
    F("turnover_rate", "float64", "换手率，百分比数值。"),
    F("market_cap", "float64", "流通市值，单位：元。"),
    F("industry_id", "string", "行业 ID。"),
    F("industry_limit_up_count", "integer", "同行业涨停数。"),
)


INTERFACES: dict[str, SourceRequestInterface] = {
    "kph_market_emotion": SourceRequestInterface(
        name="kph_market_emotion",
        display_name_zh="市场情绪",
        source_code="kph",
        source_name_zh="开盘红",
        category="情绪数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红市场情绪，传历史日期走历史接口，默认不入库。",
        source_ability="KPH market emotion realtime/history",
        description="Return KPH market emotion snapshot as one row.",
        parameters=(P("trade_date", "string", False, "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            F("limit_up_count", "integer", "涨停总数。"),
            F("limit_down_count", "integer", "跌停总数。"),
            F("real_limit_up_count", "integer", "实际涨停（非 ST）。"),
            F("real_limit_down_count", "integer", "实际跌停（非 ST）。"),
            F("st_limit_up_count", "integer", "ST 涨停数。"),
            F("st_limit_down_count", "integer", "ST 跌停数。"),
            F("rise_count", "integer", "上涨家数。"),
            F("fall_count", "integer", "下跌家数。"),
            F("flat_count", "integer", "平盘家数。"),
            F("market_sign", "string", "市场人气判断。"),
            F("raw_rise_dist", "object/string", "上涨分布。"),
            F("raw_fall_dist", "object/string", "下跌分布。"),
            F("total_amount", "float64", "全市成交额，单位：元。"),
        ),
        example=RequestExample(request={"params": {"trade_date": "20260513"}, "persist": False}, response=({"trade_date": "20260513", "limit_up_count": 112},)),
    ),
    "kph_sector_ranking": SourceRequestInterface(
        name="kph_sector_ranking",
        display_name_zh="板块排行",
        source_code="kph",
        source_name_zh="开盘红",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红精选/行业/地区板块排行，默认不入库。",
        source_ability="KPH sector ranking",
        description="Return KPH sector ranking rows.",
        parameters=(P("trade_date", "string", True, "交易日期，YYYYMMDD 或 YYYY-MM-DD。"), P("sector_type", "string", False, "板块类型：selected、industry、region，默认 selected。", "selected"), P("fetch_all", "boolean", False, "是否分页获取全部，默认 false。", False)),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            F("plate_id", "string", "板块 ID。"),
            F("plate_name", "string", "板块名称。"),
            F("sector_type", "string", "板块类型。"),
            F("change_pct", "float64", "涨跌幅。"),
            F("amount", "float64", "成交额，单位：元。"),
            F("amplitude", "float64", "振幅。"),
            F("net_inflow", "float64", "净流入，单位：元。"),
            F("turnover_rate", "float64", "换手率。"),
            F("market_cap", "float64", "总市值，单位：元。"),
            F("stock_count", "integer", "成分股数量。"),
        ),
        example=RequestExample(request={"params": {"trade_date": "20260513", "sector_type": "selected"}, "persist": False}, response=({"plate_id": "801807", "plate_name": "算力"},)),
    ),
    "kph_sector_constituents_history": SourceRequestInterface(
        name="kph_sector_constituents_history",
        display_name_zh="历史板块成分股",
        source_code="kph",
        source_name_zh="开盘红",
        category="板块数据",
        request_mode="source_request",
        first_stage_strategy="按开盘红板块 ID 和历史日期请求成分股，默认不入库。",
        source_ability="KPH historical sector constituents",
        description="Return KPH historical sector constituents.",
        parameters=(P("plate_id", "string", True, "板块 ID。"), P("trade_date", "string", True, "历史交易日期，必须早于今天。")),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            F("plate_id", "string", "板块 ID。"),
            *STOCK_FIELDS,
            F("tags", "string", "概念标签。"),
            F("last_price", "float64", "现价。"),
            F("change_pct", "float64", "涨跌幅。"),
            F("amount", "float64", "成交额。"),
            F("turnover_rate", "float64", "换手率。"),
            F("float_market_value", "float64", "流通市值。"),
            F("main_net", "float64", "主力净额。"),
            F("limit_tag", "string", "连板标签。"),
            F("rank_tag", "string", "龙虎榜/龙头标签。"),
            F("limit_count", "integer", "近期涨停次数。"),
        ),
        example=RequestExample(request={"params": {"plate_id": "801001", "trade_date": "20260513"}, "persist": False}, response=({"instrument_id": "000001.SZ", "plate_id": "801001"},)),
    ),
    "kph_limit_up_history": SourceRequestInterface(
        name="kph_limit_up_history",
        display_name_zh="历史涨停股",
        source_code="kph",
        source_name_zh="开盘红",
        category="短线数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红历史涨停股列表，默认不入库。",
        source_ability="KPH historical limit-up stocks",
        description="Return historical limit-up stocks.",
        parameters=(P("trade_date", "string", True, "历史交易日期，必须早于今天。"),),
        fields=LIMIT_HISTORY_FIELDS,
        example=RequestExample(request={"params": {"trade_date": "20260513"}, "persist": False}, response=({"instrument_id": "601126.SH", "limit_tag": "首板"},)),
    ),
    "kph_limit_down_history": SourceRequestInterface(
        name="kph_limit_down_history",
        display_name_zh="历史跌停股",
        source_code="kph",
        source_name_zh="开盘红",
        category="短线数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红历史跌停股列表，默认不入库。",
        source_ability="KPH historical limit-down stocks",
        description="Return historical limit-down stocks.",
        parameters=(P("trade_date", "string", True, "历史交易日期，必须早于今天。"),),
        fields=LIMIT_HISTORY_FIELDS,
        example=RequestExample(request={"params": {"trade_date": "20260513"}, "persist": False}, response=({"instrument_id": "002810.SZ", "seal_money": 0},)),
    ),
    "kph_wind_vane_history": SourceRequestInterface(
        name="kph_wind_vane_history",
        display_name_zh="历史风向标",
        source_code="kph",
        source_name_zh="开盘红",
        category="短线数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红历史风向标股票列表，默认不入库。",
        source_ability="KPH historical wind-vane stocks",
        description="Return historical wind-vane stocks.",
        parameters=(P("trade_date", "string", True, "历史交易日期，必须早于今天。"),),
        fields=LIMIT_HISTORY_FIELDS,
        example=RequestExample(request={"params": {"trade_date": "20260513"}, "persist": False}, response=({"instrument_id": "601126.SH", "themes": "智能电网"},)),
    ),
    "kph_limit_ladder": SourceRequestInterface(
        name="kph_limit_ladder",
        display_name_zh="涨停天梯",
        source_code="kph",
        source_name_zh="开盘红",
        category="复盘数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红涨停天梯，默认不入库。",
        source_ability="KPH limit-up ladder",
        description="Return KPH limit-up ladder rows.",
        parameters=(P("trade_date", "string", False, "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            *STOCK_FIELDS,
            F("limit_count", "integer", "连板数。"),
            F("limit_time", "integer", "涨停时间戳。"),
            F("plate_id", "string", "所属板块 ID。"),
            F("plate_name", "string", "所属板块名称。"),
            F("one_word", "boolean", "是否大单一字。"),
            F("popular", "boolean", "是否有人气。"),
            F("plate_limit_up_count", "integer", "板块涨停股数量。"),
            F("amount", "float64", "个股成交额。"),
            F("plate_amount", "float64", "板块成交额。"),
        ),
        example=RequestExample(request={"params": {}, "persist": False}, response=({"instrument_id": "000001.SZ", "limit_count": 2},)),
    ),
    "kph_market_review_events": SourceRequestInterface(
        name="kph_market_review_events",
        display_name_zh="盘面梳理事件",
        source_code="kph",
        source_name_zh="开盘红",
        category="复盘数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红盘面梳理事件流，默认不入库。",
        source_ability="KPH market review events",
        description="Return KPH market review event rows.",
        parameters=(P("trade_date", "string", False, "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"), P("limit", "integer", False, "返回条数，默认 30。", 30), P("offset", "integer", False, "偏移量，默认 0。", 0)),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            F("event_time", "integer", "事件时间戳。"),
            F("tag_id", "integer", "事件类型 ID。"),
            F("tag_name", "string", "事件类型名称。"),
            F("tag_attribute", "integer", "事件属性。"),
            F("plate_id", "string", "板块 ID。"),
            F("plate_name", "string", "板块名称。"),
            F("detail", "string", "事件描述。"),
            F("raw_stock_list", "object/string", "相关股票列表。"),
        ),
        example=RequestExample(request={"params": {"limit": 5}, "persist": False}, response=({"tag_name": "直线拉升", "plate_name": "芯片"},)),
    ),
    "kph_limit_resumption_history": SourceRequestInterface(
        name="kph_limit_resumption_history",
        display_name_zh="历史涨停复盘",
        source_code="kph",
        source_name_zh="开盘红",
        category="复盘数据",
        request_mode="source_request",
        first_stage_strategy="请求开盘红历史涨停复盘，默认不入库。",
        source_ability="KPH historical limit-up resumption",
        description="Return flattened KPH historical limit resumption rows.",
        parameters=(P("trade_date", "string", False, "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"), P("limit", "integer", False, "返回条数，默认 100。", 100), P("offset", "integer", False, "偏移量，默认 0。", 0)),
        fields=(
            F("trade_date", "date/string", "交易日期。"),
            F("plate_id", "string", "板块 ID。"),
            F("plate_name", "string", "板块名称。"),
            *STOCK_FIELDS,
            F("limit_tag", "string", "连板标签。"),
            F("limit_count", "integer", "连板数。"),
            F("themes", "string", "所属概念。"),
            F("reason_short", "string", "涨停原因短标签。"),
            F("reason_detail", "string", "涨停原因详细文字。"),
        ),
        example=RequestExample(request={"params": {"trade_date": "20260513"}, "persist": False}, response=({"plate_name": "芯片", "instrument_id": "000001.SZ"},)),
    ),
}
