"""Eastmoney source request interface catalog."""

from __future__ import annotations

from axdata_core.sources.base import (
    RequestExample,
    RequestField,
    RequestParameter,
    SourceRequestInterface,
)


COMMON_SECURITY_FIELDS = (
    RequestField("instrument_id", "string", "AxData instrument id.", "AxData 统一证券代码。"),
    RequestField("symbol", "string", "Six-digit symbol.", "六位证券代码。"),
    RequestField("exchange", "string", "Exchange code.", "交易所代码：SSE、SZSE、BSE。"),
    RequestField("name", "string", "Security short name.", "证券简称。"),
)


INTERFACES: dict[str, SourceRequestInterface] = {
    "eastmoney_dragon_tiger_daily": SourceRequestInterface(
        name="eastmoney_dragon_tiger_daily",
        display_name_zh="龙虎榜每日汇总",
        source_code="eastmoney",
        source_name_zh="东方财富",
        category="龙虎榜数据",
        request_mode="source_request",
        first_stage_strategy="低频请求东方财富龙虎榜每日汇总，返回确认字段，默认不入库。",
        source_ability="Eastmoney daily billboard summary",
        description=(
            "Return daily dragon-tiger summary rows. Amount fields are yuan. "
            "change_pct and turnover_rate are percentage numbers."
        ),
        parameters=(
            RequestParameter("trade_date", "string", True, "Trade date.", "交易日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 50，最大 200。", 50),
        ),
        fields=(
            RequestField("trade_date", "date/string", "Trade date.", "交易日期，格式 YYYYMMDD。"),
            *COMMON_SECURITY_FIELDS,
            RequestField("reason", "string", "Billboard reason.", "上榜原因。"),
            RequestField("close_price", "float64", "Close price.", "收盘价，单位：元。"),
            RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
            RequestField("turnover_rate", "float64", "Turnover rate.", "换手率，百分比数值。"),
            RequestField("buy_amount", "float64", "Buy amount.", "龙虎榜买入额，单位：元。"),
            RequestField("sell_amount", "float64", "Sell amount.", "龙虎榜卖出额，单位：元。"),
            RequestField("net_buy_amount", "float64", "Net buy amount.", "龙虎榜净买入额，单位：元。"),
            RequestField("total_amount", "float64", "Total billboard amount.", "龙虎榜成交额，单位：元。"),
            RequestField("market", "string", "Trading market label.", "交易市场标签。"),
        ),
        example=RequestExample(
            request={"params": {"trade_date": "20240102", "limit": 5}, "persist": False},
            response=(
                {
                    "trade_date": "20240102",
                    "instrument_id": "000595.SZ",
                    "symbol": "000595",
                    "exchange": "SZSE",
                    "name": "*ST宝实",
                    "reason": "连续三个交易日内，涨幅偏离值累计达到20%的证券",
                    "close_price": 5.7,
                    "change_pct": 10.0386,
                    "turnover_rate": 5.0939,
                    "buy_amount": 79387344.0,
                    "sell_amount": 41045941.7,
                    "net_buy_amount": 38341402.3,
                    "total_amount": 120433285.7,
                    "market": "深交所风险警示板",
                },
            ),
        ),
    ),
    "eastmoney_margin_trading": SourceRequestInterface(
        name="eastmoney_margin_trading",
        display_name_zh="融资融券明细",
        source_code="eastmoney",
        source_name_zh="东方财富",
        category="融资融券数据",
        request_mode="source_request",
        first_stage_strategy="低频请求东方财富单股融资融券明细，返回确认字段，默认不入库。",
        source_ability="Eastmoney stock margin trading details",
        description=(
            "Return stock margin-trading rows. Amount and balance fields are yuan. "
            "Securities-lending quantity fields are shares. Empty source results are returned as empty data."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 000001、000001.SZ。"),
            RequestParameter("start_date", "string", False, "Start date.", "开始日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("end_date", "string", False, "End date.", "结束日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 50，最大 200。", 50),
        ),
        fields=(
            RequestField("trade_date", "date/string", "Trade date.", "交易日期，格式 YYYYMMDD。"),
            *COMMON_SECURITY_FIELDS,
            RequestField("market", "string", "Trading market label.", "交易市场标签。"),
            RequestField("close_price", "float64", "Close price.", "收盘价，单位：元。"),
            RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
            RequestField("margin_balance", "float64", "Financing balance.", "融资余额，单位：元。"),
            RequestField("margin_buy_amount", "float64", "Financing buy amount.", "融资买入额，单位：元。"),
            RequestField("margin_repay_amount", "float64", "Financing repay amount.", "融资偿还额，单位：元。"),
            RequestField("margin_net_buy_amount", "float64", "Financing net buy amount.", "融资净买入额，单位：元。"),
            RequestField("short_balance", "float64", "Securities lending balance.", "融券余额，单位：元。"),
            RequestField("short_sell_volume", "float64", "Short sell volume.", "融券卖出量，单位：股。"),
            RequestField("short_repay_volume", "float64", "Short repay volume.", "融券偿还量，单位：股。"),
            RequestField("short_net_sell_volume", "float64", "Short net sell volume.", "融券净卖出量，单位：股。"),
            RequestField("total_balance", "float64", "Total margin balance.", "融资融券余额，单位：元。"),
            RequestField("market_value", "float64", "Market value.", "总市值，单位：元。"),
        ),
        example=RequestExample(
            request={
                "params": {
                    "code": "000001.SZ",
                    "start_date": "20240102",
                    "end_date": "20240105",
                    "limit": 5,
                },
                "persist": False,
            },
            response=(
                {
                    "trade_date": "20240105",
                    "instrument_id": "000001.SZ",
                    "symbol": "000001",
                    "exchange": "SZSE",
                    "name": "平安银行",
                    "market": "深交所主板",
                    "close_price": 9.27,
                    "change_pct": 1.7563,
                    "margin_balance": 5105063089.0,
                    "margin_buy_amount": 266715372.0,
                    "margin_repay_amount": 325760031.0,
                    "margin_net_buy_amount": -59044659.0,
                    "short_balance": 106309509.0,
                    "short_sell_volume": 564400.0,
                    "short_repay_volume": 201500.0,
                    "short_net_sell_volume": 362900.0,
                    "total_balance": 5211372598.0,
                    "market_value": 179889420226.5,
                },
            ),
        ),
    ),
    "eastmoney_research_reports": SourceRequestInterface(
        name="eastmoney_research_reports",
        display_name_zh="个股研报列表",
        source_code="eastmoney",
        source_name_zh="东方财富",
        category="研报数据",
        request_mode="source_request",
        first_stage_strategy="低频请求东方财富研报列表，只返回研报元信息，默认不抓取 PDF、不入库。",
        source_ability="Eastmoney stock research report list",
        description=(
            "Return stock research-report list metadata. EPS fields are yuan/share. "
            "PE fields are ratio values. file_size_kb is the source attachment size in KB."
        ),
        parameters=(
            RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 000001、000001.SZ。"),
            RequestParameter("start_date", "string", False, "Start publish date.", "开始发布日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("end_date", "string", False, "End publish date.", "结束发布日期，YYYYMMDD 或 YYYY-MM-DD。"),
            RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
            RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 20，最大 100。", 20),
        ),
        fields=(
            RequestField("report_id", "string", "Report id.", "研报 ID。"),
            *COMMON_SECURITY_FIELDS,
            RequestField("title", "string", "Report title.", "研报标题。"),
            RequestField("publish_date", "date/string", "Publish date.", "发布日期，格式 YYYYMMDD。"),
            RequestField("org_name", "string", "Research organization.", "研究机构。"),
            RequestField("rating", "string", "Rating text.", "评级。"),
            RequestField("rating_change", "string", "Rating change code from source.", "评级变动源端值。"),
            RequestField("researcher", "string", "Researcher names.", "研究员。"),
            RequestField("eps_forecast_this_year", "float64", "This-year EPS forecast.", "本年度 EPS 预测，单位：元/股。"),
            RequestField("pe_forecast_this_year", "float64", "This-year PE forecast.", "本年度 PE 预测，倍。"),
            RequestField("file_size_kb", "float64", "Attachment size in KB.", "附件大小，单位：KB。"),
            RequestField("page_count", "integer", "Attachment page count.", "附件页数。"),
        ),
        example=RequestExample(
            request={
                "params": {
                    "code": "000001.SZ",
                    "start_date": "20240101",
                    "end_date": "20241231",
                    "limit": 5,
                },
                "persist": False,
            },
            response=(
                {
                    "report_id": "AP202410221640398395",
                    "instrument_id": "000001.SZ",
                    "symbol": "000001",
                    "exchange": "SZSE",
                    "name": "平安银行",
                    "title": "2024年三季报点评：零售业务调优结构，存款成本持续改善",
                    "publish_date": "20241022",
                    "org_name": "东兴证券股份有限公司",
                    "rating": "买入",
                    "rating_change": "3",
                    "researcher": "林瑾璐,田馨宇",
                    "eps_forecast_this_year": 2.6,
                    "pe_forecast_this_year": 4.54,
                    "file_size_kb": 960.0,
                    "page_count": 8,
                },
            ),
        ),
    ),
}


QUOTE_FIELDS = (
    *COMMON_SECURITY_FIELDS,
    RequestField("last_price", "float64", "Latest price.", "最新价，单位：元。"),
    RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
    RequestField("change", "float64", "Price change.", "涨跌额，单位：元。"),
    RequestField("volume", "float64", "Volume.", "成交量，源端口径。"),
    RequestField("amount", "float64", "Amount in yuan.", "成交额，单位：元。"),
    RequestField("amplitude", "float64", "Amplitude percent.", "振幅，百分比数值。"),
    RequestField("turnover_rate", "float64", "Turnover rate.", "换手率，百分比数值。"),
    RequestField("pe_ttm", "float64", "TTM PE.", "市盈率 TTM。"),
    RequestField("volume_ratio", "float64", "Volume ratio.", "量比。"),
    RequestField("high", "float64", "High price.", "最高价，单位：元。"),
    RequestField("low", "float64", "Low price.", "最低价，单位：元。"),
    RequestField("open", "float64", "Open price.", "开盘价，单位：元。"),
    RequestField("pre_close", "float64", "Previous close.", "昨收价，单位：元。"),
    RequestField("total_market_value", "float64", "Total market value in yuan.", "总市值，单位：元。"),
    RequestField("float_market_value", "float64", "Float market value in yuan.", "流通市值，单位：元。"),
    RequestField("pb", "float64", "PB ratio.", "市净率。"),
)


SECTOR_QUOTE_FIELDS = (
    RequestField("sector_code", "string", "Sector code.", "板块代码。"),
    RequestField("sector_name", "string", "Sector name.", "板块名称。"),
    RequestField("sector_type", "string", "Sector type.", "板块类型。"),
    RequestField("last_price", "float64", "Latest sector price.", "板块最新价。"),
    RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
    RequestField("change", "float64", "Price change.", "涨跌额。"),
    RequestField("volume", "float64", "Volume.", "成交量，源端口径。"),
    RequestField("amount", "float64", "Amount in yuan.", "成交额，单位：元。"),
    RequestField("amplitude", "float64", "Amplitude percent.", "振幅，百分比数值。"),
    RequestField("turnover_rate", "float64", "Turnover rate.", "换手率，百分比数值。"),
    RequestField("total_market_value", "float64", "Total market value in yuan.", "总市值，单位：元。"),
    RequestField("main_inflow", "float64", "Main fund inflow in yuan.", "主力净流入，单位：元。"),
    RequestField("lead_stock_name", "string", "Leading stock name.", "领涨股名称。"),
    RequestField("lead_stock_symbol", "string", "Leading stock symbol.", "领涨股六位代码。"),
    RequestField("lead_stock_change_pct", "float64", "Leading stock change percent.", "领涨股涨跌幅。"),
    RequestField("up_count", "integer", "Rising constituent count.", "上涨家数。"),
    RequestField("down_count", "integer", "Falling constituent count.", "下跌家数。"),
)


LIMIT_POOL_FIELDS = (
    RequestField("trade_date", "date/string", "Trade date.", "交易日期，格式 YYYYMMDD。"),
    *COMMON_SECURITY_FIELDS,
    RequestField("market_code", "string", "Eastmoney market code.", "东方财富市场代码。"),
    RequestField("last_price", "float64", "Latest price.", "最新价，单位：元。"),
    RequestField("limit_price", "float64", "Limit price.", "涨停/跌停价，单位：元。"),
    RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
    RequestField("amount", "float64", "Amount in yuan.", "成交额，单位：元。"),
    RequestField("float_market_value", "float64", "Float market value.", "流通市值，单位：元。"),
    RequestField("turnover_rate", "float64", "Turnover rate.", "换手率，百分比数值。"),
    RequestField("first_limit_time", "string", "First limit-up time.", "首次涨停时间。"),
    RequestField("last_limit_time", "string", "Last limit time.", "最后涨停/跌停时间。"),
    RequestField("continuous_count", "integer", "Continuous board count.", "连板/连续跌停次数。"),
    RequestField("open_times", "integer", "Limit open count.", "炸板/开板次数。"),
    RequestField("main_inflow", "float64", "Main fund inflow.", "主力净流入，单位：元。"),
    RequestField("sector", "string", "Sector text.", "所属行业/板块。"),
)


INTERFACES.update(
    {
        "eastmoney_market_index_realtime": SourceRequestInterface(
            name="eastmoney_market_index_realtime",
            display_name_zh="大盘指数实时行情",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="指数数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富指数实时行情，默认只返回常用指数，默认不入库。",
            source_ability="Eastmoney A-share market index realtime quotes",
            description="Return Eastmoney A-share market index realtime quotes.",
            parameters=(
                RequestParameter("scope", "string", False, "Index scope.", "指数范围：default 常用指数，all 全部指数。", "default"),
                RequestParameter("limit", "integer", False, "Maximum rows.", "最多返回条数，默认 100。", 100),
            ),
            fields=(
                RequestField("index_code", "string", "Index code.", "指数代码。"),
                RequestField("index_name", "string", "Index name.", "指数名称。"),
                RequestField("last_price", "float64", "Latest price.", "最新价。"),
                RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
                RequestField("change", "float64", "Price change.", "涨跌额。"),
                RequestField("volume", "float64", "Volume.", "成交量，源端口径。"),
                RequestField("amount", "float64", "Amount in yuan.", "成交额，单位：元。"),
                RequestField("high", "float64", "High price.", "最高价。"),
                RequestField("low", "float64", "Low price.", "最低价。"),
                RequestField("open", "float64", "Open price.", "开盘价。"),
                RequestField("pre_close", "float64", "Previous close.", "昨收价。"),
            ),
            example=RequestExample(
                request={"params": {"scope": "default", "limit": 6}, "persist": False},
                response=({"index_code": "000001", "index_name": "上证指数", "last_price": 3200.5},),
            ),
        ),
        "eastmoney_stock_realtime_snapshot": SourceRequestInterface(
            name="eastmoney_stock_realtime_snapshot",
            display_name_zh="A股实时行情快照",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="实时数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富 A 股实时行情；传 code 查指定股票，不传 code 按页返回小样本，默认不入库。",
            source_ability="Eastmoney A-share realtime stock quote snapshot",
            description="Return Eastmoney stock realtime quote rows.",
            parameters=(
                RequestParameter("code", "string/list", False, "Stock code(s).", "股票代码，可传 000001.SZ 或逗号分隔多只。"),
                RequestParameter("filter_st", "boolean", False, "Filter ST stocks.", "是否过滤 ST、*ST 和低价退市风险股，默认 true。", True),
                RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
                RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 50，最大 200。", 50),
            ),
            fields=QUOTE_FIELDS,
            example=RequestExample(
                request={"params": {"code": "000001.SZ"}, "persist": False},
                response=({"instrument_id": "000001.SZ", "name": "平安银行", "last_price": 10.64},),
            ),
        ),
        "eastmoney_sector_realtime": SourceRequestInterface(
            name="eastmoney_sector_realtime",
            display_name_zh="板块实时行情",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="板块数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富行业/概念板块行情，默认不入库。",
            source_ability="Eastmoney sector realtime quotes",
            description="Return Eastmoney industry/concept sector realtime quotes.",
            parameters=(
                RequestParameter("sector_type", "string", False, "Sector type.", "板块类型：industry、concept、industry_l1、industry_l2、industry_l3。", "industry"),
                RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
                RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 100，最大 200。", 100),
            ),
            fields=SECTOR_QUOTE_FIELDS,
            example=RequestExample(
                request={"params": {"sector_type": "industry", "limit": 5}, "persist": False},
                response=({"sector_code": "BK0475", "sector_name": "银行", "change_pct": 1.2},),
            ),
        ),
        "eastmoney_sector_constituents": SourceRequestInterface(
            name="eastmoney_sector_constituents",
            display_name_zh="板块成分股",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="板块数据",
            request_mode="source_request",
            first_stage_strategy="按东方财富板块代码请求成分股，默认不入库。",
            source_ability="Eastmoney sector constituents",
            description="Return constituents of an Eastmoney sector.",
            parameters=(
                RequestParameter("sector_code", "string", True, "Sector code.", "板块代码，例如 BK1033。"),
                RequestParameter("page", "integer", False, "Page number.", "页码，默认 1。", 1),
                RequestParameter("limit", "integer", False, "Page size.", "每页条数，默认 100，最大 200。", 100),
            ),
            fields=QUOTE_FIELDS,
            example=RequestExample(
                request={"params": {"sector_code": "BK1033", "limit": 5}, "persist": False},
                response=({"instrument_id": "000049.SZ", "name": "德赛电池", "last_price": 32.1},),
            ),
        ),
        "eastmoney_stock_sector_belong": SourceRequestInterface(
            name="eastmoney_stock_sector_belong",
            display_name_zh="个股所属板块",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="板块数据",
            request_mode="source_request",
            first_stage_strategy="批量查询股票所属行业板块，默认不入库。",
            source_ability="Eastmoney stock sector belonging",
            description="Return Eastmoney sector names for requested stocks.",
            parameters=(RequestParameter("code", "string/list", True, "Stock code(s).", "股票代码，支持逗号分隔多只。"),),
            fields=(
                *COMMON_SECURITY_FIELDS,
                RequestField("sector_name", "string", "Sector name.", "所属行业板块。"),
            ),
            example=RequestExample(
                request={"params": {"code": "000001.SZ"}, "persist": False},
                response=({"instrument_id": "000001.SZ", "name": "平安银行", "sector_name": "银行"},),
            ),
        ),
        "eastmoney_limit_up_pool": SourceRequestInterface(
            name="eastmoney_limit_up_pool",
            display_name_zh="涨停池",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="短线数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富涨停池，支持指定交易日，默认不入库。",
            source_ability="Eastmoney limit-up pool",
            description="Return Eastmoney limit-up pool rows.",
            parameters=(RequestParameter("trade_date", "string", False, "Trade date.", "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),),
            fields=LIMIT_POOL_FIELDS,
            example=RequestExample(
                request={"params": {"trade_date": "20260703"}, "persist": False},
                response=({"trade_date": "20260703", "instrument_id": "000595.SZ", "continuous_count": 2},),
            ),
        ),
        "eastmoney_limit_down_pool": SourceRequestInterface(
            name="eastmoney_limit_down_pool",
            display_name_zh="跌停池",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="短线数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富跌停池，支持指定交易日，默认不入库。",
            source_ability="Eastmoney limit-down pool",
            description="Return Eastmoney limit-down pool rows.",
            parameters=(RequestParameter("trade_date", "string", False, "Trade date.", "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),),
            fields=LIMIT_POOL_FIELDS,
            example=RequestExample(
                request={"params": {"trade_date": "20260703"}, "persist": False},
                response=({"trade_date": "20260703", "instrument_id": "000890.SZ", "change_pct": -9.977827072143555},),
            ),
        ),
        "eastmoney_yesterday_limit_up_pool": SourceRequestInterface(
            name="eastmoney_yesterday_limit_up_pool",
            display_name_zh="昨日涨停今日表现",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="短线数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富昨日涨停今日表现，默认不入库。",
            source_ability="Eastmoney yesterday limit-up performance",
            description="Return performance of yesterday limit-up stocks.",
            parameters=(RequestParameter("trade_date", "string", False, "Trade date.", "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),),
            fields=(
                *LIMIT_POOL_FIELDS,
                RequestField("amplitude", "float64", "Amplitude percent.", "振幅，百分比数值。"),
                RequestField("open_ratio", "float64", "Open ratio.", "高开比，百分比数值。"),
                RequestField("yesterday_limit_time", "string", "Yesterday limit-up time.", "昨日涨停时间。"),
                RequestField("yesterday_continuous_count", "integer", "Yesterday continuous board count.", "昨日连板数。"),
            ),
            example=RequestExample(
                request={"params": {"trade_date": "20260703"}, "persist": False},
                response=({"trade_date": "20260703", "instrument_id": "002798.SZ", "open_ratio": 1.4285714626312256},),
            ),
        ),
        "eastmoney_stock_changes": SourceRequestInterface(
            name="eastmoney_stock_changes",
            display_name_zh="盘口异动列表",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="短线数据",
            request_mode="source_request",
            first_stage_strategy="请求东方财富盘口异动列表，默认不入库。",
            source_ability="Eastmoney stock intraday changes",
            description="Return Eastmoney stock change rows for one change type.",
            parameters=(
                RequestParameter("change_type", "string", False, "Change type code.", "异动类型编码，默认 8201（火箭发射）。", "8201"),
                RequestParameter("filter_st", "boolean", False, "Filter ST stocks.", "是否过滤 ST 和三板股票，默认 true。", True),
            ),
            fields=(
                *COMMON_SECURITY_FIELDS,
                RequestField("market_code", "string", "Eastmoney market code.", "东方财富市场代码。"),
                RequestField("change_time", "string", "Change time.", "异动时间，HHMMSS。"),
                RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
                RequestField("change_type", "string", "Change type code.", "异动类型编码。"),
                RequestField("change_type_name", "string", "Change type name.", "异动类型名称。"),
            ),
            example=RequestExample(
                request={"params": {"change_type": "8201"}, "persist": False},
                response=({"instrument_id": "000001.SZ", "change_type_name": "火箭发射"},),
            ),
        ),
        "eastmoney_stock_change_detail": SourceRequestInterface(
            name="eastmoney_stock_change_detail",
            display_name_zh="个股盘口异动明细",
            source_code="eastmoney",
            source_name_zh="东方财富",
            category="短线数据",
            request_mode="source_request",
            first_stage_strategy="请求单只股票盘口异动明细，默认不入库。",
            source_ability="Eastmoney stock change detail",
            description="Return detailed intraday change records for one stock.",
            parameters=(
                RequestParameter("code", "string", True, "Stock code.", "股票代码，支持 000001.SZ。"),
                RequestParameter("market", "string", False, "Eastmoney market code.", "东方财富市场代码，0=深/北，1=沪；不传则按代码推断。"),
                RequestParameter("trade_date", "string", False, "Trade date.", "交易日期，YYYYMMDD 或 YYYY-MM-DD，默认今天。"),
            ),
            fields=(
                RequestField("trade_date", "date/string", "Trade date.", "交易日期。"),
                *COMMON_SECURITY_FIELDS,
                RequestField("market_code", "string", "Eastmoney market code.", "东方财富市场代码。"),
                RequestField("change_time", "string", "Change time.", "异动时间，HHMMSS。"),
                RequestField("change_type", "string", "Change type code.", "异动类型编码。"),
                RequestField("change_type_name", "string", "Change type name.", "异动类型名称。"),
                RequestField("price", "float64", "Price.", "价格，单位：元。"),
                RequestField("change_pct", "float64", "Change percent.", "涨跌幅，百分比数值。"),
                RequestField("volume", "float64", "Volume.", "成交量，源端口径。"),
            ),
            example=RequestExample(
                request={"params": {"code": "301520.SZ", "trade_date": "20260703"}, "persist": False},
                response=({"instrument_id": "301520.SZ", "change_type_name": "火箭发射", "price": 356.7},),
            ),
        ),
    }
)
