"""Provider-owned TDX command defaults kept outside command runtimes."""

DEFAULT_AUCTION_MODE = 3
DEFAULT_AUCTION_COUNT = 500
DEFAULT_TODAY_INTRADAY_RESERVED_TAIL = b"\x00\x00\x00\x93"
RECENT_HISTORICAL_INTRADAY_DATE_BASE = 0xFED62304
FILE_PATH_FIELD_SIZE = 300

__all__ = [
    "DEFAULT_AUCTION_COUNT",
    "DEFAULT_AUCTION_MODE",
    "DEFAULT_TODAY_INTRADAY_RESERVED_TAIL",
    "FILE_PATH_FIELD_SIZE",
    "RECENT_HISTORICAL_INTRADAY_DATE_BASE",
]
